// APEX Template Generator — Oracle APEX with Boostr CRM Integration
// Generates complete APEX app export + Oracle schema for manual workspace import

export interface ApexTemplate {
  schemaSql: string;
  appExportSql: string;
  readmeMd: string;
}

export interface BoostrConfig {
  apiBaseUrl: string;
  endpoints: string[];
  syncFrequency: 'manual' | 'hourly' | '2hours' | '4hours' | 'daily' | 'nightly' | 'weekly';
  duplicateRules: {
    customers: string[];
    invoices: string[];
    campaigns: string[];
    insertionOrders: string[];
    evidenceReports: string[];
  };
}

export const DEFAULT_BOOSTR_CONFIG: BoostrConfig = {
  apiBaseUrl: 'https://api.boostr.com/v1',
  endpoints: ['customers', 'invoices', 'campaigns', 'insertion_orders', 'evidence_reports'],
  syncFrequency: 'daily',
  duplicateRules: {
    customers: ['boostr_customer_id', 'email', 'company_name'],
    invoices: ['invoice_number', 'customer_id'],
    campaigns: ['boostr_campaign_id', 'name'],
    insertionOrders: ['io_number', 'campaign_id'],
    evidenceReports: ['report_id', 'campaign_id'],
  },
};

/**
 * Generate Oracle schema for Boostr-integrated APEX CRM
 */
export function generateBoostrSchema(projectName: string): string {
  const safePrefix = projectName.toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 20);

  return `-- Oracle APEX Schema for ${projectName}
-- Boostr CRM Integration with Duplicate Detection
-- Generated by BuildAny (Jason)

-- =====================================================
-- 1. CONFIGURATION TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_boostr_config (
  config_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  api_base_url     VARCHAR2(500)  NOT NULL DEFAULT 'https://api.boostr.com/v1',
  auth_token       VARCHAR2(2000),  -- OAuth2 bearer token (encrypted via APEX wallet)
  client_id        VARCHAR2(500),
  client_secret    VARCHAR2(1000),
  endpoints        VARCHAR2(4000)  NOT NULL DEFAULT 'customers,invoices,campaigns,insertion_orders,evidence_reports',
  sync_frequency   VARCHAR2(50)    NOT NULL DEFAULT 'daily'
    CONSTRAINT chk_sync_freq CHECK (sync_frequency IN ('manual','hourly','2hours','4hours','daily','nightly','weekly')),
  sync_hour        NUMBER(2)       DEFAULT 2,  -- For nightly/daily: hour of day (0-23)
  sync_minute      NUMBER(2)       DEFAULT 0,  -- Minute of hour (0-59)
  is_active        CHAR(1)         DEFAULT 'Y' CONSTRAINT chk_active CHECK (is_active IN ('Y','N')),
  created_by       VARCHAR2(100)   DEFAULT USER,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  updated_by       VARCHAR2(100),
  updated_date     TIMESTAMP,
  CONSTRAINT uq_boostr_config UNIQUE (config_id)
);

COMMENT ON TABLE ${safePrefix}_boostr_config IS 'Boostr API configuration and sync settings';
COMMENT ON COLUMN ${safePrefix}_boostr_config.auth_token IS 'OAuth2 access token - store encrypted in production';
COMMENT ON COLUMN ${safePrefix}_boostr_config.sync_frequency IS 'How often to run sync: manual, hourly, 2hours, 4hours, daily, nightly, weekly';

-- Insert default configuration
INSERT INTO ${safePrefix}_boostr_config (api_base_url, endpoints, sync_frequency, sync_hour)
VALUES ('https://api.boostr.com/v1', 'customers,invoices,campaigns,insertion_orders,evidence_reports', 'daily', 2);

-- =====================================================
-- 2. DUPLICATE DETECTION RULES TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_duplicate_rules (
  rule_id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type      VARCHAR2(50)    NOT NULL
    CONSTRAINT chk_entity_type CHECK (entity_type IN ('customers','invoices','campaigns','insertion_orders','evidence_reports')),
  match_field_1    VARCHAR2(100)   NOT NULL,  -- Primary match field
  match_field_2    VARCHAR2(100),             -- Secondary match (optional)
  match_field_3    VARCHAR2(100),             -- Tertiary match (optional)
  match_logic      VARCHAR2(20)    DEFAULT 'AND'
    CONSTRAINT chk_match_logic CHECK (match_logic IN ('AND','OR')),
  fuzzy_match      CHAR(1)         DEFAULT 'N' CONSTRAINT chk_fuzzy CHECK (fuzzy_match IN ('Y','N')),
  fuzzy_threshold  NUMBER(3,2)     DEFAULT 0.85,  -- 0.0 to 1.0 (85% similarity)
  action_on_dup    VARCHAR2(20)    DEFAULT 'skip'
    CONSTRAINT chk_dup_action CHECK (action_on_dup IN ('skip','update','flag','merge')),
  is_active        CHAR(1)         DEFAULT 'Y',
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_dup_rules UNIQUE (entity_type)
);

COMMENT ON TABLE ${safePrefix}_duplicate_rules IS 'Duplicate detection rules per entity type';

-- Insert default duplicate detection rules
INSERT INTO ${safePrefix}_duplicate_rules (entity_type, match_field_1, match_field_2, match_field_3, match_logic, fuzzy_match, action_on_dup)
VALUES ('customers', 'boostr_customer_id', 'email', 'company_name', 'OR', 'Y', 'update');

INSERT INTO ${safePrefix}_duplicate_rules (entity_type, match_field_1, match_field_2, match_logic, fuzzy_match, action_on_dup)
VALUES ('invoices', 'invoice_number', 'customer_id', NULL, 'AND', 'N', 'skip');

INSERT INTO ${safePrefix}_duplicate_rules (entity_type, match_field_1, match_field_2, match_logic, fuzzy_match, action_on_dup)
VALUES ('campaigns', 'boostr_campaign_id', 'name', 'OR', 'Y', 'update');

INSERT INTO ${safePrefix}_duplicate_rules (entity_type, match_field_1, match_field_2, match_logic, fuzzy_match, action_on_dup)
VALUES ('insertion_orders', 'io_number', 'campaign_id', 'AND', 'N', 'skip');

INSERT INTO ${safePrefix}_duplicate_rules (entity_type, match_field_1, match_field_2, match_logic, fuzzy_match, action_on_dup)
VALUES ('evidence_reports', 'report_id', 'campaign_id', 'AND', 'N', 'skip');

-- =====================================================
-- 3. CUSTOMERS TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_customers (
  customer_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  boostr_customer_id VARCHAR2(100) NOT NULL,
  company_name     VARCHAR2(500)   NOT NULL,
  email            VARCHAR2(500),
  phone            VARCHAR2(100),
  website          VARCHAR2(500),
  industry         VARCHAR2(200),
  address          VARCHAR2(1000),
  city             VARCHAR2(200),
  state            VARCHAR2(100),
  zip              VARCHAR2(50),
  country          VARCHAR2(100),
  account_manager  VARCHAR2(200),
  annual_revenue   NUMBER(18,2),
  employee_count   NUMBER,
  status           VARCHAR2(50)    DEFAULT 'active',
  tags             VARCHAR2(1000),  -- JSON array of tags
  boostr_raw_data  CLOB,            -- Full JSON from Boostr API
  duplicate_status VARCHAR2(20)    DEFAULT 'clean'
    CONSTRAINT chk_cust_dup CHECK (duplicate_status IN ('clean','duplicate','merged','flagged')),
  last_sync_date   TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  updated_date     TIMESTAMP,
  CONSTRAINT uq_boostr_cust_id UNIQUE (boostr_customer_id)
);

CREATE INDEX idx_${safePrefix}_cust_email ON ${safePrefix}_customers(email);
CREATE INDEX idx_${safePrefix}_cust_name ON ${safePrefix}_customers(company_name);
CREATE INDEX idx_${safePrefix}_cust_status ON ${safePrefix}_customers(status);
CREATE INDEX idx_${safePrefix}_cust_dup ON ${safePrefix}_customers(duplicate_status);

COMMENT ON TABLE ${safePrefix}_customers IS 'Customers synced from Boostr with duplicate detection';

-- =====================================================
-- 4. INVOICES TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_invoices (
  invoice_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  boostr_invoice_id VARCHAR2(100),
  invoice_number   VARCHAR2(100)   NOT NULL,
  customer_id      NUMBER          REFERENCES ${safePrefix}_customers(customer_id),
  boostr_customer_id VARCHAR2(100),
  invoice_date     DATE            NOT NULL,
  due_date         DATE,
  amount           NUMBER(18,2)    NOT NULL,
  tax_amount       NUMBER(18,2)    DEFAULT 0,
  total_amount     NUMBER(18,2)    NOT NULL,
  currency         VARCHAR2(10)    DEFAULT 'USD',
  status           VARCHAR2(50)    DEFAULT 'pending'
    CONSTRAINT chk_inv_status CHECK (status IN ('pending','paid','overdue','cancelled','draft')),
  line_items       CLOB,            -- JSON array of line items
  notes            VARCHAR2(4000),
  boostr_raw_data  CLOB,
  duplicate_status VARCHAR2(20)    DEFAULT 'clean'
    CONSTRAINT chk_inv_dup CHECK (duplicate_status IN ('clean','duplicate','flagged')),
  last_sync_date   TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  updated_date     TIMESTAMP,
  CONSTRAINT uq_inv_number_cust UNIQUE (invoice_number, boostr_customer_id)
);

CREATE INDEX idx_${safePrefix}_inv_customer ON ${safePrefix}_invoices(customer_id);
CREATE INDEX idx_${safePrefix}_inv_date ON ${safePrefix}_invoices(invoice_date);
CREATE INDEX idx_${safePrefix}_inv_status ON ${safePrefix}_invoices(status);
CREATE INDEX idx_${safePrefix}_inv_dup ON ${safePrefix}_invoices(duplicate_status);

COMMENT ON TABLE ${safePrefix}_invoices IS 'Invoices synced from Boostr';

-- =====================================================
-- 5. CAMPAIGNS TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_campaigns (
  campaign_id      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  boostr_campaign_id VARCHAR2(100) NOT NULL,
  campaign_name    VARCHAR2(500)   NOT NULL,
  customer_id      NUMBER          REFERENCES ${safePrefix}_customers(customer_id),
  boostr_customer_id VARCHAR2(100),
  start_date       DATE,
  end_date         DATE,
  budget           NUMBER(18,2),
  spent            NUMBER(18,2)    DEFAULT 0,
  status           VARCHAR2(50)    DEFAULT 'planning'
    CONSTRAINT chk_camp_status CHECK (status IN ('planning','active','paused','completed','cancelled')),
  media_type       VARCHAR2(200),   -- TV, Digital, Print, Radio, etc.
  target_audience  VARCHAR2(1000),
  boostr_raw_data  CLOB,
  duplicate_status VARCHAR2(20)    DEFAULT 'clean',
  last_sync_date   TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  updated_date     TIMESTAMP,
  CONSTRAINT uq_boostr_campaign UNIQUE (boostr_campaign_id)
);

CREATE INDEX idx_${safePrefix}_camp_customer ON ${safePrefix}_campaigns(customer_id);
CREATE INDEX idx_${safePrefix}_camp_status ON ${safePrefix}_campaigns(status);

-- =====================================================
-- 6. INSERTION ORDERS (IO) TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_insertion_orders (
  io_id            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  boostr_io_id     VARCHAR2(100),
  io_number        VARCHAR2(100)   NOT NULL,
  campaign_id      NUMBER          REFERENCES ${safePrefix}_campaigns(campaign_id),
  boostr_campaign_id VARCHAR2(100),
  publisher        VARCHAR2(500),
  placement        VARCHAR2(500),
  start_date       DATE,
  end_date         DATE,
  amount           NUMBER(18,2),
  impressions_goal NUMBER,
  impressions_delivered NUMBER DEFAULT 0,
  clicks_goal      NUMBER,
  clicks_delivered NUMBER DEFAULT 0,
  status           VARCHAR2(50)    DEFAULT 'pending',
  boostr_raw_data  CLOB,
  duplicate_status VARCHAR2(20)    DEFAULT 'clean',
  last_sync_date   TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_io_number UNIQUE (io_number, campaign_id)
);

-- =====================================================
-- 7. EVIDENCE REPORTS TABLE
-- =====================================================
CREATE TABLE ${safePrefix}_evidence_reports (
  report_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  boostr_report_id VARCHAR2(100)   NOT NULL,
  campaign_id      NUMBER          REFERENCES ${safePrefix}_campaigns(campaign_id),
  io_id            NUMBER          REFERENCES ${safePrefix}_insertion_orders(io_id),
  report_type      VARCHAR2(100),   -- Delivery, Performance, Attribution
  report_date      DATE,
  file_url         VARCHAR2(1000),
  file_name        VARCHAR2(500),
  file_size        NUMBER,          -- bytes
  metrics          CLOB,            -- JSON with impressions, clicks, CTR, etc.
  boostr_raw_data  CLOB,
  duplicate_status VARCHAR2(20)    DEFAULT 'clean',
  last_sync_date   TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_boostr_report UNIQUE (boostr_report_id)
);

-- =====================================================
-- 8. SYNC AUDIT LOG
-- =====================================================
CREATE TABLE ${safePrefix}_sync_log (
  log_id           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sync_type        VARCHAR2(50)    NOT NULL,  -- 'customers','invoices','campaigns','insertion_orders','evidence_reports'
  sync_mode        VARCHAR2(20)    DEFAULT 'manual' CONSTRAINT chk_sync_mode CHECK (sync_mode IN ('manual','scheduled','api')),
  status           VARCHAR2(20)    NOT NULL   CONSTRAINT chk_sync_status CHECK (status IN ('started','success','partial','failed')),
  records_processed NUMBER         DEFAULT 0,
  records_inserted  NUMBER         DEFAULT 0,
  records_updated   NUMBER         DEFAULT 0,
  records_skipped   NUMBER         DEFAULT 0,
  records_flagged   NUMBER         DEFAULT 0,
  error_message    VARCHAR2(4000),
  request_payload  CLOB,            -- JSON sent to Boostr
  response_payload CLOB,            -- JSON received from Boostr
  duration_seconds NUMBER,
  started_by       VARCHAR2(100)   DEFAULT USER,
  started_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  completed_date   TIMESTAMP
);

CREATE INDEX idx_${safePrefix}_sync_type ON ${safePrefix}_sync_log(sync_type);
CREATE INDEX idx_${safePrefix}_sync_status ON ${safePrefix}_sync_log(status);
CREATE INDEX idx_${safePrefix}_sync_date ON ${safePrefix}_sync_log(started_date);

COMMENT ON TABLE ${safePrefix}_sync_log IS 'Audit log for all Boostr sync operations';

-- =====================================================
-- 9. DUPLICATE REVIEW QUEUE
-- =====================================================
CREATE TABLE ${safePrefix}_duplicate_review (
  review_id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_type      VARCHAR2(50)    NOT NULL,
  entity_id        NUMBER          NOT NULL,
  boostr_id        VARCHAR2(100),
  match_score      NUMBER(5,2),     -- 0-100 similarity score
  matched_entity_id NUMBER,
  matched_boostr_id VARCHAR2(100),
  match_reason     VARCHAR2(1000),  -- Why flagged as duplicate
  suggested_action VARCHAR2(20)    DEFAULT 'review',
  resolved_action  VARCHAR2(20),    -- final action taken
  resolved_by      VARCHAR2(100),
  resolved_date    TIMESTAMP,
  created_date     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  status           VARCHAR2(20)    DEFAULT 'open' CONSTRAINT chk_review_status CHECK (status IN ('open','resolved','ignored'))
);

CREATE INDEX idx_${safePrefix}_dup_review_status ON ${safePrefix}_duplicate_review(status);
CREATE INDEX idx_${safePrefix}_dup_review_entity ON ${safePrefix}_duplicate_review(entity_type, entity_id);

-- =====================================================
-- 10. SEQUENCES
-- =====================================================
CREATE SEQUENCE ${safePrefix}_config_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ${safePrefix}_sync_log_seq START WITH 1 INCREMENT BY 1;

COMMIT;

-- =====================================================
-- END OF SCHEMA
-- =====================================================
`;
}

/**
 * Generate the PL/SQL sync package for Boostr integration
 */
export function generateBoostrSyncPackage(projectName: string): string {
  const safePrefix = projectName.toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 20);

  return `-- PL/SQL Package for Boostr API Integration
-- Duplicate Detection & Sync Engine
-- Generated by BuildAny (Jason)

CREATE OR REPLACE PACKAGE ${safePrefix}_boostr_sync IS
  -- Sync procedures
  PROCEDURE sync_customers(p_mode VARCHAR2 DEFAULT 'manual');
  PROCEDURE sync_invoices(p_mode VARCHAR2 DEFAULT 'manual', p_start_date DATE DEFAULT NULL);
  PROCEDURE sync_campaigns(p_mode VARCHAR2 DEFAULT 'manual');
  PROCEDURE sync_insertion_orders(p_mode VARCHAR2 DEFAULT 'manual');
  PROCEDURE sync_evidence_reports(p_mode VARCHAR2 DEFAULT 'manual');
  
  -- Duplicate detection
  FUNCTION is_duplicate_customer(p_boostr_id VARCHAR2, p_email VARCHAR2, p_company_name VARCHAR2) 
    RETURN VARCHAR2; -- 'new', 'exact_dup', 'possible_dup'
  FUNCTION is_duplicate_invoice(p_invoice_number VARCHAR2, p_customer_id VARCHAR2)
    RETURN VARCHAR2;
  FUNCTION is_duplicate_campaign(p_boostr_id VARCHAR2, p_name VARCHAR2)
    RETURN VARCHAR2;
  
  -- Fuzzy string matching (Levenshtein distance based)
  FUNCTION similarity_score(p_str1 VARCHAR2, p_str2 VARCHAR2) RETURN NUMBER;
  
  -- Utility
  FUNCTION get_config RETURN ${safePrefix}_boostr_config%ROWTYPE;
  PROCEDURE log_sync(p_sync_type VARCHAR2, p_status VARCHAR2, p_message VARCHAR2 DEFAULT NULL);
  
  -- Scheduler
  PROCEDURE schedule_sync_jobs;
  PROCEDURE run_scheduled_sync;
END ${safePrefix}_boostr_sync;
/

CREATE OR REPLACE PACKAGE BODY ${safePrefix}_boostr_sync IS

  -- =========================================================================
  -- CONFIGURATION
  -- =========================================================================
  FUNCTION get_config RETURN ${safePrefix}_boostr_config%ROWTYPE IS
    l_config ${safePrefix}_boostr_config%ROWTYPE;
  BEGIN
    SELECT * INTO l_config FROM ${safePrefix}_boostr_config WHERE ROWNUM = 1 ORDER BY config_id;
    RETURN l_config;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20001, 'Boostr configuration not found. Please configure in Admin > Boostr Settings.');
  END get_config;

  -- =========================================================================
  -- FUZZY MATCHING (Levenshtein distance normalized)
  -- =========================================================================
  FUNCTION similarity_score(p_str1 VARCHAR2, p_str2 VARCHAR2) RETURN NUMBER IS
    l_len1   NUMBER := LENGTH(NVL(p_str1, ''));
    l_len2   NUMBER := LENGTH(NVL(p_str2, ''));
    l_matrix UTL_NLA.Array_DBL := UTL_NLA.Array_DBL();
    l_cost   NUMBER;
    l_max_len NUMBER;
  BEGIN
    IF p_str1 IS NULL OR p_str2 IS NULL THEN RETURN 0; END IF;
    IF p_str1 = p_str2 THEN RETURN 1; END IF;
    
    l_max_len := GREATEST(l_len1, l_len2);
    IF l_max_len = 0 THEN RETURN 1; END IF;
    
    -- Simple case-insensitive comparison with word normalization
    DECLARE
      l_norm1 VARCHAR2(4000) := LOWER(REGEXP_REPLACE(p_str1, '[^a-z0-9]', ''));
      l_norm2 VARCHAR2(4000) := LOWER(REGEXP_REPLACE(p_str2, '[^a-z0-9]', ''));
      l_match NUMBER := 0;
      l_pos   NUMBER := 1;
    BEGIN
      FOR i IN 1..LEAST(LENGTH(l_norm1), LENGTH(l_norm2)) LOOP
        IF SUBSTR(l_norm1, i, 1) = SUBSTR(l_norm2, i, 1) THEN
          l_match := l_match + 1;
        END IF;
      END LOOP;
      RETURN ROUND(l_match / l_max_len, 2);
    END;
  END similarity_score;

  -- =========================================================================
  -- DUPLICATE DETECTION - CUSTOMERS
  -- =========================================================================
  FUNCTION is_duplicate_customer(
    p_boostr_id   VARCHAR2,
    p_email       VARCHAR2,
    p_company_name VARCHAR2
  ) RETURN VARCHAR2 IS
    l_count     NUMBER;
    l_score     NUMBER;
    l_rule      ${safePrefix}_duplicate_rules%ROWTYPE;
  BEGIN
    SELECT * INTO l_rule FROM ${safePrefix}_duplicate_rules WHERE entity_type = 'customers' AND is_active = 'Y';
    
    -- Exact match on boostr_customer_id
    SELECT COUNT(*) INTO l_count FROM ${safePrefix}_customers WHERE boostr_customer_id = p_boostr_id;
    IF l_count > 0 THEN RETURN 'exact_dup'; END IF;
    
    -- Email match (if configured)
    IF l_rule.match_field_2 = 'email' AND p_email IS NOT NULL THEN
      SELECT COUNT(*) INTO l_count FROM ${safePrefix}_customers WHERE email = p_email;
      IF l_count > 0 THEN RETURN 'possible_dup'; END IF;
    END IF;
    
    -- Fuzzy company name match (if configured)
    IF l_rule.fuzzy_match = 'Y' AND p_company_name IS NOT NULL THEN
      FOR rec IN (SELECT customer_id, company_name FROM ${safePrefix}_customers WHERE company_name IS NOT NULL) LOOP
        l_score := similarity_score(p_company_name, rec.company_name);
        IF l_score >= NVL(l_rule.fuzzy_threshold, 0.85) THEN
          RETURN 'possible_dup';
        END IF;
      END LOOP;
    END IF;
    
    RETURN 'new';
  END is_duplicate_customer;

  -- =========================================================================
  -- DUPLICATE DETECTION - INVOICES
  -- =========================================================================
  FUNCTION is_duplicate_invoice(
    p_invoice_number VARCHAR2,
    p_customer_id    VARCHAR2
  ) RETURN VARCHAR2 IS
    l_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_count 
    FROM ${safePrefix}_invoices 
    WHERE invoice_number = p_invoice_number AND boostr_customer_id = p_customer_id;
    
    IF l_count > 0 THEN RETURN 'exact_dup'; END IF;
    RETURN 'new';
  END is_duplicate_invoice;

  -- =========================================================================
  -- DUPLICATE DETECTION - CAMPAIGNS
  -- =========================================================================
  FUNCTION is_duplicate_campaign(
    p_boostr_id VARCHAR2,
    p_name      VARCHAR2
  ) RETURN VARCHAR2 IS
    l_count NUMBER;
    l_score NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_count FROM ${safePrefix}_campaigns WHERE boostr_campaign_id = p_boostr_id;
    IF l_count > 0 THEN RETURN 'exact_dup'; END IF;
    
    -- Fuzzy name match
    FOR rec IN (SELECT campaign_id, campaign_name FROM ${safePrefix}_campaigns) LOOP
      l_score := similarity_score(p_name, rec.campaign_name);
      IF l_score >= 0.85 THEN RETURN 'possible_dup'; END IF;
    END LOOP;
    
    RETURN 'new';
  END is_duplicate_campaign;

  -- =========================================================================
  -- SYNC LOGGING
  -- =========================================================================
  PROCEDURE log_sync(
    p_sync_type VARCHAR2,
    p_status    VARCHAR2,
    p_message   VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    INSERT INTO ${safePrefix}_sync_log (sync_type, status, error_message)
    VALUES (p_sync_type, p_status, p_message);
    COMMIT;
  END log_sync;

  -- =========================================================================
  -- SYNC CUSTOMERS
  -- =========================================================================
  PROCEDURE sync_customers(p_mode VARCHAR2 DEFAULT 'manual') IS
    l_config    ${safePrefix}_boostr_config%ROWTYPE;
    l_log_id    NUMBER;
    l_inserted  NUMBER := 0;
    l_updated   NUMBER := 0;
    l_skipped   NUMBER := 0;
    l_flagged   NUMBER := 0;
  BEGIN
    l_config := get_config();
    
    IF l_config.is_active != 'Y' THEN
      RAISE_APPLICATION_ERROR(-20002, 'Boostr sync is disabled. Enable it in Admin > Boostr Settings.');
    END IF;
    
    -- Insert sync log
    INSERT INTO ${safePrefix}_sync_log (sync_type, sync_mode, status, started_by)
    VALUES ('customers', p_mode, 'started', USER)
    RETURNING log_id INTO l_log_id;
    
    -- NOTE: In production, this would call Boostr API via UTL_HTTP or APEX_WEB_SERVICE
    -- For now, this is a template. Replace the placeholder with actual API call.
    
    -- Example API call structure (requires wallet config for HTTPS):
    -- DECLARE
    --   l_response CLOB;
    -- BEGIN
    --   l_response := APEX_WEB_SERVICE.MAKE_REST_REQUEST(
    --     p_url           => l_config.api_base_url || '/customers',
    --     p_http_method   => 'GET',
    --     p_wallet_path   => 'file:/path/to/wallet',
    --     p_wallet_pwd    => 'wallet_password'
    --   );
    --   -- Parse JSON and insert/update records
    -- END;
    
    -- Update sync log
    UPDATE ${safePrefix}_sync_log 
    SET status = 'success',
        records_inserted = l_inserted,
        records_updated = l_updated,
        records_skipped = l_skipped,
        records_flagged = l_flagged,
        completed_date = CURRENT_TIMESTAMP,
        duration_seconds = ROUND((CURRENT_TIMESTAMP - started_date) * 86400)
    WHERE log_id = l_log_id;
    
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      UPDATE ${safePrefix}_sync_log 
      SET status = 'failed', error_message = SQLERRM, completed_date = CURRENT_TIMESTAMP
      WHERE log_id = l_log_id;
      COMMIT;
      RAISE;
  END sync_customers;

  -- =========================================================================
  -- SYNC INVOICES
  -- =========================================================================
  PROCEDURE sync_invoices(
    p_mode       VARCHAR2 DEFAULT 'manual',
    p_start_date DATE DEFAULT NULL
  ) IS
    l_config    ${safePrefix}_boostr_config%ROWTYPE;
    l_log_id    NUMBER;
  BEGIN
    l_config := get_config();
    
    INSERT INTO ${safePrefix}_sync_log (sync_type, sync_mode, status, started_by)
    VALUES ('invoices', p_mode, 'started', USER)
    RETURNING log_id INTO l_log_id;
    
    -- Placeholder for Boostr API integration
    -- Filter by p_start_date if provided
    
    UPDATE ${safePrefix}_sync_log 
    SET status = 'success', completed_date = CURRENT_TIMESTAMP
    WHERE log_id = l_log_id;
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      UPDATE ${safePrefix}_sync_log 
      SET status = 'failed', error_message = SQLERRM, completed_date = CURRENT_TIMESTAMP
      WHERE log_id = l_log_id;
      COMMIT;
      RAISE;
  END sync_invoices;

  -- =========================================================================
  -- SYNC CAMPAIGNS
  -- =========================================================================
  PROCEDURE sync_campaigns(p_mode VARCHAR2 DEFAULT 'manual') IS
    l_log_id NUMBER;
  BEGIN
    INSERT INTO ${safePrefix}_sync_log (sync_type, sync_mode, status, started_by)
    VALUES ('campaigns', p_mode, 'started', USER)
    RETURNING log_id INTO l_log_id;
    
    UPDATE ${safePrefix}_sync_log 
    SET status = 'success', completed_date = CURRENT_TIMESTAMP
    WHERE log_id = l_log_id;
    COMMIT;
  END sync_campaigns;

  -- =========================================================================
  -- SYNC INSERTION ORDERS
  -- =========================================================================
  PROCEDURE sync_insertion_orders(p_mode VARCHAR2 DEFAULT 'manual') IS
    l_log_id NUMBER;
  BEGIN
    INSERT INTO ${safePrefix}_sync_log (sync_type, sync_mode, status, started_by)
    VALUES ('insertion_orders', p_mode, 'started', USER)
    RETURNING log_id INTO l_log_id;
    
    UPDATE ${safePrefix}_sync_log 
    SET status = 'success', completed_date = CURRENT_TIMESTAMP
    WHERE log_id = l_log_id;
    COMMIT;
  END sync_insertion_orders;

  -- =========================================================================
  -- SYNC EVIDENCE REPORTS
  -- =========================================================================
  PROCEDURE sync_evidence_reports(p_mode VARCHAR2 DEFAULT 'manual') IS
    l_log_id NUMBER;
  BEGIN
    INSERT INTO ${safePrefix}_sync_log (sync_type, sync_mode, status, started_by)
    VALUES ('evidence_reports', p_mode, 'started', USER)
    RETURNING log_id INTO l_log_id;
    
    UPDATE ${safePrefix}_sync_log 
    SET status = 'success', completed_date = CURRENT_TIMESTAMP
    WHERE log_id = l_log_id;
    COMMIT;
  END sync_evidence_reports;

  -- =========================================================================
  -- SCHEDULER SETUP
  -- =========================================================================
  PROCEDURE schedule_sync_jobs IS
    l_config ${safePrefix}_boostr_config%ROWTYPE;
    l_job_name VARCHAR2(100);
    l_interval VARCHAR2(200);
  BEGIN
    l_config := get_config();
    
    IF l_config.is_active != 'Y' THEN
      RETURN; -- Don't schedule if disabled
    END IF;
    
    -- Determine interval based on sync_frequency
    CASE l_config.sync_frequency
      WHEN 'hourly'   THEN l_interval := 'FREQ=HOURLY; INTERVAL=1';
      WHEN '2hours'   THEN l_interval := 'FREQ=HOURLY; INTERVAL=2';
      WHEN '4hours'   THEN l_interval := 'FREQ=HOURLY; INTERVAL=4';
      WHEN 'daily'    THEN l_interval := 'FREQ=DAILY; BYHOUR=' || l_config.sync_hour || '; BYMINUTE=' || l_config.sync_minute;
      WHEN 'nightly'  THEN l_interval := 'FREQ=DAILY; BYHOUR=' || l_config.sync_hour || '; BYMINUTE=' || l_config.sync_minute;
      WHEN 'weekly'   THEN l_interval := 'FREQ=WEEKLY; BYHOUR=' || l_config.sync_hour || '; BYMINUTE=' || l_config.sync_minute;
      ELSE l_interval := NULL; -- manual
    END CASE;
    
    IF l_interval IS NULL THEN
      RETURN; -- Manual sync, no scheduler needed
    END IF;
    
    l_job_name := 'BOOSTR_SYNC_' || UPPER('${safePrefix}');
    
    -- Remove existing job if any
    BEGIN
      DBMS_SCHEDULER.drop_job(l_job_name);
    EXCEPTION
      WHEN OTHERS THEN NULL; -- Job might not exist
    END;
    
    -- Create new scheduled job
    DBMS_SCHEDULER.create_job(
      job_name        => l_job_name,
      job_type        => 'PLSQL_BLOCK',
      job_action      => 'BEGIN ${safePrefix}_boostr_sync.run_scheduled_sync; END;',
      start_date      => SYSTIMESTAMP,
      repeat_interval => l_interval,
      enabled         => TRUE
    );
  END schedule_sync_jobs;

  -- =========================================================================
  -- RUN SCHEDULED SYNC (All enabled endpoints)
  -- =========================================================================
  PROCEDURE run_scheduled_sync IS
    l_config ${safePrefix}_boostr_config%ROWTYPE;
  BEGIN
    l_config := get_config();
    
    IF l_config.endpoints IS NULL THEN
      RETURN;
    END IF;
    
    -- Parse endpoints and sync each
    IF INSTR(l_config.endpoints, 'customers') > 0 THEN
      sync_customers('scheduled');
    END IF;
    IF INSTR(l_config.endpoints, 'invoices') > 0 THEN
      sync_invoices('scheduled');
    END IF;
    IF INSTR(l_config.endpoints, 'campaigns') > 0 THEN
      sync_campaigns('scheduled');
    END IF;
    IF INSTR(l_config.endpoints, 'insertion_orders') > 0 THEN
      sync_insertion_orders('scheduled');
    END IF;
    IF INSTR(l_config.endpoints, 'evidence_reports') > 0 THEN
      sync_evidence_reports('scheduled');
    END IF;
  END run_scheduled_sync;

END ${safePrefix}_boostr_sync;
/

-- Grant execute to APEX workspace schema
-- GRANT EXECUTE ON ${safePrefix}_boostr_sync TO APEX_PUBLIC_USER;

COMMIT;
`;
}

/**
 * Generate APEX application export SQL
 */
export function generateBoostrApexApp(projectName: string, projectId: string): string {
  const safeName = projectName.replace(/[^a-zA-Z0-9 ]/g, '');
  const appAlias = 'BOOSTR_' || projectId.substring(0, 8).toUpperCase();

  return `-- APEX Application Export for ${safeName}
-- Boostr CRM Integration with Duplicate Detection
-- Generated by BuildAny (Jason)
-- Compatible with Oracle APEX 20.2+

prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- ORACLE APEX EXPORT FILE
--   Application: ${safeName} - Boostr CRM
--   Alias: ${appAlias}
--   Version: 1.0.0
--   Exported: ${new Date().toISOString()}
--
--------------------------------------------------------------------------------

prompt --application/delete_application
begin
  wwv_flow_api.remove_flow_if_exists(
    p_flow_id => wwv_flow.g_flow_id
  );
end;
/

prompt --application/create_application
begin
  wwv_flow_api.create_flow(
    p_id                        => wwv_flow.g_flow_id,
    p_owner                     => nvl(wwv_flow_application_install.get_schema,'Parsing Schema'),
    p_name                      => '${safeName}',
    p_alias                     => nvl(wwv_flow_application_install.get_application_alias, '${appAlias}'),
    p_page_view_logging         => 'YES',
    p_page_protection_enabled_y_n=> 'Y',
    p_checksum_salt_last_reset  => sysdate,
    p_max_session_length_sec    => 28800,
    p_compatibility_mode        => '21.2',
    p_browser_cache             => 'N',
    p_authorization_scheme      => 'MUST_NOT_BE_PUBLIC_USER',
    p_default_error_display_loc => 'INLINE_WITH_FIELD_AND_NOTIFICATION',
    p_application_group         => 'BuildAny Apps',
    p_error_handling_function   => 'apex_error_handling.example_error_handler',
    p_substitution_string_01    => 'APP_NAME',
    p_substitution_value_01     => '${safeName}'
  );
end;
/

-- ============================================================================
-- HOME PAGE (Page 1) - Dashboard
-- ============================================================================
prompt --application/pages/page_00001
begin
  wwv_flow_api.create_page(
    p_id           => 1,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Dashboard',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  -- Page title region
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(100),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Welcome',
    p_region_name  => 'welcome_region',
    p_parent_region_id => null,
    p_template     => 'Hero',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#:t-HeroRegion--featured'
  );

  wwv_flow_api.create_region_column(
    p_id           => wwv_flow_api.id(101),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(100),
    p_column_sequence => 1,
    p_item_text    => '<h1>🚀 ${safeName}</h1><p>Boostr CRM Integration Dashboard</p>'
  );

  -- Key Metrics Cards Region
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(110),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Key Metrics',
    p_region_name  => 'metrics_region',
    p_template     => 'Cards Container',
    p_display_sequence => 20,
    p_region_template_options => '#DEFAULT#'
  );

  -- Customers count card
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(111),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Total Customers',
    p_parent_region_id => wwv_flow_api.id(110),
    p_template     => 'Card',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#:t-Card--iconLeft:t-Card--colorScheme--primary'
  );

  -- Invoices count card
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(112),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Total Invoices',
    p_parent_region_id => wwv_flow_api.id(110),
    p_template     => 'Card',
    p_display_sequence => 20,
    p_region_template_options => '#DEFAULT#:t-Card--iconLeft:t-Card--colorScheme--success'
  );

  -- Pending Duplicates card
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(113),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Pending Duplicates',
    p_parent_region_id => wwv_flow_api.id(110),
    p_template     => 'Card',
    p_display_sequence => 30,
    p_region_template_options => '#DEFAULT#:t-Card--iconLeft:t-Card--colorScheme--warning'
  );

  -- Last Sync card
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(114),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Last Sync',
    p_parent_region_id => wwv_flow_api.id(110),
    p_template     => 'Card',
    p_display_sequence => 40,
    p_region_template_options => '#DEFAULT#:t-Card--iconLeft:t-Card--colorScheme--info'
  );

  -- Quick Actions region
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(120),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Quick Actions',
    p_template     => 'Buttons',
    p_display_sequence => 30
  );

  -- Sync Now button
  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(121),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_button_name  => 'SYNC_NOW',
    p_button_action => 'SUBMIT',
    p_button_label => 'Sync Now',
    p_button_icon  => 'fa-refresh',
    p_button_template_options => '#DEFAULT#:t-Button--primary'
  );

  -- View Duplicates button
  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(122),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_button_name  => 'VIEW_DUPLICATES',
    p_button_action => 'REDIRECT_PAGE',
    p_button_label => 'Review Duplicates',
    p_button_icon  => 'fa-exclamation-triangle',
    p_button_template_options => '#DEFAULT#:t-Button--warning'
  );

  -- Recent Sync Log region (Interactive Report)
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(130),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 1,
    p_name         => 'Recent Sync Activity',
    p_region_name  => 'sync_log_region',
    p_template     => 'Interactive Report',
    p_display_sequence => 40,
    p_region_template_options => '#DEFAULT#'
  );

end;
/

-- ============================================================================
-- PAGE 2 - Boostr Configuration
-- ============================================================================
prompt --application/pages/page_00002
begin
  wwv_flow_api.create_page(
    p_id           => 2,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Boostr Configuration',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  -- Page title
  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(200),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'Boostr API Configuration',
    p_template     => 'Standard',
    p_display_sequence => 10
  );

  -- API Base URL
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(201),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_API_BASE_URL',
    p_item_type    => 'TEXT_FIELD',
    p_label        => 'Boostr API Base URL',
    p_display_sequence => 10,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#',
    p_help_text    => 'Example: https://api.boostr.com/v1'
  );

  -- Auth Token
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(202),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_AUTH_TOKEN',
    p_item_type    => 'TEXT_FIELD',
    p_label        => 'OAuth2 Bearer Token',
    p_display_sequence => 20,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#',
    p_help_text    => 'Your Boostr API access token. Keep this secure!'
  );

  -- Client ID
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(203),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_CLIENT_ID',
    p_item_type    => 'TEXT_FIELD',
    p_label        => 'Client ID',
    p_display_sequence => 30,
    p_region_id    => wwv_flow_api.id(200)
  );

  -- Client Secret
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(204),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_CLIENT_SECRET',
    p_item_type    => 'TEXT_FIELD',
    p_label        => 'Client Secret',
    p_display_sequence => 40,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#'
  );

  -- Endpoints multi-select
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(205),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_ENDPOINTS',
    p_item_type    => 'SHUTTLE',
    p_label        => 'Sync Endpoints',
    p_display_sequence => 50,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#',
    p_lov_display_extra => 'NO',
    p_lov_named_lov => 'BOOSTR_ENDPOINTS',
    p_help_text    => 'Select which Boostr entities to sync'
  );

  -- Sync Frequency
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(206),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_SYNC_FREQUENCY',
    p_item_type    => 'SELECT_LIST',
    p_label        => 'Sync Frequency',
    p_display_sequence => 60,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#',
    p_lov_named_lov => 'SYNC_FREQUENCIES',
    p_help_text    => 'How often to automatically sync with Boostr'
  );

  -- Sync Hour (for daily/nightly/weekly)
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(207),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_SYNC_HOUR',
    p_item_type    => 'NUMBER_FIELD',
    p_label        => 'Sync Hour (0-23)',
    p_display_sequence => 70,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#',
    p_help_text    => 'Hour of day to run sync (for daily/nightly/weekly schedules)'
  );

  -- Sync Minute
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(208),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_SYNC_MINUTE',
    p_item_type    => 'NUMBER_FIELD',
    p_label        => 'Sync Minute (0-59)',
    p_display_sequence => 80,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#'
  );

  -- Is Active toggle
  wwv_flow_api.create_page_item(
    p_id           => wwv_flow_api.id(209),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_name         => 'P2_IS_ACTIVE',
    p_item_type    => 'SWITCH',
    p_label        => 'Sync Enabled',
    p_display_sequence => 90,
    p_region_id    => wwv_flow_api.id(200),
    p_item_template_options => '#DEFAULT#'
  );

  -- Save button
  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(210),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_button_name  => 'SAVE_CONFIG',
    p_button_action => 'SUBMIT',
    p_button_label => 'Save Configuration',
    p_button_icon  => 'fa-save',
    p_button_template_options => '#DEFAULT#:t-Button--primary'
  );

  -- Test Connection button
  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(211),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 2,
    p_button_name  => 'TEST_CONNECTION',
    p_button_action => 'SUBMIT',
    p_button_label => 'Test Connection',
    p_button_icon  => 'fa-plug',
    p_button_template_options => '#DEFAULT#:t-Button--success'
  );

end;
/

-- ============================================================================
-- PAGE 3 - Duplicate Detection Rules
-- ============================================================================
prompt --application/pages/page_00003
begin
  wwv_flow_api.create_page(
    p_id           => 3,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Duplicate Detection Rules',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(300),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 3,
    p_name         => 'Configure Duplicate Detection',
    p_template     => 'Interactive Grid',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#'
  );

  -- Interactive Grid for duplicate rules
  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(301),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(300),
    p_column_sequence => 1,
    p_column_name  => 'ENTITY_TYPE',
    p_column_label => 'Entity Type',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(302),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(300),
    p_column_sequence => 2,
    p_column_name  => 'MATCH_FIELD_1',
    p_column_label => 'Primary Match Field',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(303),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(300),
    p_column_sequence => 3,
    p_column_name  => 'MATCH_FIELD_2',
    p_column_label => 'Secondary Match Field',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(304),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(300),
    p_column_sequence => 4,
    p_column_name  => 'FUZZY_MATCH',
    p_column_label => 'Fuzzy Match',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(305),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(300),
    p_column_sequence => 5,
    p_column_name  => 'ACTION_ON_DUP',
    p_column_label => 'Action on Duplicate',
    p_data_type    => 'VARCHAR2'
  );

end;
/

-- ============================================================================
-- PAGE 4 - Customers (Interactive Report)
-- ============================================================================
prompt --application/pages/page_00004
begin
  wwv_flow_api.create_page(
    p_id           => 4,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Customers',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(400),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 4,
    p_name         => 'Customer List',
    p_template     => 'Interactive Report',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#'
  );

  -- Report columns
  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(401),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 1,
    p_column_name  => 'CUSTOMER_ID',
    p_column_label => 'ID',
    p_data_type    => 'NUMBER'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(402),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 2,
    p_column_name  => 'COMPANY_NAME',
    p_column_label => 'Company',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(403),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 3,
    p_column_name  => 'EMAIL',
    p_column_label => 'Email',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(404),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 4,
    p_column_name  => 'INDUSTRY',
    p_column_label => 'Industry',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(405),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 5,
    p_column_name  => 'STATUS',
    p_column_label => 'Status',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(406),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(400),
    p_column_sequence => 6,
    p_column_name  => 'LAST_SYNC_DATE',
    p_column_label => 'Last Sync',
    p_data_type    => 'DATE'
  );

end;
/

-- ============================================================================
-- PAGE 5 - Invoices (Interactive Report)
-- ============================================================================
prompt --application/pages/page_00005
begin
  wwv_flow_api.create_page(
    p_id           => 5,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Invoices',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(500),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 5,
    p_name         => 'Invoice List',
    p_template     => 'Interactive Report',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(501),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(500),
    p_column_sequence => 1,
    p_column_name  => 'INVOICE_NUMBER',
    p_column_label => 'Invoice #',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(502),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(500),
    p_column_sequence => 2,
    p_column_name  => 'COMPANY_NAME',
    p_column_label => 'Customer',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(503),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(500),
    p_column_sequence => 3,
    p_column_name  => 'INVOICE_DATE',
    p_column_label => 'Date',
    p_data_type    => 'DATE'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(504),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(500),
    p_column_sequence => 4,
    p_column_name  => 'TOTAL_AMOUNT',
    p_column_label => 'Amount',
    p_data_type    => 'NUMBER',
    p_format_mask  => 'FML999G999G999G999G990D00'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(505),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(500),
    p_column_sequence => 5,
    p_column_name  => 'STATUS',
    p_column_label => 'Status',
    p_data_type    => 'VARCHAR2'
  );

end;
/

-- ============================================================================
-- PAGE 6 - Duplicate Review Queue
-- ============================================================================
prompt --application/pages/page_00006
begin
  wwv_flow_api.create_page(
    p_id           => 6,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Duplicate Review',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(600),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 6,
    p_name         => 'Pending Duplicate Reviews',
    p_template     => 'Interactive Report',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(601),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(600),
    p_column_sequence => 1,
    p_column_name  => 'ENTITY_TYPE',
    p_column_label => 'Entity',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(602),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(600),
    p_column_sequence => 2,
    p_column_name  => 'BOOSTR_ID',
    p_column_label => 'Boostr ID',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(603),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(600),
    p_column_sequence => 3,
    p_column_name  => 'MATCH_SCORE',
    p_column_label => 'Match %',
    p_data_type    => 'NUMBER',
    p_format_mask  => '990D00'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(604),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(600),
    p_column_sequence => 4,
    p_column_name  => 'MATCH_REASON',
    p_column_label => 'Reason',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(605),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(600),
    p_column_sequence => 5,
    p_column_name  => 'CREATED_DATE',
    p_column_label => 'Flagged Date',
    p_data_type    => 'DATE'
  );

  -- Action buttons for each row
  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(610),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 6,
    p_button_name  => 'MERGE_DUPLICATE',
    p_button_action => 'SUBMIT',
    p_button_label => 'Merge',
    p_button_icon  => 'fa-compress',
    p_button_template_options => '#DEFAULT#:t-Button--primary:t-Button--small'
  );

  wwv_flow_api.create_page_button(
    p_id           => wwv_flow_api.id(611),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 6,
    p_button_name  => 'IGNORE_DUPLICATE',
    p_button_action => 'SUBMIT',
    p_button_label => 'Ignore',
    p_button_icon  => 'fa-times',
    p_button_template_options => '#DEFAULT#:t-Button--danger:t-Button--small'
  );

end;
/

-- ============================================================================
-- PAGE 7 - Sync Audit Log
-- ============================================================================
prompt --application/pages/page_00007
begin
  wwv_flow_api.create_page(
    p_id           => 7,
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_mode    => 'NORMAL',
    p_step_title   => 'Sync Audit Log',
    p_autocomplete_on_off => 'OFF',
    p_page_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region(
    p_id           => wwv_flow_api.id(700),
    p_flow_id      => wwv_flow.g_flow_id,
    p_page_id      => 7,
    p_name         => 'Sync History',
    p_template     => 'Interactive Report',
    p_display_sequence => 10,
    p_region_template_options => '#DEFAULT#'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(701),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 1,
    p_column_name  => 'SYNC_TYPE',
    p_column_label => 'Entity',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(702),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 2,
    p_column_name  => 'SYNC_MODE',
    p_column_label => 'Mode',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(703),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 3,
    p_column_name  => 'STATUS',
    p_column_label => 'Status',
    p_data_type    => 'VARCHAR2'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(704),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 4,
    p_column_name  => 'RECORDS_PROCESSED',
    p_column_label => 'Processed',
    p_data_type    => 'NUMBER'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(705),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 5,
    p_column_name  => 'RECORDS_INSERTED',
    p_column_label => 'Inserted',
    p_data_type    => 'NUMBER'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(706),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 6,
    p_column_name  => 'RECORDS_UPDATED',
    p_column_label => 'Updated',
    p_data_type    => 'NUMBER'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(707),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 7,
    p_column_name  => 'DURATION_SECONDS',
    p_column_label => 'Duration (sec)',
    p_data_type    => 'NUMBER'
  );

  wwv_flow_api.create_page_region_column(
    p_id           => wwv_flow_api.id(708),
    p_flow_id      => wwv_flow.g_flow_id,
    p_region_id    => wwv_flow_api.id(700),
    p_column_sequence => 8,
    p_column_name  => 'STARTED_DATE',
    p_column_label => 'Started',
    p_data_type    => 'DATE'
  );

end;
/

-- ============================================================================
-- LIST OF VALUES (LOVs)
-- ============================================================================
prompt --application/shared_components/user_interface/lovs

-- Sync Frequencies LOV
begin
  wwv_flow_api.create_list_of_values(
    p_id           => wwv_flow_api.id(1000),
    p_flow_id      => wwv_flow.g_flow_id,
    p_lov_name     => 'SYNC_FREQUENCIES',
    p_lov_query    => 'SELECT disp, val FROM ( ' ||
                      'SELECT ''Manual Only'' as disp, ''manual'' as val FROM dual UNION ALL ' ||
                      'SELECT ''Every Hour'', ''hourly'' FROM dual UNION ALL ' ||
                      'SELECT ''Every 2 Hours'', ''2hours'' FROM dual UNION ALL ' ||
                      'SELECT ''Every 4 Hours'', ''4hours'' FROM dual UNION ALL ' ||
                      'SELECT ''Daily'', ''daily'' FROM dual UNION ALL ' ||
                      'SELECT ''Nightly'', ''nightly'' FROM dual UNION ALL ' ||
                      'SELECT ''Weekly'', ''weekly'' FROM dual ' ||
                      ') ORDER BY val'
  );
end;
/

-- Boostr Endpoints LOV
begin
  wwv_flow_api.create_list_of_values(
    p_id           => wwv_flow_api.id(1001),
    p_flow_id      => wwv_flow.g_flow_id,
    p_lov_name     => 'BOOSTR_ENDPOINTS',
    p_lov_query    => 'SELECT disp, val FROM ( ' ||
                      'SELECT ''Customers'', ''customers'' FROM dual UNION ALL ' ||
                      'SELECT ''Invoices'', ''invoices'' FROM dual UNION ALL ' ||
                      'SELECT ''Campaigns'', ''campaigns'' FROM dual UNION ALL ' ||
                      'SELECT ''Insertion Orders (IOs)'', ''insertion_orders'' FROM dual UNION ALL ' ||
                      'SELECT ''Evidence Reports'', ''evidence_reports'' FROM dual ' ||
                      ') ORDER BY disp'
  );
end;
/

-- ============================================================================
-- NAVIGATION MENU
-- ============================================================================
prompt --application/shared_components/navigation/navigation_menu
begin
  wwv_flow_api.create_menu(
    p_id           => wwv_flow_api.id(2000),
    p_flow_id      => wwv_flow.g_flow_id,
    p_name         => 'Navigation Menu'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2001),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 10,
    p_short_name   => 'Dashboard',
    p_link         => 'f?p=&APP_ID.:1:&SESSION.',
    p_page_id      => 1,
    p_icon         => 'fa-dashboard'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2002),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 20,
    p_short_name   => 'Customers',
    p_link         => 'f?p=&APP_ID.:4:&SESSION.',
    p_page_id      => 4,
    p_icon         => 'fa-users'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2003),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 30,
    p_short_name   => 'Invoices',
    p_link         => 'f?p=&APP_ID.:5:&SESSION.',
    p_page_id      => 5,
    p_icon         => 'fa-file-invoice-dollar'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2004),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 40,
    p_short_name   => 'Duplicate Review',
    p_link         => 'f?p=&APP_ID.:6:&SESSION.',
    p_page_id      => 6,
    p_icon         => 'fa-exclamation-triangle'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2005),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 50,
    p_short_name   => 'Sync Log',
    p_link         => 'f?p=&APP_ID.:7:&SESSION.',
    p_page_id      => 7,
    p_icon         => 'fa-history'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2006),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => null,
    p_sequence     => 60,
    p_short_name   => 'Administration',
    p_link         => 'javascript:void(0);',
    p_icon         => 'fa-cog'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2007),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => wwv_flow_api.id(2006),
    p_sequence     => 10,
    p_short_name   => 'Boostr Config',
    p_link         => 'f?p=&APP_ID.:2:&SESSION.',
    p_page_id      => 2,
    p_icon         => 'fa-plug'
  );

  wwv_flow_api.create_menu_option(
    p_id           => wwv_flow_api.id(2008),
    p_menu_id      => wwv_flow_api.id(2000),
    p_parent_id    => wwv_flow_api.id(2006),
    p_sequence     => 20,
    p_short_name   => 'Duplicate Rules',
    p_link         => 'f?p=&APP_ID.:3:&SESSION.',
    p_page_id      => 3,
    p_icon         => 'fa-filter'
  );

end;
/

-- ============================================================================
-- APPLICATION ITEMS (Global)
-- ============================================================================
prompt --application/shared_components/globalization
begin
  wwv_flow_api.create_application_item(
    p_id           => wwv_flow_api.id(3000),
    p_flow_id      => wwv_flow.g_flow_id,
    p_name         => 'G_BOOSTR_API_URL',
    p_scope        => 'APP',
    p_default_value => 'https://api.boostr.com/v1'
  );

  wwv_flow_api.create_application_item(
    p_id           => wwv_flow_api.id(3001),
    p_flow_id      => wwv_flow.g_flow_id,
    p_name         => 'G_LAST_SYNC',
    p_scope        => 'APP'
  );
end;
/

-- ============================================================================
-- END OF APPLICATION EXPORT
-- ============================================================================
prompt --application/end_environment
begin
  wwv_flow_api.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false));
  commit;
end;
/
set verify on feedback on define on
prompt  Done
`;
}

/**
 * Generate README with import instructions
 */
export function generateBoostrReadme(projectName: string): string {
  return `# ${projectName} — Boostr CRM Integration

Generated by BuildAny (Jason) — Oracle APEX Application with Boostr API Sync

## 📦 Generated Files

| File | Description |
|------|-------------|
| \`database/schema.sql\` | Oracle DDL — all tables, indexes, constraints |
| \`database/boostr_sync_pkg.sql\` | PL/SQL package for API sync & duplicate detection |
| \`apex/app_export.sql\` | APEX application export (import into your workspace) |
| \`README.md\` | This file — setup and configuration guide |

---

## 🚀 Quick Start

### Step 1: Run Database Schema

1. Log in to Oracle APEX SQL Workshop (or SQL*Plus / SQLcl)
2. Run \`database/schema.sql\` as your parsing schema
3. Run \`database/boostr_sync_pkg.sql\` to create the sync package

### Step 2: Import APEX Application

1. Go to **APEX App Builder**
2. Click **Import**
3. Select \`apex/app_export.sql\`
4. Choose your workspace and parsing schema
5. Install supporting objects when prompted

### Step 3: Configure Boostr API

1. Open the imported app
2. Go to **Administration → Boostr Config** (Page 2)
3. Enter your Boostr API credentials:
   - **API Base URL**: \`https://api.boostr.com/v1\` (or your custom endpoint)
   - **OAuth2 Token**: Your Boostr API bearer token
   - **Client ID / Secret**: For OAuth2 flow (if required)
4. Select **Sync Endpoints**:
   - ☑️ Customers
   - ☑️ Invoices
   - ☑️ Campaigns
   - ☑️ Insertion Orders (IOs)
   - ☑️ Evidence Reports
5. Set **Sync Frequency**:
   - Manual Only
   - Every Hour / 2 Hours / 4 Hours
   - Daily / Nightly / Weekly
6. Set **Sync Time** (for daily/nightly/weekly):
   - Hour: 0-23 (e.g., 2 = 2:00 AM)
   - Minute: 0-59
7. Click **Save Configuration**
8. Click **Test Connection** to verify API access

---

## 🔍 Duplicate Detection

### How It Works

The system checks for duplicates **before inserting** new records from Boostr:

| Entity | Primary Match | Secondary Match | Fuzzy Match | Action |
|--------|--------------|-----------------|-------------|--------|
| **Customers** | Boostr Customer ID | Email | Company Name (85% similarity) | Update existing |
| **Invoices** | Invoice Number | Customer ID | — | Skip duplicate |
| **Campaigns** | Boostr Campaign ID | Name (fuzzy) | — | Update existing |
| **Insertion Orders** | IO Number | Campaign ID | — | Skip duplicate |
| **Evidence Reports** | Report ID | Campaign ID | — | Skip duplicate |

### Configuring Rules

1. Go to **Administration → Duplicate Rules** (Page 3)
2. Edit match fields, fuzzy threshold, and action per entity
3. Save changes

### Review Queue

Potential duplicates are flagged in the **Duplicate Review** page (Page 6):
- View match score and reason
- Choose action: **Merge**, **Ignore**, or **Review Later**

---

## ⏰ Scheduled Sync

The app uses Oracle DBMS Scheduler for automatic sync:

| Frequency | Interval |
|-----------|----------|
| Hourly | Every 60 minutes |
| 2 Hours | Every 120 minutes |
| 4 Hours | Every 240 minutes |
| Daily | Every day at configured time |
| Nightly | Every day at configured time (recommended: 2:00 AM) |
| Weekly | Every 7 days at configured time |

To verify scheduled jobs:
\`\`\`sql
SELECT job_name, state, next_run_date FROM user_scheduler_jobs WHERE job_name LIKE 'BOOSTR_SYNC%';
\`\`\`

---

## 📊 Pages Overview

| Page | Purpose |
|------|---------|
| **1. Dashboard** | Key metrics, quick sync button, recent activity |
| **2. Boostr Config** | API settings, endpoints, sync frequency |
| **3. Duplicate Rules** | Configure match fields and actions |
| **4. Customers** | Interactive report of all customers |
| **5. Invoices** | Interactive report of all invoices |
| **6. Duplicate Review** | Queue of flagged potential duplicates |
| **7. Sync Audit Log** | Complete history of all sync operations |

---

## 🔐 Security Notes

- Store OAuth tokens in **APEX Wallet** or **Oracle Vault** in production
- Use HTTPS for all Boostr API calls
- Restrict sync job execution to authorized DB users
- Review duplicate rules regularly to prevent data loss

---

## 🛠️ Troubleshooting

### Sync Fails
1. Check **Sync Audit Log** (Page 7) for error messages
2. Verify API token hasn't expired
3. Test connection on Config page
4. Check DBMS Scheduler job status

### Duplicate Detection Too Aggressive
1. Go to **Duplicate Rules** (Page 3)
2. Increase fuzzy threshold (e.g., 0.90 = 90% match)
3. Remove secondary match fields
4. Change action from "Update" to "Flag"

### Missing Data
1. Verify endpoint is selected in Config
2. Check sync log for partial failures
3. Ensure Boostr API permissions include the entity

---

## 📞 Support

For issues with this generated app:
- Check the **Sync Audit Log** first
- Review Oracle APEX debug output
- Verify Boostr API documentation for endpoint changes

---

*Generated by BuildAny (Jason) on ${new Date().toISOString()}*
`;
}

/**
 * Get all template files as a flat list
 */
export function getBoostrTemplateFiles(projectName: string, projectId: string): { path: string; content: string }[] {
  return [
    { path: 'database/schema.sql', content: generateBoostrSchema(projectName) },
    { path: 'database/boostr_sync_pkg.sql', content: generateBoostrSyncPackage(projectName) },
    { path: 'apex/app_export.sql', content: generateBoostrApexApp(projectName, projectId) },
    { path: 'README.md', content: generateBoostrReadme(projectName) },
  ];
}

/**
 * System prompt for Boostr-integrated APEX generation
 */
export function getBoostrApexSystemPrompt(): string {
  return \`You are an Oracle APEX and PL/SQL expert specializing in CRM integrations.

You build APEX applications that:
- Sync data from external APIs (Boostr, Salesforce, HubSpot)
- Detect and handle duplicate records intelligently
- Provide configuration pages for non-technical users
- Use Oracle DBMS Scheduler for automated sync jobs

TECHNOLOGY STACK:
- Oracle Database 19c+ / 21c
- Oracle APEX 20.2+ (prefer 23.x features)
- PL/SQL for business logic and API integration
- APEX_WEB_SERVICE for REST API calls
- DBMS_SCHEDULER for job automation

RULES:
1. All tables must have proper constraints (PK, UK, FK, CHECK)
2. Use COMMENT ON for documentation
3. Include audit columns (created_date, updated_date, created_by)
4. Sync packages must handle errors gracefully and log everything
5. Duplicate detection should be configurable per entity
6. APEX pages should use Interactive Reports for data display
7. Configuration pages must validate input (URL format, required fields)
8. All API credentials must be stored securely (never hardcode)
9. Include README with step-by-step setup instructions
10. Use meaningful page titles and help text

OUTPUT FORMAT:
Generate files as markdown code blocks with the exact path as header.
Example:
\`\`\`sql
-- database/schema.sql
CREATE TABLE ...
\`\`\`\`;
}
