import { db } from "./db";
import { projects, conversations, projectFiles } from "./db/schema";
import { eq } from "drizzle-orm";
import { randomUUID } from "crypto";
import { generateMobileTemplate, getMobileFileList, getMobileSystemPrompt } from "./mobile-templates";

interface LLMProvider {
  name: string;
  generate: (prompt: string, systemPrompt: string) => Promise<string>;
}

// DeepSeek V3 - Fast, cheap, good for simple apps
const deepseekProvider: LLMProvider = {
  name: "deepseek-v3",
  generate: async (prompt, systemPrompt) => {
    const res = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY || ""}`,
      },
      body: JSON.stringify({
        model: "deepseek-chat",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt },
        ],
        temperature: 0.7,
      }),
    });
    const data = await res.json();
    return data.choices?.[0]?.message?.content || "";
  },
};

// Kimi K2.6 - Long context, great for complex apps
const kimiProvider: LLMProvider = {
  name: "kimi-k2-6",
  generate: async (prompt, systemPrompt) => {
    const res = await fetch("https://api.moonshot.cn/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.KIMI_API_KEY || ""}`,
      },
      body: JSON.stringify({
        model: "kimi-k2-6",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt },
        ],
        temperature: 0.7,
      }),
    });
    const data = await res.json();
    return data.choices?.[0]?.message?.content || "";
  },
};

// GPT-4o - Reliable, good for UI/UX
const openaiProvider: LLMProvider = {
  name: "gpt-4o",
  generate: async (prompt, systemPrompt) => {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_API_KEY || ""}`,
      },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt },
        ],
        temperature: 0.7,
      }),
    });
    const data = await res.json();
    return data.choices?.[0]?.message?.content || "";
  },
};

// Router: Pick best model based on complexity
function routeModel(prompt: string): LLMProvider {
  const complexity = estimateComplexity(prompt);
  
  // Check which API keys are available
  const hasDeepseek = !!process.env.DEEPSEEK_API_KEY;
  const hasKimi = !!process.env.KIMI_API_KEY;
  const hasOpenAI = !!process.env.OPENAI_API_KEY;
  
  if (complexity > 7 && hasKimi) return kimiProvider;
  if (complexity > 5 && hasOpenAI) return openaiProvider;
  if (hasDeepseek) return deepseekProvider;
  if (hasOpenAI) return openaiProvider;
  if (hasKimi) return kimiProvider;
  
  // Fallback to mock if no keys
  return {
    name: "mock",
    generate: async () => mockGenerate(prompt),
  };
}

function estimateComplexity(prompt: string): number {
  let score = 3; // base
  if (prompt.includes("mobile") || prompt.includes("app")) score += 2;
  if (prompt.includes("database") || prompt.includes("auth")) score += 2;
  if (prompt.includes("payment") || prompt.includes("stripe")) score += 2;
  if (prompt.includes("real-time") || prompt.includes("websocket")) score += 1;
  if (prompt.length > 200) score += 1;
  return Math.min(score, 10);
}

function mockGenerate(prompt: string): string {
  // Return a structured code response for demo
  return JSON.stringify({
    files: [
      {
        path: "src/app/page.tsx",
        content: `export default function Home() {\n  return (\n    <div className="p-8">\n      <h1 className="text-2xl font-bold">${prompt.slice(0, 30)}...</h1>\n      <p>Generated by BuildAny AI</p>\n    </div>\n  );\n}`,
        language: "tsx",
      },
      {
        path: "src/app/layout.tsx",
        content: `export default function RootLayout({ children }) {\n  return <html><body>{children}</body></html>;\n}`,
        language: "tsx",
      },
    ],
    description: `Generated app based on: ${prompt}`,
  });
}

export async function generateCode(projectId: string, prompt: string, type: string) {
  const isMobile = type === "mobile" || type === "dashboard";
  
  let systemPrompt = `You are an expert full-stack developer. Generate a complete ${isMobile ? "React Native" : "Next.js"} application based on the user's description.

Return a JSON object with:
- files: array of {path, content, language}
- description: string describing what was built
- dependencies: array of npm packages needed

Guidelines:
- Use TypeScript
- Use Tailwind CSS for styling
- Include proper error handling
- Add loading states
- Make it production-ready
${isMobile ? getMobileSystemPrompt() : ""}`;

  const model = routeModel(prompt);
  
  try {
    // Save that we're using this model
    await db.insert(conversations).values({
      id: randomUUID(),
      projectId,
      role: "system",
      content: `Using model: ${model.name} for ${type} app`,
      model: model.name,
    });

    let parsed;
    
    if (isMobile) {
      // Generate mobile template first
      const template = generateMobileTemplate(`BuildAny-${projectId.slice(0, 8)}`);
      const templateFiles = getMobileFileList(template);
      
      // Get AI-generated app-specific screens
      const appResponse = await model.generate(prompt, systemPrompt);
      
      try {
        parsed = JSON.parse(appResponse);
      } catch {
        parsed = {
          files: [{
            path: "src/app/(tabs)/index.tsx",
            content: appResponse,
            language: "tsx",
          }],
          description: prompt,
          dependencies: [],
        };
      }
      
      // Merge template files with AI-generated files
      parsed.files = [
        ...templateFiles,
        ...(parsed.files || []),
      ];
    } else {
      // Web app generation
      const response = await model.generate(prompt, systemPrompt);
      
      try {
        parsed = JSON.parse(response);
      } catch {
        parsed = {
          files: [{
            path: "src/app/page.tsx",
            content: response,
            language: "tsx",
          }],
          description: prompt,
          dependencies: [],
        };
      }
    }
    
    // Deduplicate files by path (AI files override template files)
    const fileMap = new Map();
    for (const file of parsed.files) {
      fileMap.set(file.path, file);
    }
    parsed.files = Array.from(fileMap.values());

    // Save generated files
    for (const file of parsed.files || []) {
      await db.insert(projectFiles).values({
        id: randomUUID(),
        projectId,
        path: file.path,
        content: file.content,
        language: file.language || "tsx",
        isGenerated: true,
      });
    }

    // Save AI response
    await db.insert(conversations).values({
      id: randomUUID(),
      projectId,
      role: "assistant",
      content: parsed.description || "Code generated successfully",
      model: model.name,
    });

    // Update project status
    await db.update(projects)
      .set({ status: "ready" })
      .where(eq(projects.id, projectId));

    return parsed;
  } catch (error) {
    console.error("Generation error:", error);
    
    await db.insert(conversations).values({
      id: randomUUID(),
      projectId,
      role: "system",
      content: `Error: ${error instanceof Error ? error.message : "Unknown error"}`,
    });

    await db.update(projects)
      .set({ status: "error" })
      .where(eq(projects.id, projectId));

    throw error;
  }
}
