import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  avatarUrl: text("avatar_url"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  plan: text("plan").default("free"),
  creditsUsed: integer("credits_used").default(0),
  creditsTotal: integer("credits_total").default(100),
});

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  type: text("type").notNull().default("web"),
  status: text("status").default("draft"),
  githubRepo: text("github_repo"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const projectFiles = sqliteTable("project_files", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  path: text("path").notNull(),
  content: text("content"),
  language: text("language"),
  isGenerated: integer("is_generated", { mode: "boolean" }).default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const conversations = sqliteTable("conversations", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  role: text("role").notNull(),
  content: text("content").notNull(),
  model: text("model"),
  tokensUsed: integer("tokens_used"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const templates = sqliteTable("templates", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  type: text("type").notNull().default("web"),
  files: text("files"),
  authorId: text("author_id"),
  downloads: integer("downloads").default(0),
  rating: integer("rating").default(0),
  isPublic: integer("is_public", { mode: "boolean" }).default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const deployments = sqliteTable("deployments", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  provider: text("provider").notNull(),
  url: text("url"),
  status: text("status").default("pending"),
  buildLog: text("build_log"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const userMemory = sqliteTable("user_memory", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  memoryType: text("memory_type").notNull(),
  content: text("content").notNull(),
  context: text("context"),
  confidence: integer("confidence").default(50),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const projectMemory = sqliteTable("project_memory", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  memoryType: text("memory_type").notNull(),
  content: text("content").notNull(),
  context: text("context"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const platformPatterns = sqliteTable("platform_patterns", {
  id: text("id").primaryKey(),
  patternType: text("pattern_type").notNull(),
  trigger: text("trigger").notNull(),
  suggestion: text("suggestion").notNull(),
  frequency: integer("frequency").default(1),
  successRate: integer("success_rate"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const wikiPages = sqliteTable("wiki_pages", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  pageType: text("page_type").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  autoGenerated: integer("auto_generated", { mode: "boolean" }).default(true),
  lastUpdatedAt: integer("last_updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const wikiRelationships = sqliteTable("wiki_relationships", {
  id: text("id").primaryKey(),
  sourcePageId: text("source_page_id").notNull(),
  targetPageId: text("target_page_id").notNull(),
  relationshipType: text("relationship_type").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const adrs = sqliteTable("adrs", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull(),
  title: text("title").notNull(),
  context: text("context").notNull(),
  decision: text("decision").notNull(),
  consequences: text("consequences").notNull(),
  status: text("status").default("proposed"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
