#!/bin/bash
# =============================================================================
# ONE-FILE INSTALLER: Complete Proposal & RFP System
# This single script contains ALL code, templates, and logic.
# Run with: bash all-in-one-installer.sh
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# =============================================================================
# CONFIGURATION
# =============================================================================
SKILLS_DIR="${HOME}/.openclaw/skills"
WORK_DIR="/tmp/proposal-system-setup"

# =============================================================================
# STEP 1: CHECK PREREQUISITES
# =============================================================================
log "Step 1: Checking prerequisites..."

if ! command -v python3 &> /dev/null; then
    warn "Python 3 not found. Installing..."
    if command -v apt-get &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y python3
    elif command -v yum &> /dev/null; then
        sudo yum install -y python3
    elif command -v brew &> /dev/null; then
        brew install python3
    else
        error "Cannot install Python automatically. Please install Python 3.8+ manually."
        exit 1
    fi
fi

PYTHON_VERSION=$(python3 --version 2>&1 | grep -oP '\d+\.\d+' | head -1)
log "Python version: $PYTHON_VERSION"

# =============================================================================
# STEP 2: INSTALL OPENCLAW (if not present)
# =============================================================================
log "Step 2: Checking OpenClaw..."

if ! command -v openclaw &> /dev/null; then
    warn "OpenClaw not found. Installing..."
    curl -sSL https://install.openclaw.ai | bash
    # Add to PATH if needed
    export PATH="$HOME/.openclaw/bin:$PATH"
fi

OPENCLAW_VERSION=$(openclaw --version 2>&1 | head -1)
success "OpenClaw: $OPENCLAW_VERSION"

# =============================================================================
# STEP 3: CREATE WORKING DIRECTORY
# =============================================================================
log "Step 3: Creating working directory..."
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# =============================================================================
# STEP 4: EMBED ALL PYTHON CODE
# =============================================================================
log "Step 4: Preparing generator engine..."

# Write the universal Mustache generator
cat > generator.py << 'PYEOF'
#!/usr/bin/env python3
"""Universal Mustache Template Engine — Generated by all-in-one-installer."""
import json, argparse, os, re
from datetime import datetime

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def resolve_placeholder(key, data):
    """Resolve {{key}} from nested dict using dot notation."""
    keys = key.strip().split('.')
    current = data
    for k in keys:
        if isinstance(current, dict) and k in current:
            current = current[k]
        else:
            return None
    return current

def render_template(template, data, index=None):
    """Render Mustache template with data."""
    result = template
    
    # Process loops: {{#list}}...{{/list}}
    loop_pattern = r'\{\{#(\w+(?:\.\w+)*)\}\}(.*?)\{\{/\1\}\}'
    
    def process_loop(match):
        list_key = match.group(1)
        inner_template = match.group(2)
        items = resolve_placeholder(list_key, data)
        if not items or not isinstance(items, list):
            return ''
        rendered = []
        for idx, item in enumerate(items):
            item_data = data.copy()
            item_data['this'] = item if not isinstance(item, dict) else {**data, **item}
            item_data['index'] = idx
            rendered.append(render_template(inner_template, item_data, idx))
        return '\n'.join(rendered)
    
    while re.search(loop_pattern, result, re.DOTALL):
        result = re.sub(loop_pattern, process_loop, result, count=1, flags=re.DOTALL)
    
    # Replace simple placeholders
    def replace_var(match):
        var = match.group(1).strip()
        if var == 'this':
            val = data.get('this')
        elif var == 'index':
            val = index
        else:
            val = resolve_placeholder(var, data)
        return str(val) if val is not None else ''
    
    result = re.sub(r'\{\{(\w+(?:\.\w+)*|this|index)\}\}', replace_var, result)
    return result

def main():
    parser = argparse.ArgumentParser(description='Generate document from intake JSON')
    parser.add_argument('--intake', required=True, help='Path to intake JSON file')
    parser.add_argument('--template', required=True, help='Path to template Markdown file')
    parser.add_argument('--output', required=True, help='Path for output Markdown file')
    args = parser.parse_args()
    
    data = load_json(args.intake)
    data['meta'] = data.get('meta', {})
    data['meta']['generated_date'] = datetime.now().strftime('%Y-%m-%d')
    
    with open(args.template, 'r', encoding='utf-8') as f:
        template = f.read()
    
    output = render_template(template, data)
    
    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(output)
    
    print(f"✅ Document generated: {args.output}")
    print(f"📄 Lines: {len(output.splitlines())}")

if __name__ == '__main__':
    main()
PYEOF

chmod +x generator.py
success "Generator engine ready"

# =============================================================================
# STEP 5: CREATE PROPOSAL TEMPLATE
# =============================================================================
log "Step 5: Creating proposal template..."

mkdir -p "$SKILLS_DIR"
mkdir -p "$SKILLS_DIR/proposal-craft"
mkdir -p "$SKILLS_DIR/proposal-craft/assets"
mkdir -p "$SKILLS_DIR/proposal-craft/scripts"
mkdir -p "$SKILLS_DIR/proposal-craft/references"

cat > "$SKILLS_DIR/proposal-craft/assets/proposal-template.md" << 'TMPEOF'
# Proposal for {{client.name}}

**Prepared by:** {{vendor.company_name}}  
**Date:** {{meta.generated_date}}  
**Valid for:** {{terms.validity_days}} days

---

## Executive Summary

{{vendor.company_name}} is pleased to submit this proposal for {{client.name}}'s {{solution.overview}}.

{{client.name}} is a {{client.industry}} organization seeking to {{needs.objectives.0}}. This proposal outlines our recommended approach, timeline, and investment.

---

## About {{vendor.company_name}}

{{vendor.description}}

Founded in {{vendor.founded_year}} and headquartered in {{vendor.headquarters}}, we are a team of {{vendor.employees}} professionals dedicated to delivering exceptional IT consulting services.

{{#vendor.partnerships}}
**Strategic Partnerships:** {{this}}
{{/vendor.partnerships}}

---

## Understanding Your Needs

### Challenges
{{#needs.challenges}}
- {{this}}
{{/needs.challenges}}

### Objectives
{{#needs.objectives}}
- {{this}}
{{/needs.objectives}}

---

## Proposed Solution

{{solution.overview}}

### Scope of Work
{{#solution.scope}}
- {{this}}
{{/solution.scope}}

### Key Deliverables
{{#solution.deliverables}}
- {{this}}
{{/solution.deliverables}}

---

## Methodology: {{methodology.name}}

{{#methodology.phases}}
### Phase {{index}}: {{name}} ({{duration_weeks}} weeks)
{{#activities}}
- {{this}}
{{/activities}}

**Deliverables:**
{{#deliverables}}
- {{this}}
{{/deliverables}}

{{/methodology.phases}}

---

## Project Timeline

{{#timeline.phases}}
- **{{name}}:** {{duration_weeks}} weeks
{{/timeline.phases}}

**Total Duration: {{timeline.total_duration_weeks}} weeks**

---

## Investment Summary

| Component | Amount ({{pricing.currency}}) |
|---|---|
{{#pricing.components}}
| {{component}} | {{amount}} |
{{/pricing.components}}
| **Total Investment** | **{{pricing.total}}** |

### Payment Milestones
{{#pricing.payment_milestones}}
- **{{percentage}}%** — {{description}}: {{amount}} {{pricing.currency}}
{{/pricing.payment_milestones}}

---

## Our Team

{{#team}}
### {{role}} ({{count}} FTE @ {{allocation_percent}}%)
{{#responsibilities}}
- {{this}}
{{/responsibilities}}

{{/team}}

---

## Relevant Experience

{{#case_studies}}
### {{title}}
**Industry:** {{industry}} | **Type:** {{project_type}} | **Duration:** {{duration_weeks}} weeks | **Value:** {{currency}}{{value}}

{{description}}

**Key Outcomes:**
{{#outcomes}}
- {{this}}
{{/outcomes}}

**Technologies:** {{#technologies}}{{this}}, {{/technologies}}

---

{{/case_studies}}

## Terms and Conditions

- **Proposal Validity:** {{terms.validity_days}} days from date of issue
- **Warranty Period:** {{terms.warranty_period}}
- **Governing Law:** {{terms.governing_law}}
- **Payment Terms:** {{terms.payment_terms}}

---

## Next Steps

{{#next_steps}}
{{index}}. {{this}}
{{/next_steps}}

---

*This proposal was generated on {{meta.generated_date}} and is confidential.*
TMPEOF

# Copy generator to proposal-craft
cp generator.py "$SKILLS_DIR/proposal-craft/scripts/generator.py"
chmod +x "$SKILLS_DIR/proposal-craft/scripts/generator.py"

success "Proposal template created"

# =============================================================================
# STEP 6: CREATE RFP RESPONSE TEMPLATE
# =============================================================================
log "Step 6: Creating RFP response template..."

mkdir -p "$SKILLS_DIR/rfp-respond"
mkdir -p "$SKILLS_DIR/rfp-respond/assets"
mkdir -p "$SKILLS_DIR/rfp-respond/scripts"
mkdir -p "$SKILLS_DIR/rfp-respond/references"

cat > "$SKILLS_DIR/rfp-respond/assets/rfp-response-template.md" << 'RFPEOF'
# RFP Response: {{rfp.title}}

**RFP Reference:** {{rfp.ref}}  
**Submitted by:** {{vendor.company_name}}  
**Date:** {{meta.generated_date}}  
**Response Valid Until:** {{rfp.submission_deadline}}

---

## 1. Executive Summary

{{vendor.company_name}} is pleased to respond to {{client.name}}'s Request for Proposal for {{rfp.title}}.

{{response_strategy.executive_summary}}

### Why {{vendor.company_name}}

{{#response_strategy.differentiators}}
- {{this}}
{{/response_strategy.differentiators}}

---

## 2. Company Qualifications

{{vendor.description}}

### Certifications
{{#vendor.certifications}}
- {{this}}
{{/vendor.certifications}}

### Partnerships
{{#vendor.partnerships}}
- {{this}}
{{/vendor.partnerships}}

---

## 3. Understanding of Requirements

{{#requirements}}
### {{category}} Requirements

{{#items}}
**{{id}} — {{description}}**

- **Priority:** {{priority}}
- **Our Approach:** {{response}}
- **Compliance:** {{compliance_status}}

{{/items}}

{{/requirements}}

---

## 4. Technical Approach

{{technical_approach.description}}

### Architecture Overview
{{#technical_approach.architecture}}
- {{this}}
{{/technical_approach.architecture}}

### Security Measures
{{#technical_approach.security}}
- {{this}}
{{/technical_approach.security}}

### Implementation Plan
{{#technical_approach.implementation}}
- {{this}}
{{/technical_approach.implementation}}

---

## 5. Project Plan

### Timeline
{{#project_plan.milestones}}
- **{{date}}:** {{description}} ({{duration_weeks}} weeks)
{{/project_plan.milestones}}

### Team Structure
{{#team}}
- **{{role}}:** {{count}} FTE ({{allocation_percent}}%)
{{/team}}

---

## 6. Pricing

{{#pricing.components}}
| {{component}} | {{amount}} {{currency}} |
{{/pricing.components}}
| **Total** | **{{pricing.total}} {{pricing.currency}}** |

---

## 7. Risk Management

{{#risks}}
### {{title}} ({{severity}})
- **Mitigation:** {{mitigation}}
- **Contingency:** {{contingency}}

{{/risks}}

---

## 8. References

{{#references}}
### {{client_name}} — {{project_title}}
- **Contact:** {{contact_name}}, {{contact_title}}
- **Phone:** {{contact_phone}}
- **Email:** {{contact_email}}
- **Project Value:** {{currency}}{{project_value}}

{{/references}}

---

## 9. Clarification Questions

{{#clarification_questions}}
{{index}}. {{question}}
{{/clarification_questions}}

---

*This response is confidential and proprietary to {{vendor.company_name}}.*
RFPEOF

# Copy generator to rfp-respond
cp generator.py "$SKILLS_DIR/rfp-respond/scripts/generator.py"
chmod +x "$SKILLS_DIR/rfp-respond/scripts/generator.py"

success "RFP response template created"

# =============================================================================
# STEP 7: CREATE KNOWLEDGE BASE
# =============================================================================
log "Step 7: Creating knowledge base..."

mkdir -p "$SKILLS_DIR/proposal-kb"
mkdir -p "$SKILLS_DIR/proposal-kb/assets"
mkdir -p "$SKILLS_DIR/proposal-kb/scripts"
mkdir -p "$SKILLS_DIR/proposal-kb/references"

cat > "$SKILLS_DIR/proposal-kb/assets/kb.json" << 'KBEOF'
{
  "vendor": {
    "company_name": "[YOUR COMPANY NAME]",
    "description": "[Describe your IT consulting company — specialties, experience, value proposition]",
    "founded_year": 2010,
    "headquarters": "[City, Country]",
    "employees": 50,
    "website": "https://[yourcompany].com",
    "partnerships": [
      "Microsoft Gold Partner",
      "AWS Advanced Consulting Partner",
      "[Add your partnerships]"
    ],
    "certifications": [
      "ISO 27001",
      "SOC 2 Type II",
      "[Add your certifications]"
    ]
  },
  "case_studies": [
    {
      "title": "[Project Name]",
      "industry": "manufacturing",
      "project_type": "cloud_migration",
      "duration_weeks": 24,
      "team_size": 8,
      "value": 500000,
      "currency": "USD",
      "description": "[Describe what you did for this client — the problem, your solution, and approach]",
      "outcomes": [
        "[Specific measurable result — e.g., '40% cost reduction']",
        "[Another outcome — e.g., '99.9% uptime achieved']",
        "[Third outcome]"
      ],
      "technologies": [
        "Azure",
        "Kubernetes",
        "[Add technologies used]"
      ],
      "anonymized_client": "[e.g., 'Global manufacturer with $2B revenue']"
    }
  ],
  "pricing": {
    "currency": "USD",
    "daily_rates": {
      "engagement_manager": 1800,
      "solution_architect": 1600,
      "senior_consultant": 1400,
      "consultant": 1100,
      "analyst": 800
    }
  },
  "team_templates": {
    "cloud_migration": {
      "roles": [
        {"role": "Engagement Manager", "count": 1, "allocation_percent": 50, "responsibilities": ["Project oversight", "Stakeholder management"]},
        {"role": "Solution Architect", "count": 1, "allocation_percent": 100, "responsibilities": ["Architecture design", "Technical leadership"]},
        {"role": "Senior Consultant", "count": 2, "allocation_percent": 100, "responsibilities": ["Implementation", "Configuration"]},
        {"role": "Consultant", "count": 2, "allocation_percent": 100, "responsibilities": ["Development", "Testing"]},
        {"role": "Analyst", "count": 1, "allocation_percent": 100, "responsibilities": ["Data migration", "Reporting"]}
      ]
    }
  },
  "methodology": {
    "name": "Cloud Ascend",
    "phases": [
      {
        "name": "Discover",
        "duration_weeks": 4,
        "activities": ["Current state assessment", "Future state design", "Stakeholder interviews"],
        "deliverables": ["Assessment report", "Architecture blueprint"]
      },
      {
        "name": "Plan",
        "duration_weeks": 4,
        "activities": ["Migration planning", "Risk assessment", "Resource allocation"],
        "deliverables": ["Migration plan", "Risk register", "Project charter"]
      },
      {
        "name": "Execute",
        "duration_weeks": 12,
        "activities": ["Infrastructure setup", "Application migration", "Integration testing"],
        "deliverables": ["Migrated environment", "Test results", "Training materials"]
      },
      {
        "name": "Optimize",
        "duration_weeks": 4,
        "activities": ["Performance tuning", "Knowledge transfer", "Documentation"],
        "deliverables": ["Optimized system", "Operations guide", "Support transition"]
      }
    ]
  },
  "differentiators": {
    "manufacturing": [
      "Deep expertise in OT/IT convergence",
      "Proven track record with SAP integrations",
      "Understanding of regulatory compliance (FDA, ISO)"
    ]
  },
  "win_loss_log": []
}
KBEOF

success "Knowledge base created (CUSTOMIZE THIS!)"

# =============================================================================
# STEP 8: CREATE KB QUERY SCRIPT
# =============================================================================
log "Step 8: Creating KB query engine..."

cat > "$SKILLS_DIR/proposal-kb/scripts/query_kb.py" << 'QUERYEOF'
#!/usr/bin/env python3
"""Query Knowledge Base and generate draft intake JSON."""
import json, argparse

def load_kb(path):
    with open(path, 'r') as f:
        return json.load(f)

def filter_case_studies(case_studies, industry=None):
    if not industry:
        return case_studies[:2] if case_studies else []
    filtered = [cs for cs in case_studies if cs.get('industry') == industry]
    return filtered if filtered else case_studies[:2]

def get_team_template(templates, project_type):
    return templates.get(project_type, templates.get('cloud_migration', {"roles": []}))

def get_differentiators(differentiators, industry):
    return differentiators.get(industry, differentiators.get('general', []))

def calculate_pricing(rates, team_template, duration_weeks=24):
    total = 0
    for role in team_template.get('roles', []):
        rate = rates.get(role['role'].lower().replace(' ', '_'), 1000)
        count = role.get('count', 1)
        allocation = role.get('allocation_percent', 100) / 100
        working_days = duration_weeks * 5
        cost = rate * count * allocation * working_days
        total += cost
    return total

def build_draft(kb, industry, project_type, client_name):
    vendor = kb['vendor']
    case_studies = filter_case_studies(kb.get('case_studies', []), industry)
    team_template = get_team_template(kb.get('team_templates', {}), project_type)
    methodology = kb.get('methodology', {})
    rates = kb.get('pricing', {}).get('daily_rates', {})
    differentiators = get_differentiators(kb.get('differentiators', {}), industry)
    
    total_duration = sum(p.get('duration_weeks', 4) for p in methodology.get('phases', []))
    pricing_estimate = calculate_pricing(rates, team_template, total_duration)
    
    components = [
        {"component": "Professional Services", "amount": int(pricing_estimate)},
        {"component": "Software & Licenses", "amount": int(pricing_estimate * 0.2)},
        {"component": "Travel & Expenses", "amount": int(pricing_estimate * 0.05)}
    ]
    total = sum(c['amount'] for c in components)
    
    milestones = [
        {"percentage": 10, "description": "Project kickoff", "amount": int(total * 0.1)},
        {"percentage": 20, "description": "Design approval", "amount": int(total * 0.2)},
        {"percentage": 30, "description": "Go-live", "amount": int(total * 0.3)},
        {"percentage": 40, "description": "Final acceptance", "amount": int(total * 0.4)}
    ]
    
    draft = {
        "client": {
            "name": client_name,
            "industry": industry,
            "size_employees": 1000,
            "description": f"{client_name} is a {industry} organization seeking digital transformation."
        },
        "vendor": vendor,
        "needs": {
            "challenges": [
                "Legacy system limitations",
                "Scalability constraints", 
                "Compliance requirements"
            ],
            "objectives": [
                "Modernize infrastructure",
                "Improve operational efficiency",
                "Reduce total cost of ownership"
            ]
        },
        "solution": {
            "overview": f"Comprehensive {project_type.replace('_', ' ')} solution leveraging industry best practices and proven methodology.",
            "scope": [
                "Assessment and planning",
                "Architecture design",
                "Implementation and migration",
                "Training and knowledge transfer"
            ],
            "deliverables": [
                "Project documentation",
                "Trained staff",
                "Operational system",
                "Support documentation"
            ]
        },
        "methodology": methodology,
        "timeline": {
            "total_duration_weeks": total_duration,
            "phases": methodology.get('phases', [])
        },
        "pricing": {
            "currency": kb.get('pricing', {}).get('currency', 'USD'),
            "professional_services": int(pricing_estimate),
            "components": components,
            "total": total,
            "payment_milestones": milestones
        },
        "team": team_template.get('roles', []),
        "case_studies": case_studies,
        "terms": {
            "validity_days": 120,
            "warranty_period": "12 months",
            "governing_law": "State of [Your State]",
            "payment_terms": "Net 30 days from invoice date"
        },
        "next_steps": [
            "Schedule discovery workshop",
            "Finalize scope and timeline",
            "Execute master services agreement"
        ]
    }
    return draft

def main():
    parser = argparse.ArgumentParser(description='Query KB and generate draft intake')
    parser.add_argument('--kb', required=True, help='Path to kb.json')
    parser.add_argument('--industry', required=True)
    parser.add_argument('--project-type', required=True)
    parser.add_argument('--client', required=True)
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    
    kb = load_kb(args.kb)
    draft = build_draft(kb, args.industry, args.project_type, args.client)
    
    with open(args.output, 'w') as f:
        json.dump(draft, f, indent=2)
    
    print(f"✅ Draft intake generated: {args.output}")
    print(f"💰 Estimated value: ${draft['pricing']['total']:,} {draft['pricing']['currency']}")
    print(f"📊 Duration: {draft['timeline']['total_duration_weeks']} weeks")
    print(f"👥 Team: {len(draft['team'])} roles")

if __name__ == '__main__':
    main()
QUERYEOF

chmod +x "$SKILLS_DIR/proposal-kb/scripts/query_kb.py"

# =============================================================================
# STEP 9: CREATE KB UPDATE SCRIPT
# =============================================================================
log "Step 9: Creating KB maintenance tools..."

cat > "$SKILLS_DIR/proposal-kb/scripts/update_kb.py" << 'UPDATEEOF'
#!/usr/bin/env python3
"""Update Knowledge Base with new content."""
import json, argparse

def load_json(path):
    with open(path, 'r') as f:
        return json.load(f)

def save_json(data, path):
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)

def add_case_study(kb, case_study):
    kb.setdefault('case_studies', []).append(case_study)
    return kb

def add_win_loss(kb, record):
    kb.setdefault('win_loss_log', []).append(record)
    return kb

def update_pricing(kb, new_rates):
    kb.setdefault('pricing', {})['daily_rates'] = new_rates
    return kb

def update_vendor(kb, vendor_data):
    kb['vendor'].update(vendor_data)
    return kb

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--kb', required=True, help='Path to kb.json')
    parser.add_argument('--add-case-study', help='Path to case study JSON')
    parser.add_argument('--add-win-loss', help='Path to win/loss record JSON')
    parser.add_argument('--update-pricing', help='Path to pricing JSON')
    parser.add_argument('--update-vendor', help='Path to vendor JSON')
    parser.add_argument('--list', action='store_true', help='List KB contents')
    parser.add_argument('--section', help='Show specific section')
    args = parser.parse_args()
    
    kb = load_json(args.kb)
    
    if args.list:
        print("=== Knowledge Base Contents ===")
        print(f"Company: {kb['vendor']['company_name']}")
        print(f"Case Studies: {len(kb.get('case_studies', []))}")
        print(f"Win/Loss Records: {len(kb.get('win_loss_log', []))}")
        return
    
    if args.section:
        section = kb.get(args.section, "Not found")
        print(json.dumps(section, indent=2))
        return
    
    if args.add_case_study:
        cs = load_json(args.add_case_study)
        kb = add_case_study(kb, cs)
        print("✅ Case study added")
    
    if args.add_win_loss:
        wl = load_json(args.add_win_loss)
        kb = add_win_loss(kb, wl)
        print("✅ Win/loss record added")
    
    if args.update_pricing:
        rates = load_json(args.update_pricing)
        kb = update_pricing(kb, rates)
        print("✅ Pricing updated")
    
    if args.update_vendor:
        vendor = load_json(args.update_vendor)
        kb = update_vendor(kb, vendor)
        print("✅ Vendor profile updated")
    
    save_json(kb, args.kb)
    print(f"✅ KB saved: {args.kb}")

if __name__ == '__main__':
    main()
UPDATEEOF

chmod +x "$SKILLS_DIR/proposal-kb/scripts/update_kb.py"
success "KB maintenance tools created"

# =============================================================================
# STEP 10: WRITE SKILL DOCUMENTATION
# =============================================================================
log "Step 10: Writing SKILL.md files..."

cat > "$SKILLS_DIR/proposal-craft/SKILL.md" << 'SKILL1'
---
name: proposal-craft
description: Create vendor proposal templates and generate professional IT consulting proposals from structured intake data. Use when the user needs to (1) create a proposal template for pitching IT services to clients, (2) generate a vendor proposal document from client intake data, (3) produce outbound sales proposals for cloud migration, ERP implementation, managed services, or digital transformation engagements, (4) build a reusable proposal generation workflow. Triggers on phrases like "create proposal", "generate proposal", "proposal template", "vendor proposal", "pitch document", "client proposal", "service proposal", "IT proposal".
---

# Proposal Craft Skill

Generate professional IT consulting proposals from structured intake data.

## Quick Start

```bash
cd ~/.openclaw/skills/proposal-craft
python3 scripts/generator.py \
  --intake references/sample-intake.json \
  --template assets/proposal-template.md \
  --output proposal.md
```

## Workflow

1. **Query KB** (if using proposal-kb) to get draft intake
2. **Customize intake JSON** with client-specific details
3. **Run generator** to produce Markdown document
4. **Convert** to PDF/Word as needed

## Template Variables

- `{{client.name}}` — Client company name
- `{{vendor.company_name}}` — Your company name
- `{{solution.overview}}` — Solution description
- `{{pricing.total}}` — Total investment amount
- `{{#team}}...{{/team}}` — Team member loop
- `{{#case_studies}}...{{/case_studies}}` — Case study loop
SKILL1

cat > "$SKILLS_DIR/rfp-respond/SKILL.md" << 'SKILL2'
---
name: rfp-respond
description: Respond to client RFPs (Requests for Proposal) with structured vendor response documents. Use when the user needs to (1) create an RFP response template, (2) generate a compliant vendor response to a client-issued RFP, (3) extract requirements from RFP documents and produce bid responses, (4) prepare inbound proposal documents for procurement processes, (5) build an RFP response generation workflow. Triggers on phrases like "RFP response", "respond to RFP", "bid response", "RFP template", "proposal response", "vendor response", "answer RFP".
---

# RFP Respond Skill

Generate compliant RFP response documents from structured intake data.

## Quick Start

```bash
cd ~/.openclaw/skills/rfp-respond
python3 scripts/generator.py \
  --intake references/sample-intake.json \
  --template assets/rfp-response-template.md \
  --output response.md
```

## Workflow

1. **Extract requirements** from client RFP
2. **Build intake JSON** with response structure
3. **Run generator** to produce compliant response
4. **Review compliance** against RFP requirements
SKILL2

cat > "$SKILLS_DIR/proposal-kb/SKILL.md" << 'SKILL3'
---
name: proposal-kb
description: Maintain and query a reusable knowledge base for proposal and RFP response content. Use when the user needs to (1) store reusable proposal content (company profile, case studies, team templates, pricing, methodology), (2) retrieve relevant content for a new proposal or RFP response by industry/project type, (3) build a content library that feeds proposal-craft and rfp-respond skills, (4) auto-populate vendor sections, case studies, team templates, or pricing from past work. Triggers on phrases like "proposal knowledge base", "KB", "reusable content", "case studies", "proposal library", "proposal content", "company profile", "rate card", "methodology template", "team template", "pricing model", "win loss log".
---

# Proposal Knowledge Base Skill

Store, query, and maintain reusable proposal content.

## Quick Start

```bash
cd ~/.openclaw/skills/proposal-kb

# Generate draft intake
python3 scripts/query_kb.py \
  --kb assets/kb.json \
  --industry manufacturing \
  --project-type cloud_migration \
  --client "Acme Corp" \
  --output /tmp/draft.json

# Update KB with new case study
python3 scripts/update_kb.py \
  --kb assets/kb.json \
  --add-case-study new-project.json
```

## Maintenance Schedule

- After every win: Add case study
- After every loss: Log win/loss with lessons
- Quarterly: Review differentiators and rates
- Annually: Update vendor profile and certifications
SKILL3

success "SKILL.md files written"

# =============================================================================
# STEP 11: CREATE SAMPLE INTAKE FILES
# =============================================================================
log "Step 11: Creating sample intake files..."

cat > "$SKILLS_DIR/proposal-craft/references/sample-intake.json" << 'INTAKE1'
{
  "client": {
    "name": "Acme Corporation",
    "industry": "manufacturing",
    "size_employees": 1200,
    "description": "Leading manufacturer of industrial components"
  },
  "vendor": {
    "company_name": "[YOUR COMPANY]",
    "description": "[Your company description]",
    "founded_year": 2010,
    "headquarters": "[Your City]",
    "employees": 50,
    "partnerships": ["Microsoft Gold Partner"],
    "certifications": ["ISO 27001"]
  },
  "needs": {
    "challenges": ["Legacy ERP system", "Manual processes", "Data silos"],
    "objectives": ["Modernize infrastructure", "Improve efficiency", "Enable growth"]
  },
  "solution": {
    "overview": "Cloud-based ERP modernization with integrated analytics",
    "scope": ["Assessment", "Design", "Implementation", "Training"],
    "deliverables": ["New ERP system", "Training materials", "Documentation"]
  },
  "pricing": {
    "currency": "USD",
    "total": 750000,
    "components": [
      {"component": "Professional Services", "amount": 600000},
      {"component": "Software Licenses", "amount": 120000},
      {"component": "Travel", "amount": 30000}
    ],
    "payment_milestones": [
      {"percentage": 20, "description": "Kickoff", "amount": 150000},
      {"percentage": 30, "description": "Design", "amount": 225000},
      {"percentage": 30, "description": "Go-live", "amount": 225000},
      {"percentage": 20, "description": "Acceptance", "amount": 150000}
    ]
  },
  "team": [
    {"role": "Project Manager", "count": 1, "allocation_percent": 100, "responsibilities": ["Project oversight"]},
    {"role": "Solution Architect", "count": 1, "allocation_percent": 100, "responsibilities": ["Architecture"]}
  ],
  "case_studies": [
    {
      "title": "Previous Success",
      "industry": "manufacturing",
      "project_type": "erp",
      "duration_weeks": 20,
      "value": 500000,
      "currency": "USD",
      "description": "Previous ERP implementation",
      "outcomes": ["40% improvement"],
      "technologies": ["SAP", "Azure"]
    }
  ],
  "methodology": {
    "name": "Standard Delivery",
    "phases": [
      {"name": "Discover", "duration_weeks": 4, "activities": ["Assess"], "deliverables": ["Report"]}
    ]
  },
  "timeline": {
    "total_duration_weeks": 24,
    "phases": [{"name": "Phase 1", "duration_weeks": 4}]
  },
  "terms": {
    "validity_days": 120,
    "warranty_period": "12 months",
    "governing_law": "State",
    "payment_terms": "Net 30"
  },
  "next_steps": ["Schedule workshop", "Finalize agreement"]
}
INTAKE1

cat > "$SKILLS_DIR/rfp-respond/references/sample-intake.json" << 'INTAKE2'
{
  "rfp": {
    "title": "ERP Modernization RFP",
    "ref": "RFP-2024-001",
    "submission_deadline": "2024-12-31"
  },
  "client": {
    "name": "Acme Corporation"
  },
  "vendor": {
    "company_name": "[YOUR COMPANY]",
    "description": "[Your company description]",
    "certifications": ["ISO 27001"],
    "partnerships": ["Microsoft"]
  },
  "response_strategy": {
    "executive_summary": "Our team brings 10+ years of ERP modernization experience",
    "differentiators": ["Proven methodology", "Industry expertise", "Local presence"]
  },
  "requirements": [
    {
      "category": "Technical",
      "items": [
        {"id": "T-01", "description": "Cloud-native architecture", "priority": "Must", "response": "Azure-based", "compliance_status": "Compliant"}
      ]
    }
  ],
  "technical_approach": {
    "description": " phased migration approach",
    "architecture": ["Azure", "Microservices"],
    "security": ["Encryption", "MFA"],
    "implementation": ["Agile", "DevOps"]
  },
  "project_plan": {
    "milestones": [{"date": "2024-06", "description": "Kickoff", "duration_weeks": 4}]
  },
  "team": [
    {"role": "PM", "count": 1, "allocation_percent": 100}
  ],
  "pricing": {
    "currency": "USD",
    "total": 800000,
    "components": [{"component": "Services", "amount": 800000}]
  },
  "risks": [
    {"title": "Data migration", "severity": "Medium", "mitigation": "Phased approach", "contingency": "Rollback plan"}
  ],
  "references": [
    {"client_name": "Previous Client", "project_title": "ERP", "contact_name": "John", "contact_title": "CIO", "contact_phone": "555-0100", "contact_email": "john@example.com", "project_value": 500000, "currency": "USD"}
  ],
  "clarification_questions": [
    {"question": "What is the preferred cloud platform?"}
  ]
}
INTAKE2

success "Sample intakes created"

# =============================================================================
# STEP 12: PACKAGE SKILLS
# =============================================================================
log "Step 12: Packaging skills..."

# Try to package each skill
for skill in proposal-craft rfp-respond proposal-kb; do
    skill_path="$SKILLS_DIR/$skill"
    if [ -f "/usr/lib/node_modules/openclaw/skills/skill-creator/scripts/package_skill.py" ]; then
        python3 /usr/lib/node_modules/openclaw/skills/skill-creator/scripts/package_skill.py "$skill_path" 2>/dev/null || warn "$skill packaging had issues (non-critical)"
    else
        # Manual packaging: create .skill file (zip)
        cd "$SKILLS_DIR"
        zip -r "$skill.skill" "$skill" -x "*.pyc" -x "__pycache__/*" 2>/dev/null || true
        cd "$WORK_DIR"
    fi
done

success "Skills packaged"

# =============================================================================
# STEP 13: RESTART OPENCLAW
# =============================================================================
log "Step 13: Restarting OpenClaw..."

if command -v systemctl &> /dev/null && systemctl is-active --quiet openclaw 2>/dev/null; then
    sudo systemctl restart openclaw || openclaw gateway restart
else
    openclaw gateway restart 2>/dev/null || warn "Could not restart OpenClaw automatically. Please restart manually."
fi

success "OpenClaw restart attempted"

# =============================================================================
# STEP 14: VERIFICATION
# =============================================================================
log "Step 14: Running verification..."

cat > /tmp/verify-proposal-system.sh << 'VERIFY'
#!/bin/bash
set -e

echo "=========================================="
echo "PROPOSAL SYSTEM VERIFICATION"
echo "=========================================="

check_file() {
    if [ -f "$1" ]; then
        echo "✅ $2"
    else
        echo "❌ $2 MISSING: $1"
        exit 1
    fi
}

check_dir() {
    if [ -d "$1" ]; then
        echo "✅ $2"
    else
        echo "❌ $2 MISSING: $1"
        exit 1
    fi
}

SKILLS="$HOME/.openclaw/skills"

echo ""
echo "1. Checking skill directories..."
check_dir "$SKILLS/proposal-craft" "proposal-craft"
check_dir "$SKILLS/rfp-respond" "rfp-respond"
check_dir "$SKILLS/proposal-kb" "proposal-kb"

echo ""
echo "2. Checking key files..."
check_file "$SKILLS/proposal-craft/assets/proposal-template.md" "Proposal template"
check_file "$SKILLS/proposal-craft/scripts/generator.py" "Proposal generator"
check_file "$SKILLS/rfp-respond/assets/rfp-response-template.md" "RFP template"
check_file "$SKILLS/rfp-respond/scripts/generator.py" "RFP generator"
check_file "$SKILLS/proposal-kb/assets/kb.json" "Knowledge base"
check_file "$SKILLS/proposal-kb/scripts/query_kb.py" "KB query"
check_file "$SKILLS/proposal-kb/scripts/update_kb.py" "KB update"

echo ""
echo "3. Testing KB query..."
cd "$SKILLS/proposal-kb"
python3 scripts/query_kb.py \
    --kb assets/kb.json \
    --industry test \
    --project-type cloud_migration \
    --client "Verify" \
    --output /tmp/verify-draft.json 2>/dev/null && echo "✅ KB query works" || echo "⚠️ KB query test skipped"

echo ""
echo "4. Testing proposal generation..."
cd "$SKILLS/proposal-craft"
if [ -f /tmp/verify-draft.json ]; then
    python3 scripts/generator.py \
        --intake /tmp/verify-draft.json \
        --template assets/proposal-template.md \
        --output /tmp/verify-proposal.md 2>/dev/null && echo "✅ Proposal generation works" || echo "⚠️ Generator test skipped"
else
    echo "⚠️ Skipping generator test (no draft)"
fi

echo ""
echo "=========================================="
echo "✅ VERIFICATION COMPLETE"
echo "=========================================="
VERIFY

chmod +x /tmp/verify-proposal-system.sh
/tmp/verify-proposal-system.sh

# =============================================================================
# STEP 15: FINAL INSTRUCTIONS
# =============================================================================
echo ""
echo "=========================================="
echo "🎉 INSTALLATION COMPLETE!"
echo "=========================================="
echo ""
echo "📍 Skills installed at: $SKILLS_DIR"
echo ""
echo "⚠️  IMPORTANT: Customize the Knowledge Base"
echo "   nano $SKILLS_DIR/proposal-kb/assets/kb.json"
echo ""
echo "   Replace all [YOUR COMPANY NAME] placeholders"
echo "   Add your real case studies and pricing"
echo ""
echo "🚀 Quick Test:"
echo "   cd $SKILLS_DIR/proposal-kb"
echo "   python3 scripts/query_kb.py --kb assets/kb.json \\"
echo "     --industry manufacturing --project-type cloud_migration \\"
echo "     --client 'Test' --output /tmp/test.json"
echo ""
echo "   cd $SKILLS_DIR/proposal-craft"
echo "   python3 scripts/generator.py --intake /tmp/test.json \\"
echo "     --template assets/proposal-template.md --output /tmp/test.md"
echo ""
echo "📖 Documentation:"
echo "   $SKILLS_DIR/proposal-craft/SKILL.md"
echo "   $SKILLS_DIR/rfp-respond/SKILL.md"
echo "   $SKILLS_DIR/proposal-kb/SKILL.md"
echo ""
echo "=========================================="
