import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { projects, projectFiles, deployments } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import JSZip from "jszip";

// POST /api/deploy - Deploy a project to a hosting provider
export async function POST(req: NextRequest) {
  try {
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { projectId, provider = "vercel" } = body;

    if (!projectId) {
      return NextResponse.json({ error: "Project ID required" }, { status: 400 });
    }

    // Verify project
    const project = await db.select().from(projects).where(eq(projects.id, projectId)).get();
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }
    if (project.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Get files
    const files = await db.select().from(projectFiles).where(eq(projectFiles.projectId, projectId));

    if (files.length === 0) {
      return NextResponse.json({ error: "No files to deploy. Generate code first." }, { status: 400 });
    }

    // Create deployment record
    const deploymentId = crypto.randomUUID();
    await db.insert(deployments).values({
      id: deploymentId,
      projectId,
      provider,
      status: "building",
      buildLog: "Starting deployment...",
      createdAt: new Date(),
    });

    // For now, return a "manual deploy" package
    // In production, this would trigger Vercel/Netlify API
    const zip = new JSZip();
    
    // Add all files
    files.forEach(file => {
      zip.file(file.path, file.content || '');
    });

    // Add a README with deploy instructions
    const readme = `# ${project.name}

Generated by BuildAny (https://base66.cloud)

## Deploy

### Vercel (Recommended)
1. Install Vercel CLI: \`npm i -g vercel\`
2. Run: \`vercel\`
3. Follow prompts

### Netlify
1. Install Netlify CLI: \`npm i -g netlify-cli\`
2. Run: \`netlify deploy\`

### Self-host
1. Build: \`npm run build\`
2. Start: \`npm start\`

## Type
${project.type === 'mobile' ? 'Expo SDK 54 + React Native' : 'Next.js 15 + Tailwind + shadcn/ui'}
`;
    zip.file('README.md', readme);

    const zipContent = await zip.generateAsync({ type: 'uint8array' });

    // Update deployment status
    await db.update(deployments)
      .set({ 
        status: "ready", 
        buildLog: "Deployment package ready for download",
        url: `/api/deploy/${deploymentId}/download`
      })
      .where(eq(deployments.id, deploymentId));

    return NextResponse.json({
      success: true,
      deploymentId,
      status: "ready",
      downloadUrl: `/api/deploy/${deploymentId}/download`,
      message: "Deployment package created. Download and deploy to your preferred host.",
      providers: ["vercel", "netlify", "self-host"],
    });
  } catch (error) {
    console.error("Deploy error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}

// GET /api/deploy - List deployments for a project
export async function GET(req: NextRequest) {
  try {
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const projectId = searchParams.get("projectId");

    if (!projectId) {
      return NextResponse.json({ error: "Project ID required" }, { status: 400 });
    }

    const project = await db.select().from(projects).where(eq(projects.id, projectId)).get();
    if (!project || project.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const projectDeployments = await db
      .select()
      .from(deployments)
      .where(eq(deployments.projectId, projectId))
      .orderBy(deployments.createdAt);

    return NextResponse.json({
      success: true,
      deployments: projectDeployments,
    });
  } catch (error) {
    console.error("List deployments error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
