import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { wikiPages, projects } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";

// GET /api/project/[id]/wiki - Get all wiki pages for a project
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: projectId } = await params;

    // Verify project exists and belongs to user
    const project = await db
      .select()
      .from(projects)
      .where(eq(projects.id, projectId))
      .get();

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (project.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const pages = await db
      .select()
      .from(wikiPages)
      .where(eq(wikiPages.projectId, projectId))
      .orderBy(wikiPages.createdAt);

    return NextResponse.json({
      success: true,
      projectId,
      pages: pages.map((page) => ({
        ...page,
        content: page.content.length > 1000 
          ? page.content.slice(0, 1000) + "..." 
          : page.content,
        isTruncated: page.content.length > 1000,
      })),
      count: pages.length,
    });
  } catch (error) {
    console.error("Wiki fetch error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}

// POST /api/project/[id]/wiki - Create or update a wiki page
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id: projectId } = await params;
    const body = await req.json();
    const { pageType, title, content } = body;

    if (!pageType || !title || !content) {
      return NextResponse.json(
        { error: "pageType, title, and content are required" },
        { status: 400 }
      );
    }

    // Verify project ownership
    const project = await db
      .select()
      .from(projects)
      .where(eq(projects.id, projectId))
      .get();

    if (!project || project.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Check if page already exists
    const existingPage = await db
      .select()
      .from(wikiPages)
      .where(
        and(
          eq(wikiPages.projectId, projectId),
          eq(wikiPages.pageType, pageType)
        )
      )
      .get();

    if (existingPage) {
      // Update existing page
      await db
        .update(wikiPages)
        .set({
          title,
          content,
          lastUpdatedAt: new Date(),
        })
        .where(eq(wikiPages.id, existingPage.id));

      return NextResponse.json({
        success: true,
        message: "Wiki page updated",
        pageId: existingPage.id,
      });
    }

    // Create new page
    const pageId = crypto.randomUUID();
    await db.insert(wikiPages).values({
      id: pageId,
      projectId,
      pageType,
      title,
      content,
      autoGenerated: false,
      lastUpdatedAt: new Date(),
      createdAt: new Date(),
    });

    return NextResponse.json({
      success: true,
      message: "Wiki page created",
      pageId,
    });
  } catch (error) {
    console.error("Wiki create error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
