import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { projects, projectFiles, conversations, tasks, agents, wikiPages } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { llmRouter, getSystemPromptForType } from "@/lib/llm-router";

class HermesOrchestrator {
  constructor(public projectId: string, public prompt: string, public type: string, public userId: string) {}

  async report(message: string) {
    await db.insert(conversations).values({
      id: crypto.randomUUID(), projectId: this.projectId, role: "system",
      content: message, model: "hermes", createdAt: new Date(),
    });
    console.log(`[Hermes] ${message}`);
  }

  async design() {
    await this.report("🔍 Hermes: Starting DESIGN phase...");
    await this.report("📝 Hermes: Generating project wiki pages...");

    const designResult = await llmRouter.generate({
      prompt: `Create a design overview for this app: ${this.prompt}\n\nProvide:\n1. App concept and target users\n2. Core features (5-7 bullet points)\n3. Tech stack recommendation\n4. Architecture approach\n\nBe concise but comprehensive.`,
      systemPrompt: "You are a senior product architect. Create clear, structured design documents.",
      temperature: 0.7, maxTokens: 2000,
    });

    if (designResult.success && designResult.content) {
      await db.insert(wikiPages).values({
        id: crypto.randomUUID(), projectId: this.projectId,
        pageType: "overview", title: `${this.prompt.slice(0, 30)}... - Overview`,
        content: `# Project Overview\n\n**App Idea:** ${this.prompt}\n\n${designResult.content}`,
        autoGenerated: true, createdAt: new Date(),
      });

      const adrResult = await llmRouter.generate({
        prompt: `Based on this app idea, create an Architecture Decision Record:\n\n${this.prompt}\n\nFormat:\n## ADR-001: Tech Stack Decision\n\n### Context\nWhy we chose this approach.\n\n### Decision\nWhat we decided.\n\n### Consequences\nPros and cons.\n\n### Alternatives Considered\nWhat we rejected and why.`,
        systemPrompt: "You are a technical architect. Write clear ADRs in markdown format.",
        temperature: 0.6, maxTokens: 1500,
      });

      if (adrResult.success && adrResult.content) {
        await db.insert(wikiPages).values({
          id: crypto.randomUUID(), projectId: this.projectId,
          pageType: "adr", title: "ADR-001: Architecture Decisions",
          content: adrResult.content,
          autoGenerated: true, createdAt: new Date(),
        });
      }

      await this.report("✅ Hermes: DESIGN phase complete! Wiki pages generated. Check the Wiki tab.");
    }
    return designResult;
  }

  async build() {
    await this.report("⚡ Hermes: Starting BUILD phase...");
    await this.report("🔧 Hermes: Decomposing into tasks and assigning agents...");

    const taskDefs = [
      { title: "HTML Structure", description: "Main HTML with proper DOCTYPE, meta, viewport, semantic structure", type: "html", priority: 5 },
      { title: "CSS Styling", description: "Responsive CSS with modern styling, animations, theme support", type: "css", priority: 5 },
      { title: "JavaScript Logic", description: "Interactivity, event handlers, dynamic content, API calls if needed", type: "javascript", priority: 5 },
    ];

    const taskTypes = [...new Set(taskDefs.map(t => t.type))];
    const createdAgents = [];
    for (const taskType of taskTypes) {
      const agentId = crypto.randomUUID();
      await db.insert(agents).values({
        id: agentId, projectId: this.projectId, name: `${taskType.charAt(0).toUpperCase() + taskType.slice(1)} Agent`,
        type: taskType, status: "working",
        capabilities: JSON.stringify([taskType, "build"]),
        metadata: JSON.stringify({ projectId: this.projectId }),
        createdAt: new Date(),
      });
      createdAgents.push({ id: agentId, type: taskType });
    }

    const createdTasks = [];
    for (const taskDef of taskDefs) {
      const agent = createdAgents.find(a => a.type === taskDef.type);
      const taskId = crypto.randomUUID();
      await db.insert(tasks).values({
        id: taskId, projectId: this.projectId, agentId: agent?.id,
        type: taskDef.type, status: "pending", priority: taskDef.priority,
        title: taskDef.title, description: taskDef.description,
        createdAt: new Date(),
      });
      createdTasks.push({ id: taskId, ...taskDef, agentId: agent?.id });
    }

    await this.report(`🚀 Hermes: ${createdAgents.length} agents executing ${createdTasks.length} tasks in parallel...`);

    const results = await Promise.all(createdTasks.map(async (task) => {
      await db.update(tasks).set({ status: "running", startedAt: new Date() }).where(eq(tasks.id, task.id));

      const taskPrompt = `You are an expert ${task.type} developer.\n\nProject: ${this.prompt}\n\nTask: ${task.title}\nDescription: ${task.description}\n\nWrite clean, production-ready code. Return ONLY the code, no explanations, no markdown code blocks.`;

      const llmResult = await llmRouter.generate({
        prompt: taskPrompt,
        systemPrompt: getSystemPromptForType(this.type),
        temperature: 0.7, maxTokens: 3000,
      });

      if (llmResult.success && llmResult.content) {
        await db.update(tasks).set({ status: "completed", output: llmResult.content, completedAt: new Date() }).where(eq(tasks.id, task.id));
        return { task, code: llmResult.content, success: true };
      } else {
        await db.update(tasks).set({ status: "failed", errorLog: llmResult.error || "LLM failed" }).where(eq(tasks.id, task.id));
        return { task, error: llmResult.error, success: false };
      }
    }));

    const completedCount = results.filter(r => r.success).length;
    const failCount = results.filter(r => !r.success).length;
    await this.report(`✅ Hermes: BUILD phase complete! ${completedCount}/${results.length} tasks completed.${failCount > 0 ? ` ${failCount} failed.` : ""}`);

    return results;
  }

  async combine(results: any[]) {
    await this.report("🔄 Hermes: Assembling code from agent outputs...");

    const successful = results.filter(r => r.success);
    let html = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Generated App</title>\n  <style>\n    * { margin: 0; padding: 0; box-sizing: border-box; }\n    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }\n`;

    const cssResults = successful.filter(r => r.task.type === "css");
    for (const r of cssResults) html += `\n/* ${r.task.title} */\n${r.code}\n`;

    html += `  </style>\n</head>\n<body>\n`;

    const htmlResults = successful.filter(r => r.task.type === "html");
    for (const r of htmlResults) html += `\n${r.code}\n`;

    html += `  <script>\n    window.onerror = function(msg, url, line) {\n      console.error('Error:', msg, 'at line', line);\n      return false;\n    };\n`;

    const jsResults = successful.filter(r => r.task.type === "javascript");
    for (const r of jsResults) html += `\n    // ${r.task.title}\n    ${r.code}\n`;
    html += `  </script>\n</body>\n</html>`;

    await db.insert(projectFiles).values({
      id: crypto.randomUUID(), projectId: this.projectId,
      path: "index.html", content: html, language: "html",
      isGenerated: true, createdAt: new Date(), updatedAt: new Date(),
    });

    await this.report("✅ Hermes: Code assembled and saved! Check the Code tab.");
    return html;
  }

  async test(code: string) {
    await this.report("🧪 Hermes: Starting TEST phase...");
    await this.report("🔍 Hermes: Spinning up Test Agent to review code...");

    const testResult = await llmRouter.generate({
      prompt: `You are a senior QA engineer. Review this code thoroughly:\n\n${code.substring(0, 4000)}\n\nProvide:\n1. **Issues Found** (bugs, security issues, performance problems)\n2. **Test Checklist** (5-7 items to verify)\n3. **Quality Score** (1-10 with brief justification)\n4. **Recommendations** (specific improvements)\n\nBe concise but thorough.`,
      systemPrompt: "You are a senior QA engineer. Be thorough but concise. Focus on real issues, not nitpicks.",
      temperature: 0.5, maxTokens: 2000,
    });

    if (testResult.success && testResult.content) {
      await db.insert(wikiPages).values({
        id: crypto.randomUUID(), projectId: this.projectId,
        pageType: "test", title: "Test Report - Build Phase",
        content: `# Test Report\n\n**Generated:** ${new Date().toISOString()}\n\n${testResult.content}`,
        autoGenerated: true, createdAt: new Date(),
      });

      await this.report(`✅ Hermes: TEST phase complete!\n${testResult.content.substring(0, 150)}...\n\nCheck the Wiki tab for full test report.`);
    } else {
      await this.report("⚠️ Hermes: Test phase completed with warnings.");
    }
    return testResult;
  }

  async preview(code: string) {
    await this.report("👁️ Hermes: Starting PREVIEW phase...");
    await this.report("🎨 Hermes: Generating preview...");

    await db.insert(projectFiles).values({
      id: crypto.randomUUID(), projectId: this.projectId,
      path: "__preview.html", content: code, language: "html",
      isGenerated: true, createdAt: new Date(), updatedAt: new Date(),
    });

    await this.report("✅ Hermes: PREVIEW phase complete! Your app is ready for testing.");
    await this.report("🎉 Hermes: ALL PHASES COMPLETE! Check:\n• **Wiki tab** for design docs and test report\n• **Code tab** for source code\n• **Preview tab** to test your app");
  }

  async run() {
    try {
      await this.design();
      const results = await this.build();
      const code = await this.combine(results);
      await this.test(code);
      await this.preview(code);

      await db.update(projects).set({ status: "generated", updatedAt: new Date() }).where(eq(projects.id, this.projectId));
      return { success: true };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      await this.report(`❌ Hermes Error: ${errorMsg}`);
      await db.update(projects).set({ status: "failed", updatedAt: new Date() }).where(eq(projects.id, this.projectId));
      return { success: false, error: errorMsg };
    }
  }
}

export async function POST(req: NextRequest) {
  try {
    const authData = await auth();
    const userId = authData.userId || "guest-" + crypto.randomUUID();
    const { projectId, prompt, type = "web" } = await req.json();

    if (!prompt) return NextResponse.json({ error: "Missing prompt" }, { status: 400 });

    let project;
    if (!projectId) {
      const newId = crypto.randomUUID();
      await db.insert(projects).values({
        id: newId, userId, name: prompt.slice(0, 50), description: prompt,
        type: type as "web" | "mobile" | "dashboard",
        status: "generating", createdAt: new Date(), updatedAt: new Date(),
      });
      project = await db.select().from(projects).where(eq(projects.id, newId)).get();
    } else {
      project = await db.select().from(projects).where(eq(projects.id, projectId)).get();
      if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    await db.insert(conversations).values({
      id: crypto.randomUUID(), projectId: project.id, role: "user",
      content: prompt, model: "user", createdAt: new Date(),
    });

    const hermes = new HermesOrchestrator(project.id, prompt, type, userId);
    hermes.run().catch(err => console.error("Hermes run error:", err));

    return NextResponse.json({
      success: true, projectId: project.id,
      message: "🚀 Hermes Orchestrator started! Watch progress in the AI Chat...",
    });
  } catch (error) {
    console.error("Orchestrate error:", error);
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
