import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { deployments, projectFiles, projects } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import JSZip from "jszip";

// GET /api/deploy/[id]/download - Download deployment package
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get deployment
    const deployment = await db.select().from(deployments).where(eq(deployments.id, id)).get();
    if (!deployment) {
      return NextResponse.json({ error: "Deployment not found" }, { status: 404 });
    }

    // Verify project ownership
    const project = await db.select().from(projects).where(eq(projects.id, deployment.projectId)).get();
    if (!project || project.userId !== userId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Get files
    const files = await db.select().from(projectFiles).where(eq(projectFiles.projectId, deployment.projectId));

    const zip = new JSZip();
    files.forEach(file => {
      zip.file(file.path, file.content || '');
    });

    // Add README
    const readme = `# ${project.name}

Generated by BuildAny (https://base66.cloud)
Type: ${project.type}
Status: ${project.status}

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

## Deploy

- **Vercel**: \`vercel\`
- **Netlify**: \`netlify deploy\`
- **Self-host**: \`npm run build && npm start\`
`;
    zip.file('README.md', readme);

    const zipContent = await zip.generateAsync({ type: 'uint8array' });

    return new NextResponse(Buffer.from(zipContent), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${project.name}-deploy.zip"`,
      },
    });
  } catch (error: any) {
    console.error('Deployment download error:', error);
    return NextResponse.json({ error: 'Download failed', details: error.message }, { status: 500 });
  }
}
