import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { projects } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { randomUUID } from "crypto";

export async function POST(req: Request) {
  try {
    const authData = await auth();
    const userId = authData.userId;
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { projectId, name } = body;

    // Get project
    const project = await db.select().from(projects).where(eq(projects.id, projectId)).get();
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Get files for the project
    const { projectFiles } = await import("@/lib/db/schema");
    const files = await db.select().from(projectFiles).where(eq(projectFiles.projectId, projectId));

    // Create GitHub repo
    const githubToken = process.env.GITHUB_TOKEN;
    if (!githubToken) {
      return NextResponse.json({ error: "GitHub token not configured" }, { status: 500 });
    }

    const repoName = name.toLowerCase().replace(/[^a-z0-9-]/g, "-");
    
    // Create repo
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        description: project.description || "Generated by BuildAny",
        private: false,
        auto_init: true,
      }),
    });

    if (!createRes.ok) {
      const error = await createRes.json();
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    const repo = await createRes.json();

    // Commit files
    for (const file of files) {
      await fetch(`https://api.github.com/repos/${repo.full_name}/contents/${file.path}`, {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `Add ${file.path}`,
          content: Buffer.from(file.content || "").toString("base64"),
        }),
      });
    }

    // Update project with GitHub repo
    await db.update(projects)
      .set({ githubRepo: repo.full_name })
      .where(eq(projects.id, projectId));

    return NextResponse.json({
      repoUrl: repo.html_url,
      repoName: repo.full_name,
    });
  } catch (error) {
    console.error("GitHub error:", error);
    return NextResponse.json({ error: "Failed to create repo" }, { status: 500 });
  }
}