export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'dessert';
export type TasteTag = 'spicy' | 'not-spicy' | 'sweet' | 'savory' | 'sour';
export type DietTag = 'vegan' | 'vegetarian' | 'keto' | 'gluten-free' | 'dairy-free' | 'high-protein';
export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Ingredient {
  name: string;
  amount: number;
  unit: string;
}

export interface RecipeStep {
  stepNumber: number;
  instruction: string;
  timerMinutes?: number;
}

export interface Nutrition {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface Recipe {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  mealType: MealType[];
  tasteTags: TasteTag[];
  dietTags: DietTag[];
  difficulty: Difficulty;
  prepTimeMinutes: number;
  cookTimeMinutes: number;
  servings: number;
  rating: number;
  ratingCount: number;
  ingredients: Ingredient[];
  steps: RecipeStep[];
  nutrition: Nutrition;
  tips: string[];
  isFeatured?: boolean;
  isTrending?: boolean;
  isPremium?: boolean;
}

export const HIGH_PROTEIN_RECIPES_BATCH_2: Recipe[] = [
  {
    id: 'r151',
    title: 'Greek Yogurt Chicken Salad',
    description: 'A creamy, protein-packed chicken salad made with Greek yogurt instead of mayo. Loaded with celery, grapes, and walnuts for crunch and sweetness.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    rating: 4.6,
    ratingCount: 2100,
    ingredients: [
      { name: 'Chicken breast', amount: 500, unit: 'g' },
      { name: 'Greek yogurt', amount: 200, unit: 'g' },
      { name: 'Celery stalks', amount: 3, unit: 'pieces' },
      { name: 'Red grapes', amount: 150, unit: 'g' },
      { name: 'Walnuts', amount: 60, unit: 'g' },
      { name: 'Dijon mustard', amount: 1, unit: 'tbsp' },
      { name: 'Lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'Dried dill', amount: 1, unit: 'tsp' },
      { name: 'Lettuce leaves', amount: 8, unit: 'pieces' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Season chicken breast with salt and pepper. Bake at 200°C for 18-20 minutes until fully cooked. Let cool.' },
      { stepNumber: 2, instruction: 'Dice cooled chicken into small cubes. Chop celery and halve the grapes.' },
      { stepNumber: 3, instruction: 'In a large bowl, mix Greek yogurt, Dijon mustard, lemon juice, and dried dill.' },
      { stepNumber: 4, instruction: 'Add chicken, celery, grapes, and walnuts to the yogurt mixture. Fold gently until evenly coated.' },
      { stepNumber: 5, instruction: 'Serve in lettuce cups or on whole grain bread. Chill before serving for best flavor.' },
    ],
    nutrition: { calories: 380, protein: 42, carbs: 18, fat: 14, fiber: 3 },
    tips: [
      'Greek yogurt gives the same creaminess as mayo but with way more protein.',
      'Add a pinch of curry powder for an unexpected warm twist.',
      'Keeps well in the fridge for 3 days — perfect for meal prep.',
    ],
  },
  {
    id: 'r152',
    title: 'Lentil & Quinoa Power Bowl',
    description: 'A hearty vegetarian bowl packed with plant-based protein from lentils and quinoa, topped with roasted vegetables and tahini dressing.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian', 'vegan'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    rating: 4.5,
    ratingCount: 1800,
    ingredients: [
      { name: 'Quinoa', amount: 200, unit: 'g' },
      { name: 'Green lentils', amount: 200, unit: 'g' },
      { name: 'Sweet potato', amount: 2, unit: 'medium' },
      { name: 'Red bell pepper', amount: 2, unit: 'pieces' },
      { name: 'Broccoli florets', amount: 300, unit: 'g' },
      { name: 'Tahini', amount: 3, unit: 'tbsp' },
      { name: 'Lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Pumpkin seeds', amount: 40, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Rinse quinoa and lentils. Cook quinoa in 400ml water for 15 minutes. Simmer lentils in 600ml water for 20 minutes until tender.' },
      { stepNumber: 2, instruction: 'Cube sweet potatoes and toss with olive oil, salt, and pepper. Roast at 200°C for 25 minutes.' },
      { stepNumber: 3, instruction: 'Toss broccoli and bell pepper with olive oil. Add to the oven for the last 15 minutes.' },
      { stepNumber: 4, instruction: 'Whisk tahini, lemon juice, minced garlic, and 2 tbsp warm water until smooth. Thin with more water if needed.' },
      { stepNumber: 5, instruction: 'Assemble bowls: quinoa and lentils base, roasted veggies on top, drizzle with tahini sauce, sprinkle pumpkin seeds.' },
    ],
    nutrition: { calories: 520, protein: 24, carbs: 68, fat: 16, fiber: 14 },
    tips: [
      'This bowl delivers complete protein — quinoa provides all nine essential amino acids.',
      'Prep all components on Sunday and assemble fresh all week.',
      'Swap broccoli for cauliflower or Brussels sprouts based on season.',
    ],
  },
  {
    id: 'r153',
    title: 'Cottage Cheese Protein Pancakes',
    description: 'Fluffy, high-protein pancakes made with cottage cheese and oats. No flour needed — just blend, pour, and flip.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600',
    mealType: ['breakfast'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    rating: 4.7,
    ratingCount: 3400,
    ingredients: [
      { name: 'Cottage cheese', amount: 250, unit: 'g' },
      { name: 'Rolled oats', amount: 80, unit: 'g' },
      { name: 'Eggs', amount: 3, unit: 'large' },
      { name: 'Vanilla extract', amount: 1, unit: 'tsp' },
      { name: 'Baking powder', amount: 1, unit: 'tsp' },
      { name: 'Cinnamon', amount: 1, unit: 'tsp' },
      { name: 'Maple syrup', amount: 2, unit: 'tbsp' },
      { name: 'Fresh blueberries', amount: 100, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Add cottage cheese, oats, eggs, vanilla, baking powder, and cinnamon to a blender. Blend for 60 seconds until smooth.' },
      { stepNumber: 2, instruction: 'Let batter rest for 5 minutes so oats can absorb moisture.' },
      { stepNumber: 3, instruction: 'Heat a non-stick pan over medium heat. Pour 1/4 cup batter per pancake.' },
      { stepNumber: 4, instruction: 'Cook 2-3 minutes until bubbles form on surface. Flip and cook 1-2 more minutes.' },
      { stepNumber: 5, instruction: 'Stack pancakes, top with blueberries, and drizzle maple syrup.' },
    ],
    nutrition: { calories: 420, protein: 32, carbs: 42, fat: 14, fiber: 5 },
    tips: [
      'Blend the batter the night before for even easier morning prep.',
      'Add a scoop of protein powder for an extra 10g protein boost.',
      'These freeze well — reheat in a toaster for a quick protein breakfast.',
    ],
  },
  {
    id: 'r154',
    title: 'Turkey & Spinach Meatballs',
    description: 'Lean turkey meatballs loaded with spinach and parmesan, baked until golden and served with marinara over zucchini noodles.',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 4,
    rating: 4.6,
    ratingCount: 2200,
    ingredients: [
      { name: 'Ground turkey', amount: 500, unit: 'g' },
      { name: 'Baby spinach', amount: 150, unit: 'g' },
      { name: 'Parmesan cheese', amount: 60, unit: 'g' },
      { name: 'Egg', amount: 1, unit: 'large' },
      { name: 'Almond flour', amount: 40, unit: 'g' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Italian seasoning', amount: 1, unit: 'tbsp' },
      { name: 'Marinara sauce', amount: 400, unit: 'g' },
      { name: 'Zucchini', amount: 4, unit: 'medium' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Finely chop spinach. Mix with ground turkey, parmesan, egg, almond flour, minced garlic, Italian seasoning, salt, and pepper.' },
      { stepNumber: 2, instruction: 'Roll mixture into 20 meatballs, about 3cm each. Place on a lined baking sheet.' },
      { stepNumber: 3, instruction: 'Bake at 200°C for 18-20 minutes until internal temp reaches 74°C and outsides are golden.' },
      { stepNumber: 4, instruction: 'Spiralize zucchini into noodles. Sauté in olive oil over medium-high heat for 3-4 minutes until just tender.' },
      { stepNumber: 5, instruction: 'Warm marinara in a pan. Add baked meatballs and toss to coat. Serve over zucchini noodles.' },
    ],
    nutrition: { calories: 360, protein: 38, carbs: 14, fat: 16, fiber: 4 },
    tips: [
      'Squeeze excess moisture from spinach so meatballs hold together.',
      'Almond flour keeps these gluten-free and adds a subtle nutty flavor.',
      'Make a double batch — they freeze beautifully for up to 3 months.',
    ],
  },
  {
    id: 'r155',
    title: 'Salmon & Avocado Sushi Bowl',
    description: 'A deconstructed sushi bowl with fresh salmon, creamy avocado, edamame, and pickled ginger over seasoned sushi rice.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.8,
    ratingCount: 4100,
    ingredients: [
      { name: 'Sushi-grade salmon', amount: 300, unit: 'g' },
      { name: 'Sushi rice', amount: 200, unit: 'g' },
      { name: 'Avocado', amount: 2, unit: 'large' },
      { name: 'Edamame beans', amount: 150, unit: 'g' },
      { name: 'Pickled ginger', amount: 40, unit: 'g' },
      { name: 'Nori sheets', amount: 2, unit: 'pieces' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Rice vinegar', amount: 2, unit: 'tbsp' },
      { name: 'Sesame seeds', amount: 1, unit: 'tbsp' },
      { name: 'Wasabi', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Rinse sushi rice until water runs clear. Cook with 250ml water. While warm, fold in rice vinegar and a pinch of sugar.' },
      { stepNumber: 2, instruction: 'Cut salmon into 1cm cubes. Slice avocado thinly. Shell edamame if needed.' },
      { stepNumber: 3, instruction: 'Tear nori into small strips with scissors.' },
      { stepNumber: 4, instruction: 'Divide rice between bowls. Arrange salmon, avocado, edamame, and pickled ginger in sections.' },
      { stepNumber: 5, instruction: 'Top with nori strips, sesame seeds, and a dot of wasabi. Drizzle with soy sauce before eating.' },
    ],
    nutrition: { calories: 580, protein: 36, carbs: 52, fat: 24, fiber: 8 },
    tips: [
      'Use only sushi-grade salmon from a trusted fishmonger for raw preparation.',
      'Cook salmon lightly if you prefer — 3 minutes in a hot pan keeps it tender.',
      'Add cucumber or carrots for extra crunch and volume without calories.',
    ],
  },
  {
    id: 'r156',
    title: 'Egg White Veggie Frittata',
    description: 'A light, fluffy frittata made with egg whites, loaded with colorful vegetables and feta cheese. Perfect for a high-protein brunch.',
    imageUrl: 'https://images.unsplash.com/photo-1513442542250-854d43654226?w=600',
    mealType: ['breakfast', 'lunch'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian', 'keto'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    rating: 4.4,
    ratingCount: 1600,
    ingredients: [
      { name: 'Egg whites', amount: 12, unit: 'large' },
      { name: 'Whole eggs', amount: 2, unit: 'large' },
      { name: 'Cherry tomatoes', amount: 200, unit: 'g' },
      { name: 'Red bell pepper', amount: 1, unit: 'piece' },
      { name: 'Spinach', amount: 100, unit: 'g' },
      { name: 'Feta cheese', amount: 80, unit: 'g' },
      { name: 'Red onion', amount: 1, unit: 'small' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Dried oregano', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 180°C. Heat olive oil in an oven-safe skillet over medium heat.' },
      { stepNumber: 2, instruction: 'Sauté onion and bell pepper for 4 minutes until softened. Add spinach and cook until wilted.' },
      { stepNumber: 3, instruction: 'Whisk egg whites, whole eggs, oregano, salt, and pepper in a bowl until frothy.' },
      { stepNumber: 4, instruction: 'Pour eggs over vegetables in the skillet. Scatter cherry tomatoes and crumbled feta on top.' },
      { stepNumber: 5, instruction: 'Cook on stove for 3 minutes until edges set, then transfer to oven for 15 minutes until center is set.' },
      { stepNumber: 6, instruction: 'Let cool slightly, slice into wedges, and serve warm or at room temperature.' },
    ],
    nutrition: { calories: 240, protein: 28, carbs: 10, fat: 10, fiber: 2 },
    tips: [
      'Using mostly egg whites keeps this lean while the 2 whole eggs add richness.',
      'Any vegetables work — try mushrooms, zucchini, or asparagus.',
      'Make ahead and reheat slices in the microwave for 45 seconds.',
    ],
  },
  {
    id: 'r157',
    title: 'Beef & Broccoli Stir-Fry',
    description: 'Tender strips of beef flank steak stir-fried with crisp broccoli in a savory ginger-garlic soy sauce. A classic high-protein dinner.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f1d687a32?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 4,
    rating: 4.7,
    ratingCount: 3800,
    ingredients: [
      { name: 'Flank steak', amount: 500, unit: 'g' },
      { name: 'Broccoli florets', amount: 400, unit: 'g' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Oyster sauce', amount: 2, unit: 'tbsp' },
      { name: 'Cornstarch', amount: 1, unit: 'tbsp' },
      { name: 'Ginger', amount: 2, unit: 'tbsp' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Sesame oil', amount: 1, unit: 'tsp' },
      { name: 'Vegetable oil', amount: 2, unit: 'tbsp' },
      { name: 'Brown rice', amount: 300, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Slice flank steak against the grain into thin strips. Toss with 1 tbsp soy sauce and cornstarch. Let marinate 10 minutes.' },
      { stepNumber: 2, instruction: 'Mix remaining soy sauce, oyster sauce, sesame oil, and 2 tbsp water in a small bowl.' },
      { stepNumber: 3, instruction: 'Heat vegetable oil in a wok or large skillet over high heat. Stir-fry beef in batches for 2 minutes until browned. Remove.' },
      { stepNumber: 4, instruction: 'Add broccoli and 2 tbsp water to the pan. Cover and steam for 3 minutes until bright green and crisp-tender.' },
      { stepNumber: 5, instruction: 'Add ginger and garlic. Cook 30 seconds until fragrant. Return beef to pan, pour in sauce, toss 1 minute until glossy.' },
      { stepNumber: 6, instruction: 'Serve immediately over steamed brown rice.' },
    ],
    nutrition: { calories: 480, protein: 40, carbs: 42, fat: 16, fiber: 6 },
    tips: [
      'Slice the beef very thin and against the grain for maximum tenderness.',
      'High heat and quick cooking are essential — do not crowd the pan.',
      'Swap brown rice for cauliflower rice to cut carbs significantly.',
    ],
  },
  {
    id: 'r158',
    title: 'Chickpea & Tuna Mediterranean Salad',
    description: 'A refreshing, protein-rich salad combining tuna, chickpeas, cucumber, and olives with a lemon-herb dressing. No cooking required.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'sour'],
    dietTags: ['high-protein', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 3,
    rating: 4.5,
    ratingCount: 1900,
    ingredients: [
      { name: 'Canned tuna in water', amount: 400, unit: 'g' },
      { name: 'Chickpeas', amount: 400, unit: 'g' },
      { name: 'Cucumber', amount: 2, unit: 'medium' },
      { name: 'Cherry tomatoes', amount: 250, unit: 'g' },
      { name: 'Kalamata olives', amount: 80, unit: 'g' },
      { name: 'Red onion', amount: 1, unit: 'small' },
      { name: 'Lemon juice', amount: 3, unit: 'tbsp' },
      { name: 'Extra virgin olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Dried oregano', amount: 1, unit: 'tsp' },
      { name: 'Fresh parsley', amount: 30, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Drain and rinse chickpeas and tuna. Flake tuna with a fork in a large mixing bowl.' },
      { stepNumber: 2, instruction: 'Dice cucumber and halve cherry tomatoes. Thinly slice red onion.' },
      { stepNumber: 3, instruction: 'Add chickpeas, cucumber, tomatoes, olives, and onion to the tuna.' },
      { stepNumber: 4, instruction: 'Whisk lemon juice, olive oil, oregano, salt, and pepper. Pour over salad and toss gently.' },
      { stepNumber: 5, instruction: 'Chop fresh parsley and sprinkle on top. Serve immediately or chill for 30 minutes for deeper flavor.' },
    ],
    nutrition: { calories: 420, protein: 36, carbs: 28, fat: 18, fiber: 8 },
    tips: [
      'This is a perfect no-cook summer dinner — just open cans and chop.',
      'Add artichoke hearts or roasted peppers for extra Mediterranean flair.',
      'Serve with whole grain pita or over mixed greens for a complete meal.',
    ],
  },
  {
    id: 'r159',
    title: 'Protein Overnight Oats',
    description: 'Creamy overnight oats made with protein powder, chia seeds, and almond butter. Grab-and-go breakfast with 30g+ protein.',
    imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600',
    mealType: ['breakfast', 'snack'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    rating: 4.6,
    ratingCount: 2700,
    ingredients: [
      { name: 'Rolled oats', amount: 60, unit: 'g' },
      { name: 'Vanilla protein powder', amount: 30, unit: 'g' },
      { name: 'Chia seeds', amount: 15, unit: 'g' },
      { name: 'Almond butter', amount: 20, unit: 'g' },
      { name: 'Almond milk', amount: 200, unit: 'ml' },
      { name: 'Greek yogurt', amount: 100, unit: 'g' },
      { name: 'Honey', amount: 1, unit: 'tsp' },
      { name: 'Banana', amount: 1, unit: 'medium' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'In a jar or container, combine oats, protein powder, and chia seeds.' },
      { stepNumber: 2, instruction: 'Add almond milk and Greek yogurt. Stir thoroughly until no protein powder clumps remain.' },
      { stepNumber: 3, instruction: 'Stir in almond butter and honey. Mix until well combined.' },
      { stepNumber: 4, instruction: 'Cover and refrigerate overnight (at least 6 hours).' },
      { stepNumber: 5, instruction: 'In the morning, stir and top with sliced banana. Add a splash of milk if too thick.' },
    ],
    nutrition: { calories: 520, protein: 34, carbs: 52, fat: 18, fiber: 10 },
    tips: [
      'Use a flavored protein powder you actually enjoy — it drives the taste.',
      'Prep 3-4 jars on Sunday for the whole work week.',
      'Warm in the microwave for 60 seconds if you prefer hot oatmeal.',
    ],
  },
  {
    id: 'r160',
    title: 'Shrimp & Asparagus Skillet',
    description: 'Garlicky shrimp and crisp-tender asparagus cooked in one skillet with lemon butter. Fast, elegant, and packed with protein.',
    imageUrl: 'https://images.unsplash.com/photo-1559737558-2f5a3d0c3a1c?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    rating: 4.7,
    ratingCount: 2300,
    ingredients: [
      { name: 'Large shrimp', amount: 400, unit: 'g' },
      { name: 'Asparagus', amount: 300, unit: 'g' },
      { name: 'Butter', amount: 30, unit: 'g' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'Lemon zest', amount: 1, unit: 'tsp' },
      { name: 'Red pepper flakes', amount: 1, unit: 'tsp' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Fresh parsley', amount: 20, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Peel and devein shrimp if needed. Pat dry with paper towels.' },
      { stepNumber: 2, instruction: 'Trim woody ends from asparagus. Cut spears into 5cm pieces.' },
      { stepNumber: 3, instruction: 'Heat olive oil and half the butter in a large skillet over medium-high heat. Sear shrimp 1-2 minutes per side until pink. Remove.' },
      { stepNumber: 4, instruction: 'Add asparagus to the same pan. Cook 4-5 minutes, stirring occasionally, until bright green and tender-crisp.' },
      { stepNumber: 5, instruction: 'Add garlic, red pepper flakes, and remaining butter. Cook 30 seconds until fragrant.' },
      { stepNumber: 6, instruction: 'Return shrimp to pan. Add lemon juice and zest. Toss everything together for 1 minute. Garnish with parsley.' },
    ],
    nutrition: { calories: 320, protein: 38, carbs: 12, fat: 14, fiber: 4 },
    tips: [
      'Do not overcook shrimp — they go from perfect to rubbery in under a minute.',
      'Use jumbo shrimp if available for a more impressive presentation.',
      'Serve over cauliflower rice or with a side salad to keep it keto-friendly.',
    ],
  },
  {
    id: 'r161',
    title: 'Tofu Scramble with Spinach & Mushrooms',
    description: 'A savory, high-protein vegan scramble using extra-firm tofu, sautéed mushrooms, and wilted spinach. Seasoned with turmeric and nutritional yeast.',
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600',
    mealType: ['breakfast', 'lunch'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'vegan', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.4,
    ratingCount: 1500,
    ingredients: [
      { name: 'Extra-firm tofu', amount: 400, unit: 'g' },
      { name: 'Baby spinach', amount: 150, unit: 'g' },
      { name: 'Cremini mushrooms', amount: 200, unit: 'g' },
      { name: 'Nutritional yeast', amount: 2, unit: 'tbsp' },
      { name: 'Turmeric', amount: 1, unit: 'tsp' },
      { name: 'Garlic powder', amount: 1, unit: 'tsp' },
      { name: 'Black salt (kala namak)', amount: 1, unit: 'tsp' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Cherry tomatoes', amount: 150, unit: 'g' },
      { name: 'Avocado', amount: 1, unit: 'large' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Press tofu for 10 minutes to remove excess water. Crumble into small pieces resembling scrambled eggs.' },
      { stepNumber: 2, instruction: 'Heat olive oil in a non-stick skillet. Add mushrooms and cook 5 minutes until browned and moisture evaporates.' },
      { stepNumber: 3, instruction: 'Add crumbled tofu, turmeric, garlic powder, and black salt. Stir-fry 5 minutes until tofu is golden and slightly crispy.' },
      { stepNumber: 4, instruction: 'Add spinach and cherry tomatoes. Cook 2-3 minutes until spinach wilts and tomatoes soften.' },
      { stepNumber: 5, instruction: 'Sprinkle nutritional yeast over the scramble and toss to coat. Cook 1 more minute.' },
      { stepNumber: 6, instruction: 'Serve with sliced avocado on the side and whole grain toast if desired.' },
    ],
    nutrition: { calories: 340, protein: 22, carbs: 18, fat: 22, fiber: 8 },
    tips: [
      'Black salt adds an eggy sulfur flavor — it is the secret to convincing tofu scramble.',
      'Extra-firm tofu is essential; silken will fall apart into mush.',
      'Add diced bell peppers or onions for extra vegetables and color.',
    ],
  },
  {
    id: 'r162',
    title: 'Seared Tuna Steaks with Sesame Crust',
    description: 'Ahi tuna steaks coated in sesame seeds and seared rare in the center. Served with a ginger-soy dipping sauce and cucumber salad.',
    imageUrl: 'https://images.unsplash.com/photo-1559737558-2f5a3d0c3a1c?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free', 'dairy-free'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 5,
    servings: 2,
    rating: 4.8,
    ratingCount: 3200,
    ingredients: [
      { name: 'Ahi tuna steaks', amount: 300, unit: 'g' },
      { name: 'Sesame seeds', amount: 40, unit: 'g' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Rice vinegar', amount: 1, unit: 'tbsp' },
      { name: 'Fresh ginger', amount: 1, unit: 'tbsp' },
      { name: 'Sesame oil', amount: 1, unit: 'tsp' },
      { name: 'Wasabi paste', amount: 1, unit: 'tsp' },
      { name: 'Cucumber', amount: 2, unit: 'medium' },
      { name: 'Avocado', amount: 1, unit: 'large' },
      { name: 'Vegetable oil', amount: 1, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Pat tuna steaks completely dry. Press sesame seeds onto all sides to form an even crust.' },
      { stepNumber: 2, instruction: 'Heat vegetable oil in a heavy skillet until smoking hot. Sear tuna 45-60 seconds per side. Center should stay raw/rare.' },
      { stepNumber: 3, instruction: 'Transfer to a cutting board. Let rest 2 minutes, then slice against the grain into 1cm thick pieces.' },
      { stepNumber: 4, instruction: 'Whisk soy sauce, rice vinegar, grated ginger, sesame oil, and wasabi for dipping sauce.' },
      { stepNumber: 5, instruction: 'Thinly slice cucumber and arrange on plates with avocado slices and tuna. Drizzle with some dipping sauce.' },
    ],
    nutrition: { calories: 380, protein: 42, carbs: 12, fat: 18, fiber: 5 },
    tips: [
      'Buy sushi-grade ahi tuna from a trusted fishmonger when serving rare.',
      'The pan must be very hot — a weak sear will overcook the center before the crust forms.',
      'If you prefer cooked-through tuna, bake at 200°C for 10-12 minutes instead.',
    ],
  },
  {
    id: 'r163',
    title: 'Chicken Fajita Lettuce Wraps',
    description: 'Sizzling chicken fajita strips with peppers and onions, served in crisp lettuce cups instead of tortillas. Low-carb and protein-packed.',
    imageUrl: 'https://images.unsplash.com/photo-1534352956036-cd81e27fed21?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 4,
    rating: 4.6,
    ratingCount: 2500,
    ingredients: [
      { name: 'Chicken breast', amount: 600, unit: 'g' },
      { name: 'Green bell pepper', amount: 2, unit: 'pieces' },
      { name: 'Red bell pepper', amount: 1, unit: 'piece' },
      { name: 'Yellow onion', amount: 1, unit: 'large' },
      { name: 'Butter lettuce', amount: 12, unit: 'leaves' },
      { name: 'Lime juice', amount: 2, unit: 'tbsp' },
      { name: 'Cumin', amount: 1, unit: 'tsp' },
      { name: 'Chili powder', amount: 1, unit: 'tsp' },
      { name: 'Smoked paprika', amount: 1, unit: 'tsp' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Fresh cilantro', amount: 30, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Slice chicken into thin strips. Slice peppers and onion into similar-sized strips.' },
      { stepNumber: 2, instruction: 'Mix cumin, chili powder, paprika, salt, and pepper. Toss half with chicken, half with vegetables.' },
      { stepNumber: 3, instruction: 'Heat olive oil in a large skillet over high heat. Cook chicken 5-6 minutes until browned and cooked through. Remove.' },
      { stepNumber: 4, instruction: 'Add peppers and onion to the same pan. Sauté 4-5 minutes until charred at edges and slightly softened.' },
      { stepNumber: 5, instruction: 'Return chicken to pan. Squeeze lime juice over everything and toss. Cook 1 minute to combine flavors.' },
      { stepNumber: 6, instruction: 'Spoon fajita mixture into lettuce cups. Top with fresh cilantro and an extra lime wedge.' },
    ],
    nutrition: { calories: 280, protein: 36, carbs: 12, fat: 10, fiber: 3 },
    tips: [
      'Butter lettuce (also called Boston or Bibb) is the best wrap — soft, flexible, and cup-shaped.',
      'If you want some carbs, serve with a small side of black beans or corn tortillas.',
      'Top with guacamole or salsa for extra flavor and healthy fats.',
    ],
  },
  {
    id: 'r164',
    title: 'Salmon Patties with Dill Yogurt Sauce',
    description: 'Crispy pan-fried salmon patties made with canned salmon, breadcrumbs, and herbs. Served with a cool dill yogurt dipping sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    rating: 4.5,
    ratingCount: 1700,
    ingredients: [
      { name: 'Canned salmon', amount: 400, unit: 'g' },
      { name: 'Breadcrumbs', amount: 80, unit: 'g' },
      { name: 'Egg', amount: 1, unit: 'large' },
      { name: 'Dijon mustard', amount: 1, unit: 'tbsp' },
      { name: 'Green onion', amount: 3, unit: 'pieces' },
      { name: 'Dried dill', amount: 1, unit: 'tsp' },
      { name: 'Lemon zest', amount: 1, unit: 'tsp' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Greek yogurt', amount: 150, unit: 'g' },
      { name: 'Fresh dill', amount: 20, unit: 'g' },
      { name: 'Lemon juice', amount: 1, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Drain salmon well. Remove skin and large bones if present. Flake into a bowl.' },
      { stepNumber: 2, instruction: 'Add breadcrumbs, egg, Dijon mustard, chopped green onion, dried dill, lemon zest, salt, and pepper. Mix until combined.' },
      { stepNumber: 3, instruction: 'Form mixture into 8 patties, about 2cm thick. Chill in fridge for 10 minutes to firm up.' },
      { stepNumber: 4, instruction: 'Heat olive oil in a non-stick pan over medium heat. Fry patties 3-4 minutes per side until golden and crispy.' },
      { stepNumber: 5, instruction: 'Mix Greek yogurt, fresh dill, lemon juice, and a pinch of salt for the sauce.' },
      { stepNumber: 6, instruction: 'Serve patties warm with dill yogurt sauce on the side. Great with a simple green salad.' },
    ],
    nutrition: { calories: 340, protein: 32, carbs: 16, fat: 16, fiber: 1 },
    tips: [
      'Canned salmon is budget-friendly and already cooked — just drain and mix.',
      'Chilling the patties before frying prevents them from falling apart in the pan.',
      'Try baking at 200°C for 15 minutes if you want to avoid frying.',
    ],
  },
  {
    id: 'r165',
    title: 'Beef & Lentil Bolognese',
    description: 'A hearty pasta sauce combining lean ground beef and lentils for a fiber and protein boost. Simmered with tomatoes, wine, and Italian herbs.',
    imageUrl: 'https://images.unsplash.com/photo-1626844131082-256783844137?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    servings: 6,
    rating: 4.7,
    ratingCount: 2100,
    ingredients: [
      { name: 'Lean ground beef', amount: 400, unit: 'g' },
      { name: 'Brown lentils', amount: 150, unit: 'g' },
      { name: 'Canned crushed tomatoes', amount: 800, unit: 'g' },
      { name: 'Red wine', amount: 120, unit: 'ml' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Carrot', amount: 2, unit: 'medium' },
      { name: 'Celery', amount: 2, unit: 'stalks' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Dried oregano', amount: 1, unit: 'tsp' },
      { name: 'Bay leaf', amount: 2, unit: 'pieces' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Whole wheat pasta', amount: 400, unit: 'g' },
      { name: 'Parmesan cheese', amount: 60, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Finely dice onion, carrot, and celery (soffritto base). Mince garlic.' },
      { stepNumber: 2, instruction: 'Heat olive oil in a large pot. Sauté soffritto over medium heat for 8 minutes until soft and fragrant.' },
      { stepNumber: 3, instruction: 'Add ground beef. Break apart with a spoon and cook until browned, about 6 minutes.' },
      { stepNumber: 4, instruction: 'Stir in lentils, crushed tomatoes, wine, oregano, bay leaf, salt, and pepper. Bring to a boil, then reduce to a simmer.' },
      { stepNumber: 5, instruction: 'Cover and simmer for 35-40 minutes, stirring occasionally, until lentils are tender and sauce is thick.' },
      { stepNumber: 6, instruction: 'Cook pasta according to package directions. Serve sauce over pasta with grated parmesan on top.' },
    ],
    nutrition: { calories: 520, protein: 34, carbs: 58, fat: 14, fiber: 12 },
    tips: [
      'Lentils stretch the meat and add incredible fiber — you will not miss the extra beef.',
      'Use red wine you would drink — cheap cooking wine ruins the sauce.',
      'This sauce freezes perfectly in portions for up to 3 months.',
    ],
  },
  {
    id: 'r166',
    title: 'Greek Chicken Souvlaki Bowl',
    description: 'Marinated grilled chicken skewers served over rice with tzatziki, cucumber, tomatoes, and kalamata olives. A Mediterranean protein feast.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    rating: 4.8,
    ratingCount: 2900,
    ingredients: [
      { name: 'Chicken thighs', amount: 600, unit: 'g' },
      { name: 'Greek yogurt', amount: 200, unit: 'g' },
      { name: 'Lemon juice', amount: 3, unit: 'tbsp' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Dried oregano', amount: 1, unit: 'tbsp' },
      { name: 'Cucumber', amount: 1, unit: 'large' },
      { name: 'Cherry tomatoes', amount: 200, unit: 'g' },
      { name: 'Kalamata olives', amount: 60, unit: 'g' },
      { name: 'Red onion', amount: 1, unit: 'small' },
      { name: 'Cooked rice', amount: 400, unit: 'g' },
      { name: 'Fresh dill', amount: 20, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cut chicken thighs into 3cm cubes. Mix with 100g yogurt, lemon juice, 2 tbsp olive oil, minced garlic, and oregano. Marinate 30 minutes or overnight.' },
      { stepNumber: 2, instruction: 'Thread chicken onto skewers. Grill over medium-high heat or broil for 10-12 minutes, turning occasionally, until charred and cooked through.' },
      { stepNumber: 3, instruction: 'Grate cucumber and squeeze out excess water. Mix with remaining yogurt, dill, remaining olive oil, and salt for tzatziki.' },
      { stepNumber: 4, instruction: 'Halve tomatoes, slice onion thinly. Arrange rice in bowls, top with chicken, vegetables, and olives.' },
      { stepNumber: 5, instruction: 'Dollop tzatziki generously over each bowl. Serve with warm pita if desired.' },
    ],
    nutrition: { calories: 540, protein: 38, carbs: 38, fat: 24, fiber: 4 },
    tips: [
      'Chicken thighs stay juicier than breast on the grill — worth the extra fat.',
      'Soak wooden skewers in water for 30 minutes so they do not burn.',
      'Add crumbled feta for extra authenticity and creaminess.',
    ],
  },
  {
    id: 'r167',
    title: 'Black Bean & Quinoa Stuffed Peppers',
    description: 'Colorful bell peppers stuffed with a spiced black bean and quinoa filling, topped with melted cheese. Hearty and protein-rich.',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    servings: 4,
    rating: 4.5,
    ratingCount: 2000,
    ingredients: [
      { name: 'Bell peppers', amount: 4, unit: 'large' },
      { name: 'Black beans', amount: 400, unit: 'g' },
      { name: 'Quinoa', amount: 150, unit: 'g' },
      { name: 'Corn kernels', amount: 150, unit: 'g' },
      { name: 'Cheddar cheese', amount: 120, unit: 'g' },
      { name: 'Canned diced tomatoes', amount: 200, unit: 'g' },
      { name: 'Cumin', amount: 1, unit: 'tsp' },
      { name: 'Chili powder', amount: 1, unit: 'tsp' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Fresh cilantro', amount: 30, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook quinoa in 300ml water for 15 minutes until fluffy. Let cool slightly.' },
      { stepNumber: 2, instruction: 'Cut tops off bell peppers and remove seeds. Blanch in boiling water for 3 minutes to soften slightly. Drain.' },
      { stepNumber: 3, instruction: 'Mix quinoa, drained black beans, corn, diced tomatoes, cumin, chili powder, minced garlic, salt, and pepper in a bowl.' },
      { stepNumber: 4, instruction: 'Stuff each pepper with the filling, pressing down gently. Place in a baking dish.' },
      { stepNumber: 5, instruction: 'Sprinkle shredded cheese over each stuffed pepper. Cover dish with foil.' },
      { stepNumber: 6, instruction: 'Bake at 190°C for 25 minutes. Remove foil and bake 10 more minutes until cheese is bubbly and peppers are tender.' },
    ],
    nutrition: { calories: 460, protein: 22, carbs: 56, fat: 16, fiber: 14 },
    tips: [
      'Use a mix of colored peppers — red, yellow, orange — for visual appeal.',
      'These reheat beautifully and make excellent meal prep for the week.',
      'Swap cheddar for pepper jack if you want a little heat.',
    ],
  },
  {
    id: 'r168',
    title: 'Protein Smoothie Bowl',
    description: 'A thick, spoonable smoothie bowl blended with protein powder, frozen berries, and banana. Topped with granola, chia, and almond butter.',
    imageUrl: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600',
    mealType: ['breakfast', 'snack'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    rating: 4.6,
    ratingCount: 3100,
    ingredients: [
      { name: 'Vanilla protein powder', amount: 30, unit: 'g' },
      { name: 'Frozen mixed berries', amount: 150, unit: 'g' },
      { name: 'Frozen banana', amount: 1, unit: 'medium' },
      { name: 'Almond milk', amount: 120, unit: 'ml' },
      { name: 'Greek yogurt', amount: 100, unit: 'g' },
      { name: 'Chia seeds', amount: 10, unit: 'g' },
      { name: 'Granola', amount: 30, unit: 'g' },
      { name: 'Almond butter', amount: 15, unit: 'g' },
      { name: 'Fresh strawberries', amount: 3, unit: 'pieces' },
      { name: 'Shredded coconut', amount: 10, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Add protein powder, frozen berries, frozen banana, almond milk, and Greek yogurt to a high-speed blender.' },
      { stepNumber: 2, instruction: 'Blend on high, using a tamper if needed, until thick and completely smooth. It should be thick enough to eat with a spoon.' },
      { stepNumber: 3, instruction: 'Pour into a bowl. Arrange toppings in sections: granola, chia seeds, almond butter drizzle, strawberry slices, and coconut.' },
      { stepNumber: 4, instruction: 'Serve immediately before it melts. Enjoy with a spoon, not a straw.' },
    ],
    nutrition: { calories: 480, protein: 32, carbs: 52, fat: 14, fiber: 10 },
    tips: [
      'Use a frozen banana for thickness — a fresh one will make it too runny.',
      'Do not add too much liquid — start with 120ml and add only if the blender is stuck.',
      'Change up toppings: try cacao nibs, hemp seeds, or fresh mango.',
    ],
  },
  {
    id: 'r169',
    title: 'Grilled Lamb Chops with Mint Yogurt',
    description: 'Tender grilled lamb chops marinated in garlic and rosemary, served with a refreshing mint yogurt sauce and roasted vegetables.',
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6f54262?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 2,
    rating: 4.8,
    ratingCount: 2400,
    ingredients: [
      { name: 'Lamb rib chops', amount: 8, unit: 'pieces' },
      { name: 'Fresh rosemary', amount: 2, unit: 'sprigs' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Greek yogurt', amount: 150, unit: 'g' },
      { name: 'Fresh mint', amount: 20, unit: 'g' },
      { name: 'Lemon juice', amount: 1, unit: 'tbsp' },
      { name: 'Zucchini', amount: 2, unit: 'medium' },
      { name: 'Red bell pepper', amount: 2, unit: 'pieces' },
      { name: 'Red onion', amount: 1, unit: 'small' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Rub lamb chops with minced garlic, chopped rosemary, olive oil, salt, and pepper. Let sit at room temperature for 20 minutes.' },
      { stepNumber: 2, instruction: 'Mix Greek yogurt, chopped fresh mint, lemon juice, and a pinch of salt. Chill until serving.' },
      { stepNumber: 3, instruction: 'Grill lamb chops over high heat for 3-4 minutes per side for medium-rare. Let rest 3 minutes.' },
      { stepNumber: 4, instruction: 'Toss zucchini, bell pepper, and onion with olive oil. Grill alongside lamb for 8-10 minutes until charred.' },
      { stepNumber: 5, instruction: 'Serve lamb chops with grilled vegetables and a generous spoonful of mint yogurt sauce.' },
    ],
    nutrition: { calories: 560, protein: 42, carbs: 16, fat: 36, fiber: 4 },
    tips: [
      'Let lamb rest after grilling — juices redistribute and the meat becomes more tender.',
      'The mint yogurt is also excellent with grilled chicken or as a veggie dip.',
      'If you prefer well-done lamb, cook 5-6 minutes per side over medium heat.',
    ],
  },
  {
    id: 'r170',
    title: 'Turkey Chili with Beans',
    description: 'A hearty, warming chili made with lean ground turkey, three kinds of beans, and a rich tomato-chili base. Perfect for meal prep.',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'spicy'],
    dietTags: ['high-protein', 'dairy-free', 'gluten-free'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    servings: 6,
    rating: 4.6,
    ratingCount: 2600,
    ingredients: [
      { name: 'Ground turkey', amount: 600, unit: 'g' },
      { name: 'Kidney beans', amount: 400, unit: 'g' },
      { name: 'Black beans', amount: 400, unit: 'g' },
      { name: 'Pinto beans', amount: 400, unit: 'g' },
      { name: 'Crushed tomatoes', amount: 800, unit: 'g' },
      { name: 'Tomato paste', amount: 60, unit: 'g' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Bell pepper', amount: 2, unit: 'pieces' },
      { name: 'Chili powder', amount: 2, unit: 'tbsp' },
      { name: 'Cumin', amount: 1, unit: 'tbsp' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Beef broth', amount: 250, unit: 'ml' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Dice onion and bell pepper. Mince garlic.' },
      { stepNumber: 2, instruction: 'Heat olive oil in a large pot. Brown turkey, breaking it apart, for 6-7 minutes. Remove excess fat if needed.' },
      { stepNumber: 3, instruction: 'Add onion, pepper, and garlic. Cook 5 minutes until softened.' },
      { stepNumber: 4, instruction: 'Stir in chili powder, cumin, tomato paste, crushed tomatoes, broth, and all drained beans.' },
      { stepNumber: 5, instruction: 'Bring to a boil, then reduce heat and simmer uncovered for 30 minutes, stirring occasionally, until thick and flavorful.' },
      { stepNumber: 6, instruction: 'Taste and adjust salt. Serve with diced avocado, cilantro, or a squeeze of lime.' },
    ],
    nutrition: { calories: 440, protein: 32, carbs: 48, fat: 12, fiber: 16 },
    tips: [
      'Using three bean varieties gives better texture and visual interest than just one.',
      'This chili is even better the next day — flavors deepen overnight.',
      'Top with Greek yogurt instead of sour cream for extra protein.',
    ],
  },
  {
    id: 'r171',
    title: 'Egg Muffin Cups with Veggies',
    description: 'Portable, high-protein egg muffins baked with spinach, tomatoes, and cheese. Perfect for meal prep breakfasts.',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600',
    mealType: ['breakfast', 'snack'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 6,
    rating: 4.5,
    ratingCount: 3200,
    ingredients: [
      { name: 'Eggs', amount: 10, unit: 'large' },
      { name: 'Baby spinach', amount: 100, unit: 'g' },
      { name: 'Cherry tomatoes', amount: 150, unit: 'g' },
      { name: 'Feta cheese', amount: 80, unit: 'g' },
      { name: 'Bell pepper', amount: 1, unit: 'piece' },
      { name: 'Milk', amount: 60, unit: 'ml' },
      { name: 'Olive oil', amount: 1, unit: 'tsp' },
      { name: 'Dried oregano', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 180°C. Grease a 12-cup muffin tin with olive oil or use silicone liners.' },
      { stepNumber: 2, instruction: 'Whisk eggs with milk, oregano, salt, and pepper in a large bowl.' },
      { stepNumber: 3, instruction: 'Chop spinach, halve tomatoes, and dice bell pepper. Distribute evenly among muffin cups.' },
      { stepNumber: 4, instruction: 'Pour egg mixture into each cup, filling about 3/4 full. Crumble feta on top.' },
      { stepNumber: 5, instruction: 'Bake 18-20 minutes until set and slightly puffed. Let cool 5 minutes before removing.' },
    ],
    nutrition: { calories: 180, protein: 14, carbs: 4, fat: 12, fiber: 1 },
    tips: [
      'Each muffin is roughly 2 eggs worth — adjust for your protein needs.',
      'These reheat in 30 seconds in the microwave and keep for 5 days refrigerated.',
      'Try ham and broccoli, or mushroom and swiss variations — just keep the base ratio the same.',
    ],
  },
  {
    id: 'r172',
    title: 'Peanut Butter Protein Bars',
    description: 'No-bake protein bars made with oats, peanut butter, honey, and protein powder. Chewy, satisfying, and perfect for post-workout.',
    imageUrl: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=600',
    mealType: ['snack', 'dessert'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['high-protein', 'vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 10,
    rating: 4.6,
    ratingCount: 2800,
    ingredients: [
      { name: 'Rolled oats', amount: 200, unit: 'g' },
      { name: 'Protein powder', amount: 60, unit: 'g' },
      { name: 'Peanut butter', amount: 200, unit: 'g' },
      { name: 'Honey', amount: 120, unit: 'g' },
      { name: 'Vanilla extract', amount: 1, unit: 'tsp' },
      { name: 'Dark chocolate chips', amount: 60, unit: 'g' },
      { name: 'Chia seeds', amount: 20, unit: 'g' },
      { name: 'Almond milk', amount: 60, unit: 'ml' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Line an 8x8 inch pan with parchment paper, leaving overhang for easy removal.' },
      { stepNumber: 2, instruction: 'In a large bowl, mix oats, protein powder, and chia seeds.' },
      { stepNumber: 3, instruction: 'Add peanut butter, honey, vanilla, and almond milk. Stir until a thick, sticky dough forms.' },
      { stepNumber: 4, instruction: 'Fold in chocolate chips. Press mixture firmly into the prepared pan, smoothing the top.' },
      { stepNumber: 5, instruction: 'Refrigerate for at least 2 hours until firm. Lift out using parchment and cut into 10 bars.' },
      { stepNumber: 6, instruction: 'Store in the fridge for up to 2 weeks or freeze individually wrapped for up to 3 months.' },
    ],
    nutrition: { calories: 320, protein: 16, carbs: 34, fat: 14, fiber: 5 },
    tips: [
      'Press the mixture VERY firmly into the pan or the bars will crumble when cut.',
      'Use crunchy peanut butter for extra texture, or smooth for classic chew.',
      'If too dry, add almond milk 1 tbsp at a time. If too sticky, add more oats.',
    ],
  },
  {
    id: 'r173',
    title: 'Cauliflower Crust Chicken Pizza',
    description: 'A crispy cauliflower pizza crust topped with marinara, mozzarella, and grilled chicken. Low-carb and protein-packed.',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    servings: 2,
    rating: 4.4,
    ratingCount: 1900,
    ingredients: [
      { name: 'Cauliflower', amount: 1, unit: 'large head' },
      { name: 'Egg', amount: 1, unit: 'large' },
      { name: 'Parmesan cheese', amount: 60, unit: 'g' },
      { name: 'Mozzarella cheese', amount: 120, unit: 'g' },
      { name: 'Chicken breast', amount: 200, unit: 'g' },
      { name: 'Marinara sauce', amount: 120, unit: 'g' },
      { name: 'Italian seasoning', amount: 1, unit: 'tsp' },
      { name: 'Garlic powder', amount: 1, unit: 'tsp' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Fresh basil', amount: 10, unit: 'g' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Rice cauliflower in a food processor. Microwave 8 minutes. Let cool, then squeeze out ALL moisture using a clean towel.' },
      { stepNumber: 2, instruction: 'Mix cauliflower rice with egg, parmesan, half the mozzarella, Italian seasoning, and garlic powder. Form into a flat round on parchment.' },
      { stepNumber: 3, instruction: 'Bake crust at 200°C for 15-20 minutes until golden and firm. Flip and bake 5 more minutes.' },
      { stepNumber: 4, instruction: 'While crust bakes, dice chicken and sauté in olive oil until cooked through, about 6 minutes.' },
      { stepNumber: 5, instruction: 'Spread marinara on baked crust. Top with chicken and remaining mozzarella. Bake 8-10 minutes until cheese melts.' },
      { stepNumber: 6, instruction: 'Garnish with fresh basil. Slice and serve immediately while crust is crisp.' },
    ],
    nutrition: { calories: 480, protein: 42, carbs: 18, fat: 28, fiber: 6 },
    tips: [
      'Squeezing moisture from cauliflower is THE critical step — skip it and the crust will be soggy.',
      'Pre-riced frozen cauliflower works too — just thaw and squeeze before using.',
      'Add any toppings you like: mushrooms, olives, peppers, or spinach all work great.',
    ],
  },
  {
    id: 'r174',
    title: 'Miso Glazed Cod with Bok Choy',
    description: 'Delicate cod fillets glazed with a sweet-savory miso marinade, broiled until caramelized. Served with garlicky baby bok choy.',
    imageUrl: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'sweet'],
    dietTags: ['high-protein', 'dairy-free'],
    difficulty: 'medium',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.7,
    ratingCount: 1500,
    ingredients: [
      { name: 'Cod fillets', amount: 400, unit: 'g' },
      { name: 'White miso paste', amount: 2, unit: 'tbsp' },
      { name: 'Mirin', amount: 2, unit: 'tbsp' },
      { name: 'Soy sauce', amount: 1, unit: 'tbsp' },
      { name: 'Honey', amount: 1, unit: 'tbsp' },
      { name: 'Baby bok choy', amount: 4, unit: 'heads' },
      { name: 'Garlic', amount: 2, unit: 'cloves' },
      { name: 'Ginger', amount: 1, unit: 'tbsp' },
      { name: 'Sesame oil', amount: 1, unit: 'tsp' },
      { name: 'Sesame seeds', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mix miso, mirin, soy sauce, and honey into a smooth paste. Coat cod fillets and marinate 15 minutes or up to 4 hours.' },
      { stepNumber: 2, instruction: 'Line a baking sheet with foil. Place marinated cod on top. Broil 8-10 minutes until glaze is caramelized and fish flakes.' },
      { stepNumber: 3, instruction: 'Halve bok choy lengthwise. Heat sesame oil in a skillet over medium-high heat.' },
      { stepNumber: 4, instruction: 'Add garlic and ginger. Cook 30 seconds until fragrant. Add bok choy cut-side down. Sear 3 minutes.' },
      { stepNumber: 5, instruction: 'Add 2 tbsp water, cover, and steam 2 minutes until tender but still bright green.' },
      { stepNumber: 6, instruction: 'Serve cod over rice or on its own, with bok choy alongside. Sprinkle sesame seeds on top.' },
    ],
    nutrition: { calories: 320, protein: 38, carbs: 18, fat: 10, fiber: 3 },
    tips: [
      'Miso is naturally salty — taste before adding extra salt to the marinade.',
      'The broiler gives the best caramelization, but baking at 200°C works too.',
      'Halibut, sea bass, or black cod are excellent substitutions.',
    ],
  },
  {
    id: 'r175',
    title: 'Steak & Eggs Breakfast Plate',
    description: 'A classic high-protein breakfast with a lean sirloin steak, two sunny-side-up eggs, and sautéed mushrooms. Pure power fuel.',
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600',
    mealType: ['breakfast', 'brunch'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['high-protein', 'keto', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 1,
    rating: 4.8,
    ratingCount: 3500,
    ingredients: [
      { name: 'Sirloin steak', amount: 200, unit: 'g' },
      { name: 'Eggs', amount: 2, unit: 'large' },
      { name: 'Mushrooms', amount: 150, unit: 'g' },
      { name: 'Butter', amount: 15, unit: 'g' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Garlic', amount: 1, unit: 'clove' },
      { name: 'Fresh thyme', amount: 3, unit: 'sprigs' },
      { name: 'Black pepper', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Season steak generously with salt and pepper. Let sit at room temperature for 15 minutes.' },
      { stepNumber: 2, instruction: 'Heat olive oil in a skillet over high heat. Sear steak 3-4 minutes per side for medium-rare. Let rest 5 minutes.' },
      { stepNumber: 3, instruction: 'In the same pan, add butter, sliced mushrooms, minced garlic, and thyme. Sauté 5 minutes until golden.' },
      { stepNumber: 4, instruction: 'Push mushrooms to one side. Crack eggs into the pan. Cook 2-3 minutes for sunny-side-up, or flip for over-easy.' },
      { stepNumber: 5, instruction: 'Slice steak against the grain. Plate with eggs and mushrooms. Spoon any pan juices over the top.' },
    ],
    nutrition: { calories: 560, protein: 48, carbs: 6, fat: 38, fiber: 2 },
    tips: [
      'Sirloin is lean but flavorful — flank or strip steak work too if you want more marbling.',
      'Baste the eggs with hot butter from the pan for a restaurant-style finish.',
      'Add a side of sautéed spinach for extra vitamins without extra carbs.',
    ],
  },
];
