export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'dessert';
export type TasteTag = 'spicy' | 'not-spicy' | 'sweet' | 'savory' | 'sour';
export type DietTag = 'vegan' | 'vegetarian' | 'keto' | 'gluten-free' | 'dairy-free' | 'high-protein';
export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Ingredient {
  name: string;
  amount: number;
  unit: string;
}

export interface RecipeStep {
  stepNumber: number;
  instruction: string;
  timerMinutes?: number;
}

export interface Nutrition {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface Recipe {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  mealType: MealType[];
  tasteTags: TasteTag[];
  dietTags: DietTag[];
  difficulty: Difficulty;
  prepTimeMinutes: number;
  cookTimeMinutes: number;
  servings: number;
  rating: number;
  ratingCount: number;
  ingredients: Ingredient[];
  steps: RecipeStep[];
  nutrition: Nutrition;
  tips: string[];
  isFeatured?: boolean;
  isTrending?: boolean;
  isPremium?: boolean;
}

const _BASE_RECIPES: Recipe[] = [
  {
    id: 'r001',
    title: 'Classic Avocado Toast with Poached Eggs',
    description: 'Creamy avocado on toasted sourdough topped with perfectly poached eggs, red pepper flakes, and a drizzle of olive oil. A breakfast staple that never gets old.',
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600',
    mealType: ['breakfast'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    rating: 4.8,
    ratingCount: 12450,
    isFeatured: true,
    ingredients: [
      { name: 'Sourdough bread', amount: 2, unit: 'slices' },
      { name: 'Ripe avocado', amount: 1, unit: 'large' },
      { name: 'Eggs', amount: 2, unit: 'large' },
      { name: 'Lemon juice', amount: 1, unit: 'tbsp' },
      { name: 'Red pepper flakes', amount: 0.5, unit: 'tsp' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Salt', amount: 0.5, unit: 'tsp' },
      { name: 'Black pepper', amount: 0.25, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Toast the sourdough bread slices until golden and crispy.' },
      { stepNumber: 2, instruction: 'Halve the avocado, remove the pit, and scoop the flesh into a bowl. Add lemon juice, salt, and pepper. Mash to your desired consistency.' },
      { stepNumber: 3, instruction: 'Bring a pot of water to a gentle simmer. Add a splash of vinegar. Create a gentle whirlpool and crack each egg into the center. Poach for 3 minutes.', timerMinutes: 3 },
      { stepNumber: 4, instruction: 'Spread the mashed avocado generously on each toast slice.' },
      { stepNumber: 5, instruction: 'Top each toast with a poached egg. Drizzle with olive oil and sprinkle with red pepper flakes. Serve immediately.' },
    ],
    nutrition: { calories: 380, protein: 14, carbs: 32, fat: 22, fiber: 8 },
    tips: [
      'Use very fresh eggs for the best poaching results.',
      'Add a splash of white vinegar to the poaching water to help the egg white set faster.',
      'For extra flavor, rub the toast with a garlic clove while still warm.',
    ],
  },
  {
    id: 'r002',
    title: 'Spicy Thai Basil Chicken (Pad Krapow Gai)',
    description: 'An authentic Thai street food classic — minced chicken stir-fried with fresh Thai basil, bird\'s eye chilies, and oyster sauce. Served over jasmine rice with a fried egg.',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['spicy', 'savory'],
    dietTags: ['high-protein', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.9,
    ratingCount: 8920,
    isFeatured: true,
    isTrending: true,
    ingredients: [
      { name: 'Ground chicken', amount: 400, unit: 'g' },
      { name: 'Thai basil leaves', amount: 1, unit: 'cup' },
      { name: 'Bird\'s eye chilies', amount: 4, unit: 'pieces' },
      { name: 'Garlic cloves', amount: 4, unit: 'cloves' },
      { name: 'Oyster sauce', amount: 2, unit: 'tbsp' },
      { name: 'Fish sauce', amount: 1, unit: 'tbsp' },
      { name: 'Soy sauce', amount: 1, unit: 'tbsp' },
      { name: 'Sugar', amount: 1, unit: 'tsp' },
      { name: 'Vegetable oil', amount: 2, unit: 'tbsp' },
      { name: 'Jasmine rice', amount: 1, unit: 'cup' },
      { name: 'Eggs', amount: 2, unit: 'large' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook jasmine rice according to package instructions.', timerMinutes: 15 },
      { stepNumber: 2, instruction: 'Pound or mince garlic and chilies together into a rough paste using a mortar and pestle.' },
      { stepNumber: 3, instruction: 'Heat oil in a wok over high heat until smoking. Add the garlic-chili paste and stir-fry for 30 seconds until fragrant.' },
      { stepNumber: 4, instruction: 'Add ground chicken and break it up. Stir-fry for 3-4 minutes until cooked through.', timerMinutes: 4 },
      { stepNumber: 5, instruction: 'Add oyster sauce, fish sauce, soy sauce, and sugar. Toss to combine and cook for 1 minute.' },
      { stepNumber: 6, instruction: 'Turn off heat and fold in the Thai basil leaves until just wilted.' },
      { stepNumber: 7, instruction: 'Fry eggs sunny-side up in a separate pan. Serve chicken over rice topped with the fried egg.' },
    ],
    nutrition: { calories: 520, protein: 38, carbs: 48, fat: 18, fiber: 2 },
    tips: [
      'Use a very hot wok for authentic "wok hei" (breath of the wok) flavor.',
      'Holy basil is traditional, but Italian basil works as a substitute.',
      'Adjust chili quantity to your heat preference.',
    ],
  },
  {
    id: 'r003',
    title: 'Creamy Tuscan Salmon',
    description: 'Pan-seared salmon fillets in a rich, creamy sun-dried tomato and spinach sauce. Restaurant-quality dinner ready in under 30 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600',
    mealType: ['dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['gluten-free', 'high-protein', 'keto'],
    difficulty: 'medium',
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 2,
    rating: 4.7,
    ratingCount: 6340,
    isTrending: true,
    ingredients: [
      { name: 'Salmon fillets', amount: 2, unit: 'pieces' },
      { name: 'Heavy cream', amount: 0.5, unit: 'cup' },
      { name: 'Sun-dried tomatoes', amount: 0.25, unit: 'cup' },
      { name: 'Baby spinach', amount: 2, unit: 'cups' },
      { name: 'Garlic cloves', amount: 3, unit: 'cloves' },
      { name: 'Parmesan cheese', amount: 0.25, unit: 'cup' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Italian seasoning', amount: 1, unit: 'tsp' },
      { name: 'Salt and pepper', amount: 1, unit: 'to taste' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Season salmon fillets generously with salt, pepper, and Italian seasoning on both sides.' },
      { stepNumber: 2, instruction: 'Heat olive oil in a large skillet over medium-high heat. Sear salmon skin-side up for 4 minutes, flip and cook 3 more minutes. Remove and set aside.', timerMinutes: 7 },
      { stepNumber: 3, instruction: 'In the same pan, sauté minced garlic for 30 seconds. Add sun-dried tomatoes and cook for 1 minute.' },
      { stepNumber: 4, instruction: 'Pour in heavy cream and bring to a simmer. Add parmesan and stir until melted and sauce thickens slightly.', timerMinutes: 3 },
      { stepNumber: 5, instruction: 'Add spinach and stir until wilted. Return salmon to the pan and spoon sauce over the top. Serve immediately.' },
    ],
    nutrition: { calories: 580, protein: 42, carbs: 8, fat: 42, fiber: 2 },
    tips: [
      'Pat salmon dry before searing for a better crust.',
      'Don\'t overcrowd the pan — cook salmon in batches if needed.',
      'Serve with crusty bread or pasta to soak up the sauce.',
    ],
  },
  {
    id: 'r004',
    title: 'Overnight Oats with Berries',
    description: 'Effortless, nutritious breakfast prepared the night before. Creamy oats soaked in almond milk, topped with fresh berries, honey, and crunchy granola.',
    imageUrl: 'https://images.unsplash.com/photo-1504387828636-abeb50778c0c?w=600',
    mealType: ['breakfast'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegan', 'vegetarian', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    rating: 4.6,
    ratingCount: 9870,
    ingredients: [
      { name: 'Rolled oats', amount: 0.5, unit: 'cup' },
      { name: 'Almond milk', amount: 0.75, unit: 'cup' },
      { name: 'Chia seeds', amount: 1, unit: 'tbsp' },
      { name: 'Maple syrup', amount: 1, unit: 'tbsp' },
      { name: 'Vanilla extract', amount: 0.5, unit: 'tsp' },
      { name: 'Mixed berries', amount: 0.5, unit: 'cup' },
      { name: 'Granola', amount: 2, unit: 'tbsp' },
      { name: 'Almond butter', amount: 1, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'In a jar or container, combine oats, almond milk, chia seeds, maple syrup, and vanilla extract. Stir well.' },
      { stepNumber: 2, instruction: 'Cover and refrigerate overnight (or at least 4 hours).', timerMinutes: 0 },
      { stepNumber: 3, instruction: 'In the morning, give the oats a good stir. Add a splash more milk if too thick.' },
      { stepNumber: 4, instruction: 'Top with fresh berries, granola, and a drizzle of almond butter. Enjoy cold!' },
    ],
    nutrition: { calories: 420, protein: 12, carbs: 62, fat: 14, fiber: 10 },
    tips: [
      'Prep 5 jars on Sunday for a full week of breakfasts.',
      'Add protein powder to boost the protein content.',
      'Frozen berries work just as well as fresh ones.',
    ],
  },
  {
    id: 'r005',
    title: 'Smoky BBQ Pulled Pork Tacos',
    description: 'Slow-cooked pulled pork with smoky BBQ sauce piled into warm corn tortillas with crunchy coleslaw and pickled jalapeños. A crowd-pleaser every time.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['spicy', 'savory', 'sweet'],
    dietTags: ['dairy-free', 'gluten-free'],
    difficulty: 'medium',
    prepTimeMinutes: 20,
    cookTimeMinutes: 240,
    servings: 6,
    rating: 4.8,
    ratingCount: 5670,
    isTrending: true,
    isPremium: true,
    ingredients: [
      { name: 'Pork shoulder', amount: 1.5, unit: 'kg' },
      { name: 'BBQ sauce', amount: 1, unit: 'cup' },
      { name: 'Smoked paprika', amount: 2, unit: 'tbsp' },
      { name: 'Garlic powder', amount: 1, unit: 'tbsp' },
      { name: 'Brown sugar', amount: 2, unit: 'tbsp' },
      { name: 'Corn tortillas', amount: 12, unit: 'pieces' },
      { name: 'Coleslaw mix', amount: 2, unit: 'cups' },
      { name: 'Pickled jalapeños', amount: 0.25, unit: 'cup' },
      { name: 'Lime', amount: 2, unit: 'pieces' },
      { name: 'Cilantro', amount: 0.5, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mix smoked paprika, garlic powder, brown sugar, salt, and pepper. Rub all over the pork shoulder.' },
      { stepNumber: 2, instruction: 'Place pork in a slow cooker. Pour half the BBQ sauce over it. Cook on low for 8 hours or high for 4 hours.', timerMinutes: 240 },
      { stepNumber: 3, instruction: 'Remove pork and shred with two forks. Mix with remaining BBQ sauce and some cooking liquid.' },
      { stepNumber: 4, instruction: 'Warm corn tortillas in a dry skillet or directly over a gas flame.' },
      { stepNumber: 5, instruction: 'Assemble tacos: pulled pork, coleslaw, pickled jalapeños, cilantro, and a squeeze of lime.' },
    ],
    nutrition: { calories: 480, protein: 32, carbs: 38, fat: 20, fiber: 4 },
    tips: [
      'The longer you cook the pork, the more tender it becomes.',
      'Save the cooking liquid to keep leftover pork moist.',
      'Make a double batch and freeze half for quick weeknight meals.',
    ],
  },
  {
    id: 'r006',
    title: 'Chocolate Lava Cake',
    description: 'Decadent individual chocolate cakes with a warm, gooey molten center. Served with vanilla ice cream and a dusting of powdered sugar. Pure indulgence.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600',
    mealType: ['dessert'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegetarian'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 4,
    rating: 4.9,
    ratingCount: 14200,
    isFeatured: true,
    isPremium: true,
    ingredients: [
      { name: 'Dark chocolate (70%)', amount: 200, unit: 'g' },
      { name: 'Butter', amount: 100, unit: 'g' },
      { name: 'Eggs', amount: 4, unit: 'large' },
      { name: 'Egg yolks', amount: 2, unit: 'pieces' },
      { name: 'Sugar', amount: 0.5, unit: 'cup' },
      { name: 'All-purpose flour', amount: 0.25, unit: 'cup' },
      { name: 'Vanilla extract', amount: 1, unit: 'tsp' },
      { name: 'Cocoa powder', amount: 2, unit: 'tbsp' },
      { name: 'Powdered sugar', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 220°C (425°F). Butter 4 ramekins and dust with cocoa powder.' },
      { stepNumber: 2, instruction: 'Melt chocolate and butter together in a double boiler or microwave in 30-second intervals, stirring between each.', timerMinutes: 5 },
      { stepNumber: 3, instruction: 'Whisk eggs, egg yolks, and sugar together until pale and slightly thickened. Stir in vanilla.' },
      { stepNumber: 4, instruction: 'Fold the chocolate mixture into the egg mixture. Gently fold in flour until just combined.' },
      { stepNumber: 5, instruction: 'Divide batter among ramekins. Bake for 10-12 minutes until edges are set but center jiggles slightly.', timerMinutes: 12 },
      { stepNumber: 6, instruction: 'Let rest 1 minute, then run a knife around edges and invert onto plates. Dust with powdered sugar and serve immediately with ice cream.' },
    ],
    nutrition: { calories: 520, protein: 10, carbs: 52, fat: 32, fiber: 3 },
    tips: [
      'The key is underbaking — the center should still be liquid.',
      'You can refrigerate the unbaked batter for up to 24 hours.',
      'Use high-quality chocolate for the best flavor.',
    ],
  },
  {
    id: 'r007',
    title: 'Greek Salad with Grilled Chicken',
    description: 'A vibrant, refreshing Mediterranean salad with crisp vegetables, Kalamata olives, creamy feta, and juicy grilled chicken. Light, healthy, and incredibly satisfying.',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy', 'sour'],
    dietTags: ['gluten-free', 'high-protein'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.5,
    ratingCount: 7890,
    ingredients: [
      { name: 'Chicken breast', amount: 300, unit: 'g' },
      { name: 'Cherry tomatoes', amount: 1, unit: 'cup' },
      { name: 'Cucumber', amount: 1, unit: 'medium' },
      { name: 'Red onion', amount: 0.5, unit: 'medium' },
      { name: 'Kalamata olives', amount: 0.5, unit: 'cup' },
      { name: 'Feta cheese', amount: 100, unit: 'g' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Red wine vinegar', amount: 1, unit: 'tbsp' },
      { name: 'Dried oregano', amount: 1, unit: 'tsp' },
      { name: 'Lemon juice', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Season chicken with olive oil, lemon juice, oregano, salt, and pepper. Marinate for 10 minutes.' },
      { stepNumber: 2, instruction: 'Grill chicken over medium-high heat for 6-7 minutes per side until cooked through. Let rest 5 minutes, then slice.', timerMinutes: 14 },
      { stepNumber: 3, instruction: 'Halve tomatoes, slice cucumber and red onion. Combine in a large bowl with olives.' },
      { stepNumber: 4, instruction: 'Whisk together olive oil, red wine vinegar, oregano, salt, and pepper for the dressing.' },
      { stepNumber: 5, instruction: 'Toss salad with dressing. Top with crumbled feta and sliced chicken. Serve immediately.' },
    ],
    nutrition: { calories: 420, protein: 38, carbs: 14, fat: 24, fiber: 4 },
    tips: [
      'Don\'t overdress the salad — add dressing just before serving.',
      'Block feta is better than pre-crumbled for this salad.',
    ],
  },
  {
    id: 'r008',
    title: 'Banana Pancakes (3 Ingredients)',
    description: 'Fluffy, naturally sweet pancakes made with just bananas, eggs, and oats. No flour, no sugar, no dairy — and ready in 15 minutes. Perfect for a healthy breakfast.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600',
    mealType: ['breakfast'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegetarian', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    rating: 4.4,
    ratingCount: 11200,
    ingredients: [
      { name: 'Ripe bananas', amount: 2, unit: 'large' },
      { name: 'Eggs', amount: 2, unit: 'large' },
      { name: 'Rolled oats', amount: 0.5, unit: 'cup' },
      { name: 'Cinnamon', amount: 0.5, unit: 'tsp' },
      { name: 'Maple syrup', amount: 2, unit: 'tbsp' },
      { name: 'Fresh berries', amount: 0.5, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mash bananas in a bowl until smooth. Add eggs and whisk together.' },
      { stepNumber: 2, instruction: 'Stir in oats and cinnamon. Let batter rest for 2 minutes to thicken.' },
      { stepNumber: 3, instruction: 'Heat a non-stick pan over medium heat. Lightly grease with cooking spray or butter.' },
      { stepNumber: 4, instruction: 'Pour small rounds of batter (about 3 tbsp each). Cook 2-3 minutes until bubbles form, flip and cook 1-2 more minutes.', timerMinutes: 5 },
      { stepNumber: 5, instruction: 'Serve stacked with fresh berries and a drizzle of maple syrup.' },
    ],
    nutrition: { calories: 320, protein: 12, carbs: 52, fat: 7, fiber: 6 },
    tips: [
      'Use very ripe bananas with brown spots for the sweetest flavor.',
      'Keep pancakes small — they\'re easier to flip than large ones.',
    ],
  },
  {
    id: 'r009',
    title: 'Spicy Mango Chicken Curry',
    description: 'A vibrant, aromatic curry with tender chicken pieces in a rich mango-coconut sauce with warming spices. Serve with fluffy basmati rice and naan bread.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    mealType: ['dinner'],
    tasteTags: ['spicy', 'sweet', 'savory'],
    dietTags: ['dairy-free', 'gluten-free', 'high-protein'],
    difficulty: 'medium',
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 4,
    rating: 4.7,
    ratingCount: 4560,
    isFeatured: true,
    ingredients: [
      { name: 'Chicken thighs', amount: 600, unit: 'g' },
      { name: 'Mango', amount: 1, unit: 'large' },
      { name: 'Coconut milk', amount: 400, unit: 'ml' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Garlic cloves', amount: 4, unit: 'cloves' },
      { name: 'Ginger', amount: 1, unit: 'inch' },
      { name: 'Curry powder', amount: 2, unit: 'tbsp' },
      { name: 'Cayenne pepper', amount: 1, unit: 'tsp' },
      { name: 'Tomato paste', amount: 2, unit: 'tbsp' },
      { name: 'Basmati rice', amount: 1.5, unit: 'cups' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Dice chicken thighs into 2-inch pieces. Season with salt and pepper.' },
      { stepNumber: 2, instruction: 'Sauté diced onion in oil for 5 minutes until softened. Add minced garlic and ginger, cook 1 minute.', timerMinutes: 6 },
      { stepNumber: 3, instruction: 'Add curry powder and cayenne, stir for 30 seconds. Add tomato paste and cook 2 minutes.' },
      { stepNumber: 4, instruction: 'Add chicken and brown on all sides, about 5 minutes.', timerMinutes: 5 },
      { stepNumber: 5, instruction: 'Pour in coconut milk and add diced mango. Simmer for 20 minutes until chicken is cooked and sauce thickens.', timerMinutes: 20 },
      { stepNumber: 6, instruction: 'Cook basmati rice. Serve curry over rice, garnished with cilantro and a squeeze of lime.' },
    ],
    nutrition: { calories: 560, protein: 36, carbs: 52, fat: 22, fiber: 4 },
    tips: [
      'Use ripe but firm mango for the best texture.',
      'For a smoother sauce, blend half the curry before adding the chicken back.',
    ],
  },
  {
    id: 'r010',
    title: 'Keto Cauliflower Fried Rice',
    description: 'A low-carb twist on the takeout classic. Cauliflower rice stir-fried with vegetables, eggs, and soy sauce. You won\'t miss the real thing!',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['keto', 'gluten-free', 'dairy-free', 'vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.3,
    ratingCount: 6780,
    ingredients: [
      { name: 'Cauliflower head', amount: 1, unit: 'medium' },
      { name: 'Eggs', amount: 3, unit: 'large' },
      { name: 'Frozen peas and carrots', amount: 1, unit: 'cup' },
      { name: 'Green onions', amount: 4, unit: 'stalks' },
      { name: 'Garlic cloves', amount: 3, unit: 'cloves' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Sesame oil', amount: 1, unit: 'tbsp' },
      { name: 'Vegetable oil', amount: 2, unit: 'tbsp' },
      { name: 'Ginger', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cut cauliflower into florets and pulse in a food processor until it resembles rice. Don\'t over-process.' },
      { stepNumber: 2, instruction: 'Heat oil in a large wok or skillet over high heat. Add garlic and ginger, stir-fry 30 seconds.' },
      { stepNumber: 3, instruction: 'Add frozen vegetables and cook for 3 minutes until thawed and slightly tender.', timerMinutes: 3 },
      { stepNumber: 4, instruction: 'Push everything to the side. Scramble eggs in the empty space, then mix into the vegetables.' },
      { stepNumber: 5, instruction: 'Add cauliflower rice and stir-fry for 5-6 minutes until tender but not mushy.', timerMinutes: 6 },
      { stepNumber: 6, instruction: 'Add soy sauce and sesame oil. Toss well. Top with sliced green onions and serve.' },
    ],
    nutrition: { calories: 280, protein: 16, carbs: 18, fat: 16, fiber: 7 },
    tips: [
      'Don\'t overcook the cauliflower — it should still have some bite.',
      'Spread cauliflower on a baking sheet and roast for 10 min first for a drier texture.',
    ],
  },
  {
    id: 'r011',
    title: 'Homemade Margherita Pizza',
    description: 'The classic Neapolitan pizza with a crispy thin crust, San Marzano tomato sauce, fresh mozzarella, and fragrant basil. Simple perfection.',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600',
    mealType: ['dinner', 'lunch'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['vegetarian'],
    difficulty: 'medium',
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    servings: 4,
    rating: 4.8,
    ratingCount: 18900,
    isTrending: true,
    ingredients: [
      { name: 'Pizza dough', amount: 500, unit: 'g' },
      { name: 'San Marzano tomatoes', amount: 400, unit: 'g' },
      { name: 'Fresh mozzarella', amount: 250, unit: 'g' },
      { name: 'Fresh basil leaves', amount: 20, unit: 'leaves' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Garlic clove', amount: 1, unit: 'clove' },
      { name: 'Salt', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to maximum temperature (250°C/480°F) with a pizza stone or baking sheet inside for at least 30 minutes.', timerMinutes: 30 },
      { stepNumber: 2, instruction: 'Crush tomatoes by hand, mix with a pinch of salt and a drizzle of olive oil. Don\'t cook the sauce.' },
      { stepNumber: 3, instruction: 'Stretch dough on a floured surface to a thin 12-inch round.' },
      { stepNumber: 4, instruction: 'Spread tomato sauce leaving a 1-inch border. Tear mozzarella and distribute evenly.' },
      { stepNumber: 5, instruction: 'Slide onto hot pizza stone. Bake 10-12 minutes until crust is charred and cheese is bubbling.', timerMinutes: 12 },
      { stepNumber: 6, instruction: 'Remove from oven. Scatter fresh basil, drizzle with olive oil, and serve immediately.' },
    ],
    nutrition: { calories: 480, protein: 20, carbs: 62, fat: 16, fiber: 3 },
    tips: [
      'A very hot oven is essential for authentic pizza.',
      'Less is more with toppings — don\'t overload the pizza.',
      'Let the dough come to room temperature before stretching.',
    ],
  },
  {
    id: 'r012',
    title: 'Vegan Buddha Bowl',
    description: 'A nourishing, colorful bowl with roasted sweet potato, crispy chickpeas, quinoa, avocado, and a creamy tahini dressing. Meal prep friendly and endlessly customizable.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 2,
    rating: 4.6,
    ratingCount: 8340,
    ingredients: [
      { name: 'Sweet potato', amount: 1, unit: 'large' },
      { name: 'Canned chickpeas', amount: 400, unit: 'g' },
      { name: 'Quinoa', amount: 0.75, unit: 'cup' },
      { name: 'Avocado', amount: 1, unit: 'medium' },
      { name: 'Baby spinach', amount: 2, unit: 'cups' },
      { name: 'Cherry tomatoes', amount: 1, unit: 'cup' },
      { name: 'Tahini', amount: 3, unit: 'tbsp' },
      { name: 'Lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Cumin', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 200°C (400°F). Cube sweet potato and toss with olive oil, cumin, salt, and pepper.' },
      { stepNumber: 2, instruction: 'Drain and rinse chickpeas. Pat dry, toss with olive oil and paprika. Spread on a baking sheet with sweet potato. Roast 25-30 minutes.', timerMinutes: 30 },
      { stepNumber: 3, instruction: 'Cook quinoa: rinse, add to 1.5x water, bring to boil, simmer 15 minutes covered.', timerMinutes: 15 },
      { stepNumber: 4, instruction: 'Make tahini dressing: whisk tahini, lemon juice, garlic, and 2-3 tbsp water until smooth.' },
      { stepNumber: 5, instruction: 'Assemble bowls: quinoa base, spinach, roasted sweet potato, chickpeas, sliced avocado, and cherry tomatoes. Drizzle with tahini dressing.' },
    ],
    nutrition: { calories: 520, protein: 18, carbs: 68, fat: 22, fiber: 16 },
    tips: [
      'Roast chickpeas until very crispy for the best texture.',
      'Make extra tahini dressing — it keeps in the fridge for a week.',
    ],
  },
  {
    id: 'r013',
    title: 'Beef Tacos with Homemade Salsa',
    description: 'Seasoned ground beef in warm corn tortillas with fresh pico de gallo, shredded cheese, sour cream, and guacamole. Taco night done right.',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600',
    mealType: ['dinner', 'lunch'],
    tasteTags: ['spicy', 'savory'],
    dietTags: ['gluten-free'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    rating: 4.7,
    ratingCount: 9870,
    isTrending: true,
    ingredients: [
      { name: 'Ground beef', amount: 500, unit: 'g' },
      { name: 'Corn tortillas', amount: 12, unit: 'pieces' },
      { name: 'Tomatoes', amount: 3, unit: 'medium' },
      { name: 'Red onion', amount: 0.5, unit: 'medium' },
      { name: 'Jalapeño', amount: 1, unit: 'piece' },
      { name: 'Cilantro', amount: 0.5, unit: 'cup' },
      { name: 'Lime', amount: 2, unit: 'pieces' },
      { name: 'Taco seasoning', amount: 2, unit: 'tbsp' },
      { name: 'Shredded cheese', amount: 1, unit: 'cup' },
      { name: 'Sour cream', amount: 0.5, unit: 'cup' },
      { name: 'Avocados', amount: 2, unit: 'medium' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Make pico de gallo: dice tomatoes, red onion, and jalapeño. Mix with cilantro, lime juice, and salt. Set aside.' },
      { stepNumber: 2, instruction: 'Brown ground beef in a skillet over medium-high heat, breaking it up. Drain excess fat.', timerMinutes: 8 },
      { stepNumber: 3, instruction: 'Add taco seasoning and 0.25 cup water. Simmer 3 minutes until sauce thickens.', timerMinutes: 3 },
      { stepNumber: 4, instruction: 'Mash avocados with lime juice, salt, and a pinch of cumin for quick guacamole.' },
      { stepNumber: 5, instruction: 'Warm tortillas. Assemble tacos with beef, pico de gallo, guacamole, cheese, and sour cream.' },
    ],
    nutrition: { calories: 540, protein: 30, carbs: 42, fat: 28, fiber: 7 },
    tips: [
      'Double the pico de gallo — it\'s great on everything.',
      'Toast tortillas directly over a gas flame for authentic char.',
    ],
  },
  {
    id: 'r014',
    title: 'Protein Smoothie Bowl',
    description: 'A thick, creamy acai-style smoothie bowl packed with protein and topped with granola, fresh fruit, coconut flakes, and nut butter. The ultimate post-workout meal.',
    imageUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=600',
    mealType: ['breakfast', 'snack'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegetarian', 'gluten-free', 'high-protein'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 1,
    rating: 4.5,
    ratingCount: 7230,
    ingredients: [
      { name: 'Frozen banana', amount: 1, unit: 'large' },
      { name: 'Frozen mixed berries', amount: 1, unit: 'cup' },
      { name: 'Protein powder (vanilla)', amount: 1, unit: 'scoop' },
      { name: 'Greek yogurt', amount: 0.5, unit: 'cup' },
      { name: 'Almond milk', amount: 0.25, unit: 'cup' },
      { name: 'Granola', amount: 3, unit: 'tbsp' },
      { name: 'Fresh strawberries', amount: 5, unit: 'pieces' },
      { name: 'Almond butter', amount: 1, unit: 'tbsp' },
      { name: 'Coconut flakes', amount: 1, unit: 'tbsp' },
      { name: 'Honey', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Blend frozen banana, frozen berries, protein powder, Greek yogurt, and almond milk until thick and smooth. Add minimal liquid — it should be very thick.' },
      { stepNumber: 2, instruction: 'Pour into a bowl. Arrange granola, sliced strawberries, coconut flakes, and a drizzle of almond butter and honey on top.' },
      { stepNumber: 3, instruction: 'Serve immediately before it melts!' },
    ],
    nutrition: { calories: 480, protein: 32, carbs: 62, fat: 12, fiber: 8 },
    tips: [
      'The key is using frozen fruit for a thick, ice cream-like consistency.',
      'Chill your bowl in the freezer for 5 minutes before serving.',
    ],
  },
  {
    id: 'r015',
    title: 'Lemon Garlic Shrimp Pasta',
    description: 'Succulent shrimp in a bright lemon-garlic butter sauce tossed with linguine and fresh parsley. An elegant weeknight dinner ready in 20 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600',
    mealType: ['dinner', 'lunch'],
    tasteTags: ['savory', 'not-spicy', 'sour'],
    dietTags: ['high-protein', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 2,
    rating: 4.6,
    ratingCount: 8910,
    ingredients: [
      { name: 'Large shrimp', amount: 300, unit: 'g' },
      { name: 'Linguine', amount: 200, unit: 'g' },
      { name: 'Butter', amount: 3, unit: 'tbsp' },
      { name: 'Garlic cloves', amount: 5, unit: 'cloves' },
      { name: 'Lemon', amount: 1, unit: 'large' },
      { name: 'White wine', amount: 0.25, unit: 'cup' },
      { name: 'Red pepper flakes', amount: 0.5, unit: 'tsp' },
      { name: 'Fresh parsley', amount: 0.25, unit: 'cup' },
      { name: 'Parmesan', amount: 0.25, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook linguine in salted boiling water until al dente. Reserve 1 cup pasta water before draining.', timerMinutes: 10 },
      { stepNumber: 2, instruction: 'Season shrimp with salt, pepper, and red pepper flakes.' },
      { stepNumber: 3, instruction: 'Melt butter in a large skillet. Add minced garlic and cook 1 minute. Add shrimp and cook 2 minutes per side until pink.', timerMinutes: 5 },
      { stepNumber: 4, instruction: 'Remove shrimp. Add white wine and lemon juice to the pan. Simmer 2 minutes, scraping up any bits.', timerMinutes: 2 },
      { stepNumber: 5, instruction: 'Add pasta and toss, adding pasta water as needed for a silky sauce. Return shrimp, add parsley and parmesan. Serve with lemon wedges.' },
    ],
    nutrition: { calories: 560, protein: 36, carbs: 62, fat: 16, fiber: 3 },
    tips: [
      'Don\'t overcook the shrimp — they only need 2 minutes per side.',
      'The pasta water is key for creating a silky, emulsified sauce.',
    ],
  },
  {
    id: 'r016',
    title: 'Crispy Baked Chicken Wings',
    description: 'Incredibly crispy wings baked (not fried!) with a secret baking powder technique, tossed in your choice of buffalo, honey garlic, or BBQ sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600',
    mealType: ['snack', 'dinner'],
    tasteTags: ['spicy', 'savory'],
    dietTags: ['gluten-free', 'high-protein', 'dairy-free'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 45,
    servings: 4,
    rating: 4.8,
    ratingCount: 15600,
    isTrending: true,
    isPremium: true,
    ingredients: [
      { name: 'Chicken wings', amount: 1, unit: 'kg' },
      { name: 'Baking powder', amount: 1, unit: 'tbsp' },
      { name: 'Salt', amount: 1, unit: 'tsp' },
      { name: 'Garlic powder', amount: 1, unit: 'tsp' },
      { name: 'Hot sauce', amount: 0.25, unit: 'cup' },
      { name: 'Butter', amount: 3, unit: 'tbsp' },
      { name: 'Honey', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Pat wings completely dry with paper towels. This is crucial for crispiness.' },
      { stepNumber: 2, instruction: 'Toss wings with baking powder, salt, and garlic powder. Spread on a wire rack over a baking sheet. Refrigerate uncovered for 1 hour (or overnight).', timerMinutes: 60 },
      { stepNumber: 3, instruction: 'Preheat oven to 220°C (425°F). Bake wings for 20 minutes, flip, then bake 20-25 more minutes until very crispy.', timerMinutes: 45 },
      { stepNumber: 4, instruction: 'Make buffalo sauce: melt butter, mix with hot sauce and honey.' },
      { stepNumber: 5, instruction: 'Toss hot wings in sauce and serve immediately with celery and blue cheese dip.' },
    ],
    nutrition: { calories: 420, protein: 34, carbs: 8, fat: 28, fiber: 0 },
    tips: [
      'Baking powder (not soda) is the secret to crispy skin.',
      'The longer you dry-brine in the fridge, the crispier the wings.',
      'Use a wire rack so air circulates under the wings.',
    ],
  },
  {
    id: 'r017',
    title: 'Strawberry Cheesecake Overnight Oats',
    description: 'Indulgent yet healthy overnight oats that taste like cheesecake. Cream cheese, vanilla, and fresh strawberries make this breakfast feel like dessert.',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600',
    mealType: ['breakfast'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    rating: 4.7,
    ratingCount: 5430,
    ingredients: [
      { name: 'Rolled oats', amount: 0.5, unit: 'cup' },
      { name: 'Milk', amount: 0.5, unit: 'cup' },
      { name: 'Cream cheese', amount: 2, unit: 'tbsp' },
      { name: 'Honey', amount: 1, unit: 'tbsp' },
      { name: 'Vanilla extract', amount: 0.5, unit: 'tsp' },
      { name: 'Fresh strawberries', amount: 0.5, unit: 'cup' },
      { name: 'Graham cracker crumbs', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Soften cream cheese. Mix with milk, honey, and vanilla until smooth.' },
      { stepNumber: 2, instruction: 'Stir in oats. Cover and refrigerate overnight.' },
      { stepNumber: 3, instruction: 'In the morning, top with sliced strawberries and graham cracker crumbs for that cheesecake crust effect.' },
    ],
    nutrition: { calories: 390, protein: 11, carbs: 58, fat: 12, fiber: 5 },
    tips: [
      'Use full-fat cream cheese for the richest flavor.',
      'Layer the ingredients in a jar for a pretty presentation.',
    ],
  },
  {
    id: 'r018',
    title: 'Vegetable Stir-Fry with Tofu',
    description: 'Crispy golden tofu with colorful vegetables in a savory ginger-soy sauce. Quick, healthy, and packed with plant-based protein. Ready in 20 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
    mealType: ['lunch', 'dinner'],
    tasteTags: ['savory', 'not-spicy'],
    dietTags: ['vegan', 'vegetarian', 'dairy-free', 'gluten-free'],
    difficulty: 'easy',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.4,
    ratingCount: 6120,
    ingredients: [
      { name: 'Extra-firm tofu', amount: 400, unit: 'g' },
      { name: 'Broccoli florets', amount: 2, unit: 'cups' },
      { name: 'Bell peppers', amount: 2, unit: 'medium' },
      { name: 'Snap peas', amount: 1, unit: 'cup' },
      { name: 'Soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'Sesame oil', amount: 1, unit: 'tbsp' },
      { name: 'Ginger', amount: 1, unit: 'tbsp' },
      { name: 'Garlic cloves', amount: 3, unit: 'cloves' },
      { name: 'Cornstarch', amount: 1, unit: 'tbsp' },
      { name: 'Rice', amount: 1, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Press tofu for 15 minutes to remove excess moisture. Cut into 1-inch cubes and toss with cornstarch.' },
      { stepNumber: 2, instruction: 'Pan-fry tofu in oil over medium-high heat for 4-5 minutes per side until golden and crispy. Remove.', timerMinutes: 10 },
      { stepNumber: 3, instruction: 'In the same pan, stir-fry garlic and ginger for 30 seconds. Add broccoli and cook 3 minutes.' },
      { stepNumber: 4, instruction: 'Add bell peppers and snap peas. Stir-fry 2 minutes until crisp-tender.', timerMinutes: 2 },
      { stepNumber: 5, instruction: 'Return tofu. Add soy sauce and sesame oil. Toss to coat. Serve over rice.' },
    ],
    nutrition: { calories: 420, protein: 24, carbs: 48, fat: 14, fiber: 8 },
    tips: [
      'Pressing tofu is essential for crispiness — don\'t skip this step.',
      'Cornstarch coating helps tofu get extra crispy.',
    ],
  },
  {
    id: 'r019',
    title: 'Honey Garlic Salmon',
    description: 'Glazed salmon fillets with a sweet and savory honey-garlic sauce, pan-seared to perfection. One of the easiest and most impressive weeknight dinners.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600',
    mealType: ['dinner'],
    tasteTags: ['sweet', 'savory', 'not-spicy'],
    dietTags: ['gluten-free', 'dairy-free', 'high-protein', 'keto'],
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 2,
    rating: 4.8,
    ratingCount: 11340,
    isFeatured: true,
    ingredients: [
      { name: 'Salmon fillets', amount: 2, unit: 'pieces' },
      { name: 'Honey', amount: 3, unit: 'tbsp' },
      { name: 'Garlic cloves', amount: 4, unit: 'cloves' },
      { name: 'Soy sauce', amount: 2, unit: 'tbsp' },
      { name: 'Lemon juice', amount: 1, unit: 'tbsp' },
      { name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { name: 'Fresh parsley', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mix honey, minced garlic, soy sauce, and lemon juice in a small bowl.' },
      { stepNumber: 2, instruction: 'Season salmon with salt and pepper. Heat oil in a skillet over medium-high heat.' },
      { stepNumber: 3, instruction: 'Sear salmon skin-side up for 4 minutes. Flip and cook 3 minutes.', timerMinutes: 7 },
      { stepNumber: 4, instruction: 'Pour honey garlic sauce over salmon. Cook 2 more minutes, basting frequently, until sauce is caramelized.', timerMinutes: 2 },
      { stepNumber: 5, instruction: 'Garnish with fresh parsley and serve with roasted vegetables or rice.' },
    ],
    nutrition: { calories: 440, protein: 38, carbs: 22, fat: 20, fiber: 0 },
    tips: [
      'Don\'t move the salmon while searing — let it develop a crust.',
      'The sauce will thicken quickly, so watch it carefully.',
    ],
  },
  {
    id: 'r020',
    title: 'Chocolate Chip Banana Bread',
    description: 'Moist, tender banana bread loaded with chocolate chips. The perfect way to use overripe bananas. Smells incredible while baking and tastes even better.',
    imageUrl: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600',
    mealType: ['breakfast', 'snack', 'dessert'],
    tasteTags: ['sweet', 'not-spicy'],
    dietTags: ['vegetarian'],
    difficulty: 'easy',
    prepTimeMinutes: 10,
    cookTimeMinutes: 60,
    servings: 8,
    rating: 4.9,
    ratingCount: 22100,
    isTrending: true,
    ingredients: [
      { name: 'Overripe bananas', amount: 3, unit: 'large' },
      { name: 'All-purpose flour', amount: 1.5, unit: 'cups' },
      { name: 'Sugar', amount: 0.75, unit: 'cup' },
      { name: 'Butter', amount: 0.5, unit: 'cup' },
      { name: 'Eggs', amount: 2, unit: 'large' },
      { name: 'Baking soda', amount: 1, unit: 'tsp' },
      { name: 'Salt', amount: 0.5, unit: 'tsp' },
      { name: 'Vanilla extract', amount: 1, unit: 'tsp' },
      { name: 'Chocolate chips', amount: 1, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 175°C (350°F). Grease a 9x5 inch loaf pan.' },
      { stepNumber: 2, instruction: 'Mash bananas in a large bowl. Add melted butter, sugar, eggs, and vanilla. Mix well.' },
      { stepNumber: 3, instruction: 'Stir in flour, baking soda, and salt until just combined. Don\'t overmix.' },
      { stepNumber: 4, instruction: 'Fold in chocolate chips. Pour into prepared pan.' },
      { stepNumber: 5, instruction: 'Bake for 55-65 minutes until a toothpick inserted in the center comes out clean.', timerMinutes: 60 },
      { stepNumber: 6, instruction: 'Cool in pan for 10 minutes, then turn out onto a wire rack. Slice and serve warm.' },
    ],
    nutrition: { calories: 340, protein: 5, carbs: 52, fat: 14, fiber: 2 },
    tips: [
      'The blacker the bananas, the sweeter and more flavorful the bread.',
      'Don\'t overmix the batter — lumps are fine and keep the bread tender.',
      'Wrap tightly and it keeps for 3 days at room temperature.',
    ],
  },
];

import { NEW_RECIPES } from './recipes-new';
export const RECIPES: Recipe[] = [..._BASE_RECIPES, ...NEW_RECIPES];

// Helper functions
export function getFeaturedRecipes(): Recipe[] {
  return RECIPES.filter(r => r.isFeatured);
}

export function getTrendingRecipes(): Recipe[] {
  return RECIPES.filter(r => r.isTrending);
}

export function getRecipesByMealType(mealType: MealType): Recipe[] {
  return RECIPES.filter(r => r.mealType.includes(mealType));
}

export function getQuickRecipes(maxMinutes: number): Recipe[] {
  return RECIPES.filter(r => r.cookTimeMinutes + r.prepTimeMinutes <= maxMinutes);
}

export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return RECIPES.filter(r =>
    r.title.toLowerCase().includes(q) ||
    r.description.toLowerCase().includes(q) ||
    r.ingredients.some(i => i.name.toLowerCase().includes(q)) ||
    r.tasteTags.some(t => t.includes(q)) ||
    r.dietTags.some(t => t.includes(q))
  );
}

export function getRecipesByDiet(dietTag: DietTag): Recipe[] {
  return RECIPES.filter(r => r.dietTags.includes(dietTag));
}
