name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 2.25.170.135
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/buildany
            git fetch origin main
            git reset --hard origin/main
            npm install --legacy-peer-deps
            npm run build || exit 1
            pm2 restart buildany --update-env
